// Code generated by hertz generator.

package admin

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	maintenance "github.com/zy84338719/fileCodeBox/biz/model/maintenance"
	adminsvc "github.com/zy84338719/fileCodeBox/internal/app/admin"
)

var maintenanceService *adminsvc.Service

func init() {
	maintenanceService = adminsvc.NewService()
}

// CleanExpiredFiles .
// @router /admin/maintenance/clean-expired [POST]
func CleanExpiredFiles(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintenance.CleanExpiredFilesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用服务层清理过期文件
	deletedCount, freedSpace, err := maintenanceService.CleanExpiredFiles(ctx)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &maintenance.CleanExpiredFilesResp{
			Code:    500,
			Message: "清理失败: " + err.Error(),
		})
		return
	}

	resp := &maintenance.CleanExpiredFilesResp{
		Code:    200,
		Message: "清理完成",
		Data: &maintenance.CleanExpiredFilesData{
			DeletedCount: deletedCount,
			FreedSpace:   freedSpace,
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// CleanTempFiles .
// @router /admin/maintenance/clean-temp [POST]
func CleanTempFiles(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintenance.CleanTempFilesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用服务层清理临时文件
	deletedCount, _, err := maintenanceService.CleanTempFiles(ctx)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &maintenance.CleanTempFilesResp{
			Code:    500,
			Message: "清理失败: " + err.Error(),
		})
		return
	}

	resp := &maintenance.CleanTempFilesResp{
		Code:    200,
		Message: "清理完成",
		Data: &maintenance.CleanTempFilesData{
			DeletedCount: deletedCount,
			FreedSpace:   0,
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// GetSystemInfo .
// @router /admin/maintenance/system-info [GET]
func GetSystemInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintenance.GetSystemInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用服务层获取系统信息
	info, err := maintenanceService.GetSystemInfo(ctx)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &maintenance.GetSystemInfoResp{
			Code:    500,
			Message: "获取系统信息失败: " + err.Error(),
		})
		return
	}

	resp := &maintenance.GetSystemInfoResp{
		Code:    200,
		Message: "获取成功",
		Data: &maintenance.SystemInfoData{
			Version:     info.Version,
			Os:          info.OS,
			Arch:        info.Arch,
			Uptime:      info.Uptime,
			Goroutines:  info.Goroutines,
			MemoryAlloc: info.MemoryAlloc,
			MemoryTotal: info.MemoryTotal,
			MemorySys:   info.MemorySys,
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// GetStorageStatus .
// @router /admin/maintenance/monitor/storage [GET]
func GetStorageStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintenance.GetStorageStatusReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用服务层获取存储状态
	status, err := maintenanceService.GetStorageStatus(ctx)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &maintenance.GetStorageStatusResp{
			Code:    500,
			Message: "获取存储状态失败: " + err.Error(),
		})
		return
	}

	resp := &maintenance.GetStorageStatusResp{
		Code:    200,
		Message: "获取成功",
		Data: &maintenance.StorageStatusData{
			StorageType:  status.StorageType,
			TotalSpace:   status.TotalSpace,
			UsedSpace:    status.UsedSpace,
			FreeSpace:    status.FreeSpace,
			FileCount:    status.FileCount,
			UsagePercent: status.UsagePercent,
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// GetSystemLogs .
// @router /admin/maintenance/logs [GET]
func GetSystemLogs(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintenance.GetSystemLogsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 处理分页参数
	page := req.Page
	pageSize := req.PageSize
	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 || pageSize > 100 {
		pageSize = 20
	}

	// 调用服务层获取系统日志
	logs, total, err := maintenanceService.GetSystemLogs(ctx, req.Level, int(page), int(pageSize))
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &maintenance.GetSystemLogsResp{
			Code:    500,
			Message: "获取系统日志失败: " + err.Error(),
		})
		return
	}

	// 转换为响应格式
	logEntries := make([]*maintenance.LogEntry, len(logs))
	for i, log := range logs {
		logEntries[i] = &maintenance.LogEntry{
			Id:        log.ID,
			Level:     log.Level,
			Message:   log.Message,
			CreatedAt: log.CreatedAt,
			Module:    log.Module,
			UserId:    log.UserID,
		}
	}

	resp := &maintenance.GetSystemLogsResp{
		Code:    200,
		Message: "获取成功",
		Data: &maintenance.SystemLogsData{
			Logs:     logEntries,
			Total:    total,
			Page:     page,
			PageSize: pageSize,
		},
	}

	c.JSON(consts.StatusOK, resp)
}
