// Code generated by hertz generator.

package admin

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	admin "github.com/zy84338719/fileCodeBox/biz/model/admin"
)

// AdminLogin .
// @router /admin/login [POST]
func AdminLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminLoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminLoginResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminStats .
// @router /admin/stats [GET]
func AdminStats(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminStatsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminStatsResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminListFiles .
// @router /admin/files [GET]
func AdminListFiles(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminListFilesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminListFilesResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminDeleteFile .
// @router /admin/files/:id [DELETE]
func AdminDeleteFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminDeleteFileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminDeleteFileResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminListUsers .
// @router /admin/users [GET]
func AdminListUsers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminListUsersReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminListUsersResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminUpdateUserStatus .
// @router /admin/users/:id/status [PUT]
func AdminUpdateUserStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminUpdateUserStatusReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminUpdateUserStatusResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminGetConfig .
// @router /admin/config [GET]
func AdminGetConfig(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminGetConfigReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminGetConfigResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminUpdateConfig .
// @router /admin/config [PUT]
func AdminUpdateConfig(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminUpdateConfigReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminUpdateConfigResp)

	c.JSON(consts.StatusOK, resp)
}
