// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: http/chunk.proto

package chunk

import (
	_ "github.com/zy84338719/fileCodeBox/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkUploadInitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileHash      string                 `protobuf:"bytes,3,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	ChunkSize     int32                  `protobuf:"varint,4,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,5,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadInitReq) Reset() {
	*x = ChunkUploadInitReq{}
	mi := &file_http_chunk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadInitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadInitReq) ProtoMessage() {}

func (x *ChunkUploadInitReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_chunk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadInitReq.ProtoReflect.Descriptor instead.
func (*ChunkUploadInitReq) Descriptor() ([]byte, []int) {
	return file_http_chunk_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkUploadInitReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ChunkUploadInitReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ChunkUploadInitReq) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *ChunkUploadInitReq) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *ChunkUploadInitReq) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

type ChunkUploadInitResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ChunkUploadInitData   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadInitResp) Reset() {
	*x = ChunkUploadInitResp{}
	mi := &file_http_chunk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadInitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadInitResp) ProtoMessage() {}

func (x *ChunkUploadInitResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_chunk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadInitResp.ProtoReflect.Descriptor instead.
func (*ChunkUploadInitResp) Descriptor() ([]byte, []int) {
	return file_http_chunk_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkUploadInitResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChunkUploadInitResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChunkUploadInitResp) GetData() *ChunkUploadInitData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChunkUploadInitData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	ChunkSize     string                 `protobuf:"bytes,2,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	TotalChunks   string                 `protobuf:"bytes,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	IsQuickUpload bool                   `protobuf:"varint,4,opt,name=is_quick_upload,json=isQuickUpload,proto3" json:"is_quick_upload,omitempty"` // Quick upload flag
	ShareCode     string                 `protobuf:"bytes,5,opt,name=share_code,json=shareCode,proto3" json:"share_code,omitempty"`                // If quick upload, return share code directly
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadInitData) Reset() {
	*x = ChunkUploadInitData{}
	mi := &file_http_chunk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadInitData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadInitData) ProtoMessage() {}

func (x *ChunkUploadInitData) ProtoReflect() protoreflect.Message {
	mi := &file_http_chunk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadInitData.ProtoReflect.Descriptor instead.
func (*ChunkUploadInitData) Descriptor() ([]byte, []int) {
	return file_http_chunk_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkUploadInitData) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *ChunkUploadInitData) GetChunkSize() string {
	if x != nil {
		return x.ChunkSize
	}
	return ""
}

func (x *ChunkUploadInitData) GetTotalChunks() string {
	if x != nil {
		return x.TotalChunks
	}
	return ""
}

func (x *ChunkUploadInitData) GetIsQuickUpload() bool {
	if x != nil {
		return x.IsQuickUpload
	}
	return false
}

func (x *ChunkUploadInitData) GetShareCode() string {
	if x != nil {
		return x.ShareCode
	}
	return ""
}

type ChunkUploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"` // 分片数据通过 multipart/form-data 上传
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadReq) Reset() {
	*x = ChunkUploadReq{}
	mi := &file_http_chunk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadReq) ProtoMessage() {}

func (x *ChunkUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_chunk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadReq.ProtoReflect.Descriptor instead.
func (*ChunkUploadReq) Descriptor() ([]byte, []int) {
	return file_http_chunk_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkUploadReq) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *ChunkUploadReq) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type ChunkUploadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ChunkUploadData       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadResp) Reset() {
	*x = ChunkUploadResp{}
	mi := &file_http_chunk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadResp) ProtoMessage() {}

func (x *ChunkUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_chunk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadResp.ProtoReflect.Descriptor instead.
func (*ChunkUploadResp) Descriptor() ([]byte, []int) {
	return file_http_chunk_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkUploadResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChunkUploadResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChunkUploadResp) GetData() *ChunkUploadData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChunkUploadData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkIndex    int32                  `protobuf:"varint,1,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	ChunkHash     string                 `protobuf:"bytes,2,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadData) Reset() {
	*x = ChunkUploadData{}
	mi := &file_http_chunk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadData) ProtoMessage() {}

func (x *ChunkUploadData) ProtoReflect() protoreflect.Message {
	mi := &file_http_chunk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadData.ProtoReflect.Descriptor instead.
func (*ChunkUploadData) Descriptor() ([]byte, []int) {
	return file_http_chunk_proto_rawDescGZIP(), []int{5}
}

func (x *ChunkUploadData) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ChunkUploadData) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

type ChunkUploadStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadStatusReq) Reset() {
	*x = ChunkUploadStatusReq{}
	mi := &file_http_chunk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadStatusReq) ProtoMessage() {}

func (x *ChunkUploadStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_chunk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadStatusReq.ProtoReflect.Descriptor instead.
func (*ChunkUploadStatusReq) Descriptor() ([]byte, []int) {
	return file_http_chunk_proto_rawDescGZIP(), []int{6}
}

func (x *ChunkUploadStatusReq) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type ChunkUploadStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ChunkUploadStatusData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadStatusResp) Reset() {
	*x = ChunkUploadStatusResp{}
	mi := &file_http_chunk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadStatusResp) ProtoMessage() {}

func (x *ChunkUploadStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_chunk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadStatusResp.ProtoReflect.Descriptor instead.
func (*ChunkUploadStatusResp) Descriptor() ([]byte, []int) {
	return file_http_chunk_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkUploadStatusResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChunkUploadStatusResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChunkUploadStatusResp) GetData() *ChunkUploadStatusData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChunkUploadStatusData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UploadId        string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	TotalChunks     int32                  `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	UploadedChunks  int32                  `protobuf:"varint,3,opt,name=uploaded_chunks,json=uploadedChunks,proto3" json:"uploaded_chunks,omitempty"`
	UploadedIndexes []int32                `protobuf:"varint,4,rep,packed,name=uploaded_indexes,json=uploadedIndexes,proto3" json:"uploaded_indexes,omitempty"`
	Progress        int32                  `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"` // 百分比
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`      // uploading, completed, cancelled
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChunkUploadStatusData) Reset() {
	*x = ChunkUploadStatusData{}
	mi := &file_http_chunk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadStatusData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadStatusData) ProtoMessage() {}

func (x *ChunkUploadStatusData) ProtoReflect() protoreflect.Message {
	mi := &file_http_chunk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadStatusData.ProtoReflect.Descriptor instead.
func (*ChunkUploadStatusData) Descriptor() ([]byte, []int) {
	return file_http_chunk_proto_rawDescGZIP(), []int{8}
}

func (x *ChunkUploadStatusData) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *ChunkUploadStatusData) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *ChunkUploadStatusData) GetUploadedChunks() int32 {
	if x != nil {
		return x.UploadedChunks
	}
	return 0
}

func (x *ChunkUploadStatusData) GetUploadedIndexes() []int32 {
	if x != nil {
		return x.UploadedIndexes
	}
	return nil
}

func (x *ChunkUploadStatusData) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ChunkUploadStatusData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ChunkUploadCompleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	ExpireValue   int32                  `protobuf:"varint,2,opt,name=expire_value,json=expireValue,proto3" json:"expire_value,omitempty"`
	ExpireStyle   string                 `protobuf:"bytes,3,opt,name=expire_style,json=expireStyle,proto3" json:"expire_style,omitempty"`
	RequireAuth   bool                   `protobuf:"varint,4,opt,name=require_auth,json=requireAuth,proto3" json:"require_auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadCompleteReq) Reset() {
	*x = ChunkUploadCompleteReq{}
	mi := &file_http_chunk_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadCompleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadCompleteReq) ProtoMessage() {}

func (x *ChunkUploadCompleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_chunk_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadCompleteReq.ProtoReflect.Descriptor instead.
func (*ChunkUploadCompleteReq) Descriptor() ([]byte, []int) {
	return file_http_chunk_proto_rawDescGZIP(), []int{9}
}

func (x *ChunkUploadCompleteReq) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *ChunkUploadCompleteReq) GetExpireValue() int32 {
	if x != nil {
		return x.ExpireValue
	}
	return 0
}

func (x *ChunkUploadCompleteReq) GetExpireStyle() string {
	if x != nil {
		return x.ExpireStyle
	}
	return ""
}

func (x *ChunkUploadCompleteReq) GetRequireAuth() bool {
	if x != nil {
		return x.RequireAuth
	}
	return false
}

type ChunkUploadCompleteResp struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Code          int32                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ChunkUploadCompleteData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadCompleteResp) Reset() {
	*x = ChunkUploadCompleteResp{}
	mi := &file_http_chunk_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadCompleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadCompleteResp) ProtoMessage() {}

func (x *ChunkUploadCompleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_chunk_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadCompleteResp.ProtoReflect.Descriptor instead.
func (*ChunkUploadCompleteResp) Descriptor() ([]byte, []int) {
	return file_http_chunk_proto_rawDescGZIP(), []int{10}
}

func (x *ChunkUploadCompleteResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChunkUploadCompleteResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChunkUploadCompleteResp) GetData() *ChunkUploadCompleteData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChunkUploadCompleteData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareCode     string                 `protobuf:"bytes,1,opt,name=share_code,json=shareCode,proto3" json:"share_code,omitempty"`
	ShareUrl      string                 `protobuf:"bytes,2,opt,name=share_url,json=shareUrl,proto3" json:"share_url,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadCompleteData) Reset() {
	*x = ChunkUploadCompleteData{}
	mi := &file_http_chunk_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadCompleteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadCompleteData) ProtoMessage() {}

func (x *ChunkUploadCompleteData) ProtoReflect() protoreflect.Message {
	mi := &file_http_chunk_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadCompleteData.ProtoReflect.Descriptor instead.
func (*ChunkUploadCompleteData) Descriptor() ([]byte, []int) {
	return file_http_chunk_proto_rawDescGZIP(), []int{11}
}

func (x *ChunkUploadCompleteData) GetShareCode() string {
	if x != nil {
		return x.ShareCode
	}
	return ""
}

func (x *ChunkUploadCompleteData) GetShareUrl() string {
	if x != nil {
		return x.ShareUrl
	}
	return ""
}

func (x *ChunkUploadCompleteData) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ChunkUploadCompleteData) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type ChunkUploadCancelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadCancelReq) Reset() {
	*x = ChunkUploadCancelReq{}
	mi := &file_http_chunk_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadCancelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadCancelReq) ProtoMessage() {}

func (x *ChunkUploadCancelReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_chunk_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadCancelReq.ProtoReflect.Descriptor instead.
func (*ChunkUploadCancelReq) Descriptor() ([]byte, []int) {
	return file_http_chunk_proto_rawDescGZIP(), []int{12}
}

func (x *ChunkUploadCancelReq) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type ChunkUploadCancelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadCancelResp) Reset() {
	*x = ChunkUploadCancelResp{}
	mi := &file_http_chunk_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadCancelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadCancelResp) ProtoMessage() {}

func (x *ChunkUploadCancelResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_chunk_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadCancelResp.ProtoReflect.Descriptor instead.
func (*ChunkUploadCancelResp) Descriptor() ([]byte, []int) {
	return file_http_chunk_proto_rawDescGZIP(), []int{13}
}

func (x *ChunkUploadCancelResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChunkUploadCancelResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_http_chunk_proto protoreflect.FileDescriptor

const file_http_chunk_proto_rawDesc = "" +
	"\n" +
	"\x10http/chunk.proto\x12\n" +
	"http.chunk\x1a\rapi/api.proto\"\xfc\x01\n" +
	"\x12ChunkUploadInitReq\x12*\n" +
	"\tfile_name\x18\x01 \x01(\tB\rʻ\x18\tfile_nameR\bfileName\x12*\n" +
	"\tfile_size\x18\x02 \x01(\x03B\rʻ\x18\tfile_sizeR\bfileSize\x12*\n" +
	"\tfile_hash\x18\x03 \x01(\tB\rʻ\x18\tfile_hashR\bfileHash\x12-\n" +
	"\n" +
	"chunk_size\x18\x04 \x01(\x05B\x0eʻ\x18\n" +
	"chunk_sizeR\tchunkSize\x123\n" +
	"\ftotal_chunks\x18\x05 \x01(\x05B\x10ʻ\x18\ftotal_chunksR\vtotalChunks\"\x99\x01\n" +
	"\x13ChunkUploadInitResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x12=\n" +
	"\x04data\x18\x03 \x01(\v2\x1f.http.chunk.ChunkUploadInitDataB\bʻ\x18\x04dataR\x04data\"\x91\x02\n" +
	"\x13ChunkUploadInitData\x12*\n" +
	"\tupload_id\x18\x01 \x01(\tB\rʻ\x18\tupload_idR\buploadId\x12-\n" +
	"\n" +
	"chunk_size\x18\x02 \x01(\tB\x0eʻ\x18\n" +
	"chunk_sizeR\tchunkSize\x123\n" +
	"\ftotal_chunks\x18\x03 \x01(\tB\x10ʻ\x18\ftotal_chunksR\vtotalChunks\x12;\n" +
	"\x0fis_quick_upload\x18\x04 \x01(\bB\x13ʻ\x18\x0fis_quick_uploadR\risQuickUpload\x12-\n" +
	"\n" +
	"share_code\x18\x05 \x01(\tB\x0eʻ\x18\n" +
	"share_codeR\tshareCode\"n\n" +
	"\x0eChunkUploadReq\x12*\n" +
	"\tupload_id\x18\x01 \x01(\tB\rһ\x18\tupload_idR\buploadId\x120\n" +
	"\vchunk_index\x18\x02 \x01(\x05B\x0fһ\x18\vchunk_indexR\n" +
	"chunkIndex\"\x91\x01\n" +
	"\x0fChunkUploadResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x129\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.http.chunk.ChunkUploadDataB\bʻ\x18\x04dataR\x04data\"r\n" +
	"\x0fChunkUploadData\x120\n" +
	"\vchunk_index\x18\x01 \x01(\x05B\x0fʻ\x18\vchunk_indexR\n" +
	"chunkIndex\x12-\n" +
	"\n" +
	"chunk_hash\x18\x02 \x01(\tB\x0eʻ\x18\n" +
	"chunk_hashR\tchunkHash\"B\n" +
	"\x14ChunkUploadStatusReq\x12*\n" +
	"\tupload_id\x18\x01 \x01(\tB\rһ\x18\tupload_idR\buploadId\"\x9d\x01\n" +
	"\x15ChunkUploadStatusResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x12?\n" +
	"\x04data\x18\x03 \x01(\v2!.http.chunk.ChunkUploadStatusDataB\bʻ\x18\x04dataR\x04data\"\xc5\x02\n" +
	"\x15ChunkUploadStatusData\x12*\n" +
	"\tupload_id\x18\x01 \x01(\tB\rʻ\x18\tupload_idR\buploadId\x123\n" +
	"\ftotal_chunks\x18\x02 \x01(\x05B\x10ʻ\x18\ftotal_chunksR\vtotalChunks\x12<\n" +
	"\x0fuploaded_chunks\x18\x03 \x01(\x05B\x13ʻ\x18\x0fuploaded_chunksR\x0euploadedChunks\x12?\n" +
	"\x10uploaded_indexes\x18\x04 \x03(\x05B\x14ʻ\x18\x10uploaded_indexesR\x0fuploadedIndexes\x12(\n" +
	"\bprogress\x18\x05 \x01(\x05B\fʻ\x18\bprogressR\bprogress\x12\"\n" +
	"\x06status\x18\x06 \x01(\tB\n" +
	"ʻ\x18\x06statusR\x06status\"\xe3\x01\n" +
	"\x16ChunkUploadCompleteReq\x12*\n" +
	"\tupload_id\x18\x01 \x01(\tB\rһ\x18\tupload_idR\buploadId\x123\n" +
	"\fexpire_value\x18\x02 \x01(\x05B\x10ʻ\x18\fexpire_valueR\vexpireValue\x123\n" +
	"\fexpire_style\x18\x03 \x01(\tB\x10ʻ\x18\fexpire_styleR\vexpireStyle\x123\n" +
	"\frequire_auth\x18\x04 \x01(\bB\x10ʻ\x18\frequire_authR\vrequireAuth\"\xa1\x01\n" +
	"\x17ChunkUploadCompleteResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x12A\n" +
	"\x04data\x18\x03 \x01(\v2#.http.chunk.ChunkUploadCompleteDataB\bʻ\x18\x04dataR\x04data\"\xcc\x01\n" +
	"\x17ChunkUploadCompleteData\x12-\n" +
	"\n" +
	"share_code\x18\x01 \x01(\tB\x0eʻ\x18\n" +
	"share_codeR\tshareCode\x12*\n" +
	"\tshare_url\x18\x02 \x01(\tB\rʻ\x18\tshare_urlR\bshareUrl\x12*\n" +
	"\tfile_name\x18\x03 \x01(\tB\rʻ\x18\tfile_nameR\bfileName\x12*\n" +
	"\tfile_size\x18\x04 \x01(\x03B\rʻ\x18\tfile_sizeR\bfileSize\"B\n" +
	"\x14ChunkUploadCancelReq\x12*\n" +
	"\tupload_id\x18\x01 \x01(\tB\rһ\x18\tupload_idR\buploadId\"\\\n" +
	"\x15ChunkUploadCancelResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage2\xfa\x04\n" +
	"\fChunkService\x12k\n" +
	"\x0fChunkUploadInit\x12\x1e.http.chunk.ChunkUploadInitReq\x1a\x1f.http.chunk.ChunkUploadInitResp\"\x17\xd2\xc1\x18\x13/chunk/upload/init/\x12w\n" +
	"\vChunkUpload\x12\x1a.http.chunk.ChunkUploadReq\x1a\x1b.http.chunk.ChunkUploadResp\"/\xd2\xc1\x18+/chunk/upload/chunk/:upload_id/:chunk_index\x12}\n" +
	"\x11ChunkUploadStatus\x12 .http.chunk.ChunkUploadStatusReq\x1a!.http.chunk.ChunkUploadStatusResp\"#\xca\xc1\x18\x1f/chunk/upload/status/:upload_id\x12\x85\x01\n" +
	"\x13ChunkUploadComplete\x12\".http.chunk.ChunkUploadCompleteReq\x1a#.http.chunk.ChunkUploadCompleteResp\"%\xd2\xc1\x18!/chunk/upload/complete/:upload_id\x12}\n" +
	"\x11ChunkUploadCancel\x12 .http.chunk.ChunkUploadCancelReq\x1a!.http.chunk.ChunkUploadCancelResp\"#\xe2\xc1\x18\x1f/chunk/upload/cancel/:upload_idB3Z1github.com/zy84338719/fileCodeBox/biz/model/chunkb\x06proto3"

var (
	file_http_chunk_proto_rawDescOnce sync.Once
	file_http_chunk_proto_rawDescData []byte
)

func file_http_chunk_proto_rawDescGZIP() []byte {
	file_http_chunk_proto_rawDescOnce.Do(func() {
		file_http_chunk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_http_chunk_proto_rawDesc), len(file_http_chunk_proto_rawDesc)))
	})
	return file_http_chunk_proto_rawDescData
}

var file_http_chunk_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_http_chunk_proto_goTypes = []any{
	(*ChunkUploadInitReq)(nil),      // 0: http.chunk.ChunkUploadInitReq
	(*ChunkUploadInitResp)(nil),     // 1: http.chunk.ChunkUploadInitResp
	(*ChunkUploadInitData)(nil),     // 2: http.chunk.ChunkUploadInitData
	(*ChunkUploadReq)(nil),          // 3: http.chunk.ChunkUploadReq
	(*ChunkUploadResp)(nil),         // 4: http.chunk.ChunkUploadResp
	(*ChunkUploadData)(nil),         // 5: http.chunk.ChunkUploadData
	(*ChunkUploadStatusReq)(nil),    // 6: http.chunk.ChunkUploadStatusReq
	(*ChunkUploadStatusResp)(nil),   // 7: http.chunk.ChunkUploadStatusResp
	(*ChunkUploadStatusData)(nil),   // 8: http.chunk.ChunkUploadStatusData
	(*ChunkUploadCompleteReq)(nil),  // 9: http.chunk.ChunkUploadCompleteReq
	(*ChunkUploadCompleteResp)(nil), // 10: http.chunk.ChunkUploadCompleteResp
	(*ChunkUploadCompleteData)(nil), // 11: http.chunk.ChunkUploadCompleteData
	(*ChunkUploadCancelReq)(nil),    // 12: http.chunk.ChunkUploadCancelReq
	(*ChunkUploadCancelResp)(nil),   // 13: http.chunk.ChunkUploadCancelResp
}
var file_http_chunk_proto_depIdxs = []int32{
	2,  // 0: http.chunk.ChunkUploadInitResp.data:type_name -> http.chunk.ChunkUploadInitData
	5,  // 1: http.chunk.ChunkUploadResp.data:type_name -> http.chunk.ChunkUploadData
	8,  // 2: http.chunk.ChunkUploadStatusResp.data:type_name -> http.chunk.ChunkUploadStatusData
	11, // 3: http.chunk.ChunkUploadCompleteResp.data:type_name -> http.chunk.ChunkUploadCompleteData
	0,  // 4: http.chunk.ChunkService.ChunkUploadInit:input_type -> http.chunk.ChunkUploadInitReq
	3,  // 5: http.chunk.ChunkService.ChunkUpload:input_type -> http.chunk.ChunkUploadReq
	6,  // 6: http.chunk.ChunkService.ChunkUploadStatus:input_type -> http.chunk.ChunkUploadStatusReq
	9,  // 7: http.chunk.ChunkService.ChunkUploadComplete:input_type -> http.chunk.ChunkUploadCompleteReq
	12, // 8: http.chunk.ChunkService.ChunkUploadCancel:input_type -> http.chunk.ChunkUploadCancelReq
	1,  // 9: http.chunk.ChunkService.ChunkUploadInit:output_type -> http.chunk.ChunkUploadInitResp
	4,  // 10: http.chunk.ChunkService.ChunkUpload:output_type -> http.chunk.ChunkUploadResp
	7,  // 11: http.chunk.ChunkService.ChunkUploadStatus:output_type -> http.chunk.ChunkUploadStatusResp
	10, // 12: http.chunk.ChunkService.ChunkUploadComplete:output_type -> http.chunk.ChunkUploadCompleteResp
	13, // 13: http.chunk.ChunkService.ChunkUploadCancel:output_type -> http.chunk.ChunkUploadCancelResp
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_http_chunk_proto_init() }
func file_http_chunk_proto_init() {
	if File_http_chunk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_chunk_proto_rawDesc), len(file_http_chunk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_http_chunk_proto_goTypes,
		DependencyIndexes: file_http_chunk_proto_depIdxs,
		MessageInfos:      file_http_chunk_proto_msgTypes,
	}.Build()
	File_http_chunk_proto = out.File
	file_http_chunk_proto_goTypes = nil
	file_http_chunk_proto_depIdxs = nil
}
