// Code generated by hertz generator.

package admin

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	admin "github.com/zy84338719/fileCodeBox/biz/model/admin"
	adminsvc "github.com/zy84338719/fileCodeBox/internal/app/admin"
)

var adminService *adminsvc.Service

func init() {
	adminService = adminsvc.NewService()
}

// AdminLogin .
// @router /admin/login [POST]
func AdminLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminLoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &admin.AdminLoginResp{
			Code:    400,
			Message: "请求参数错误: " + err.Error(),
		})
		return
	}

	// 参数验证
	if req.Username == "" || req.Password == "" {
		c.JSON(consts.StatusBadRequest, &admin.AdminLoginResp{
			Code:    400,
			Message: "用户名和密码不能为空",
		})
		return
	}

	// 生成 token
	token, err := adminService.GenerateTokenForAdmin(ctx, req.Username, req.Password)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, &admin.AdminLoginResp{
			Code:    401,
			Message: err.Error(),
		})
		return
	}

	// 返回成功响应
	resp := &admin.AdminLoginResp{
		Code:    200,
		Message: "登录成功",
		Data: &admin.AdminLoginData{
			Token:     token,
			TokenType: "Bearer",
			ExpiresIn: 24 * 60 * 60, // 24小时
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// AdminStats .
// @router /admin/stats [GET]
func AdminStats(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminStatsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminStatsResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminListFiles .
// @router /admin/files [GET]
func AdminListFiles(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminListFilesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminListFilesResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminDeleteFile .
// @router /admin/files/:id [DELETE]
func AdminDeleteFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminDeleteFileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminDeleteFileResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminListUsers .
// @router /admin/users [GET]
func AdminListUsers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminListUsersReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminListUsersResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminUpdateUserStatus .
// @router /admin/users/:id/status [PUT]
func AdminUpdateUserStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminUpdateUserStatusReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminUpdateUserStatusResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminGetConfig .
// @router /admin/config [GET]
func AdminGetConfig(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminGetConfigReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminGetConfigResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminUpdateConfig .
// @router /admin/config [PUT]
func AdminUpdateConfig(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminUpdateConfigReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminUpdateConfigResp)

	c.JSON(consts.StatusOK, resp)
}

// CleanExpiredFiles 清理过期文件
// @router /admin/maintenance/clean-expired [POST]
func CleanExpiredFiles(ctx context.Context, c *app.RequestContext) {
	count, err := adminService.CleanupExpiredFiles(ctx)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "清理过期文件失败: " + err.Error(),
		})
		return
	}
	c.JSON(consts.StatusOK, map[string]interface{}{
		"code":    200,
		"message": "清理完成",
		"data": map[string]interface{}{
			"deleted_count": count,
		},
	})
}

// CleanTempFiles 清理临时文件
// @router /admin/maintenance/clean-temp [POST]
func CleanTempFiles(ctx context.Context, c *app.RequestContext) {
	count, err := adminService.CleanupIncompleteUploads(ctx, 24)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "清理临时文件失败: " + err.Error(),
		})
		return
	}
	c.JSON(consts.StatusOK, map[string]interface{}{
		"code":    200,
		"message": "清理完成",
		"data": map[string]interface{}{
			"deleted_count": count,
		},
	})
}

// GetSystemLogs 获取系统日志
// @router /admin/maintenance/logs [GET]
func GetSystemLogs(ctx context.Context, c *app.RequestContext) {
	logs := []map[string]interface{}{}
	c.JSON(consts.StatusOK, map[string]interface{}{
		"code": 200,
		"data": logs,
	})
}

// GetSystemInfo 获取系统信息
// @router /admin/maintenance/system-info [GET]
func GetSystemInfo(ctx context.Context, c *app.RequestContext) {
	info := map[string]interface{}{
		"go_version": "1.25",
		"os":         "linux",
		"arch":       "amd64",
	}
	c.JSON(consts.StatusOK, map[string]interface{}{
		"code": 200,
		"data": info,
	})
}

// GetStorageStatus 获取存储状态
// @router /admin/maintenance/monitor/storage [GET]
func GetStorageStatus(ctx context.Context, c *app.RequestContext) {
	status := map[string]interface{}{
		"type":       "local",
		"total_size": 0,
		"used_size":  0,
		"available":  true,
	}
	c.JSON(consts.StatusOK, map[string]interface{}{
		"code": 200,
		"data": status,
	})
}
