// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: http/qrcode.proto

package qrcode

import (
	_ "github.com/zy84338719/fileCodeBox/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateQRCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ReturnBase64  bool                   `protobuf:"varint,3,opt,name=return_base64,json=returnBase64,proto3" json:"return_base64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQRCodeReq) Reset() {
	*x = GenerateQRCodeReq{}
	mi := &file_http_qrcode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQRCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQRCodeReq) ProtoMessage() {}

func (x *GenerateQRCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_qrcode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQRCodeReq.ProtoReflect.Descriptor instead.
func (*GenerateQRCodeReq) Descriptor() ([]byte, []int) {
	return file_http_qrcode_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateQRCodeReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GenerateQRCodeReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GenerateQRCodeReq) GetReturnBase64() bool {
	if x != nil {
		return x.ReturnBase64
	}
	return false
}

type GenerateQRCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *QRCodeData            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQRCodeResp) Reset() {
	*x = GenerateQRCodeResp{}
	mi := &file_http_qrcode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQRCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQRCodeResp) ProtoMessage() {}

func (x *GenerateQRCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_qrcode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQRCodeResp.ProtoReflect.Descriptor instead.
func (*GenerateQRCodeResp) Descriptor() ([]byte, []int) {
	return file_http_qrcode_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateQRCodeResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GenerateQRCodeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenerateQRCodeResp) GetData() *QRCodeData {
	if x != nil {
		return x.Data
	}
	return nil
}

type QRCodeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Base64Data    string                 `protobuf:"bytes,5,opt,name=base64_data,json=base64Data,proto3" json:"base64_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QRCodeData) Reset() {
	*x = QRCodeData{}
	mi := &file_http_qrcode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QRCodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRCodeData) ProtoMessage() {}

func (x *QRCodeData) ProtoReflect() protoreflect.Message {
	mi := &file_http_qrcode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRCodeData.ProtoReflect.Descriptor instead.
func (*QRCodeData) Descriptor() ([]byte, []int) {
	return file_http_qrcode_proto_rawDescGZIP(), []int{2}
}

func (x *QRCodeData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QRCodeData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *QRCodeData) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *QRCodeData) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *QRCodeData) GetBase64Data() string {
	if x != nil {
		return x.Base64Data
	}
	return ""
}

type GetQRCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQRCodeReq) Reset() {
	*x = GetQRCodeReq{}
	mi := &file_http_qrcode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQRCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQRCodeReq) ProtoMessage() {}

func (x *GetQRCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_qrcode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQRCodeReq.ProtoReflect.Descriptor instead.
func (*GetQRCodeReq) Descriptor() ([]byte, []int) {
	return file_http_qrcode_proto_rawDescGZIP(), []int{3}
}

func (x *GetQRCodeReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_http_qrcode_proto protoreflect.FileDescriptor

const file_http_qrcode_proto_rawDesc = "" +
	"\n" +
	"\x11http/qrcode.proto\x12\vhttp.qrcode\x1a\rapi/api.proto\"\x87\x01\n" +
	"\x11GenerateQRCodeReq\x12\x1c\n" +
	"\x04data\x18\x01 \x01(\tB\bʻ\x18\x04dataR\x04data\x12\x1c\n" +
	"\x04size\x18\x02 \x01(\x05B\bʻ\x18\x04sizeR\x04size\x126\n" +
	"\rreturn_base64\x18\x03 \x01(\bB\x11ʻ\x18\rreturn_base64R\freturnBase64\"\x90\x01\n" +
	"\x12GenerateQRCodeResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x125\n" +
	"\x04data\x18\x03 \x01(\v2\x17.http.qrcode.QRCodeDataB\bʻ\x18\x04dataR\x04data\"\xbe\x01\n" +
	"\n" +
	"QRCodeData\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06ʻ\x18\x02idR\x02id\x12\x1c\n" +
	"\x04data\x18\x02 \x01(\tB\bʻ\x18\x04dataR\x04data\x12\x1c\n" +
	"\x04size\x18\x03 \x01(\x05B\bʻ\x18\x04sizeR\x04size\x12*\n" +
	"\timage_url\x18\x04 \x01(\tB\rʻ\x18\timage_urlR\bimageUrl\x120\n" +
	"\vbase64_data\x18\x05 \x01(\tB\x0fʻ\x18\vbase64_dataR\n" +
	"base64Data\"&\n" +
	"\fGetQRCodeReq\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06һ\x18\x02idR\x02id2\xcc\x01\n" +
	"\rQRCodeService\x12g\n" +
	"\x0eGenerateQRCode\x12\x1e.http.qrcode.GenerateQRCodeReq\x1a\x1f.http.qrcode.GenerateQRCodeResp\"\x14\xd2\xc1\x18\x10/qrcode/generate\x12R\n" +
	"\tGetQRCode\x12\x19.http.qrcode.GetQRCodeReq\x1a\x19.http.qrcode.GetQRCodeReq\"\x0f\xca\xc1\x18\v/qrcode/:idB4Z2github.com/zy84338719/fileCodeBox/biz/model/qrcodeb\x06proto3"

var (
	file_http_qrcode_proto_rawDescOnce sync.Once
	file_http_qrcode_proto_rawDescData []byte
)

func file_http_qrcode_proto_rawDescGZIP() []byte {
	file_http_qrcode_proto_rawDescOnce.Do(func() {
		file_http_qrcode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_http_qrcode_proto_rawDesc), len(file_http_qrcode_proto_rawDesc)))
	})
	return file_http_qrcode_proto_rawDescData
}

var file_http_qrcode_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_http_qrcode_proto_goTypes = []any{
	(*GenerateQRCodeReq)(nil),  // 0: http.qrcode.GenerateQRCodeReq
	(*GenerateQRCodeResp)(nil), // 1: http.qrcode.GenerateQRCodeResp
	(*QRCodeData)(nil),         // 2: http.qrcode.QRCodeData
	(*GetQRCodeReq)(nil),       // 3: http.qrcode.GetQRCodeReq
}
var file_http_qrcode_proto_depIdxs = []int32{
	2, // 0: http.qrcode.GenerateQRCodeResp.data:type_name -> http.qrcode.QRCodeData
	0, // 1: http.qrcode.QRCodeService.GenerateQRCode:input_type -> http.qrcode.GenerateQRCodeReq
	3, // 2: http.qrcode.QRCodeService.GetQRCode:input_type -> http.qrcode.GetQRCodeReq
	1, // 3: http.qrcode.QRCodeService.GenerateQRCode:output_type -> http.qrcode.GenerateQRCodeResp
	3, // 4: http.qrcode.QRCodeService.GetQRCode:output_type -> http.qrcode.GetQRCodeReq
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_http_qrcode_proto_init() }
func file_http_qrcode_proto_init() {
	if File_http_qrcode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_qrcode_proto_rawDesc), len(file_http_qrcode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_http_qrcode_proto_goTypes,
		DependencyIndexes: file_http_qrcode_proto_depIdxs,
		MessageInfos:      file_http_qrcode_proto_msgTypes,
	}.Build()
	File_http_qrcode_proto = out.File
	file_http_qrcode_proto_goTypes = nil
	file_http_qrcode_proto_depIdxs = nil
}
