// Code generated by hertz generator.

package main

import (
	"context"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/zy84338719/fileCodeBox/backend/gen/http/handler"
	customHandler "github.com/zy84338719/fileCodeBox/backend/internal/transport/http/handler"
	customMw "github.com/zy84338719/fileCodeBox/backend/internal/transport/http/middleware"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// ===== OpenAPI 文档（B7） =====
	r.GET("/openapi.json", customHandler.OpenAPISpec)

	// ===== 自定义：我的分享管理 API（不走 IDL） =====
	apiV1 := r.Group("/api/v1", customMw.UserAuth())
	{
		userShares := apiV1.Group("/user/shares", customMw.UserAuth())
		userShares.GET("", customHandler.ListUserShares)
		userShares.POST("/batch-delete", customHandler.BatchDeleteUserShares)
		userShares.POST("/batch-extend", customHandler.BatchExtendUserShares)
		userShares.POST("/:code/restore", customHandler.RestoreUserShare)
		userShares.DELETE("/:code/hard", customHandler.HardDeleteUserShare)

		// 通知（per-user）
		apiV1.GET("/notifies/mine", customMw.UserAuth(), customHandler.ListMyNotifications)
		apiV1.GET("/notifies/unread-count", customMw.UserAuth(), customHandler.UnreadNotifyCount)
		apiV1.POST("/notifies/mark-read", customMw.UserAuth(), customHandler.MarkNotifyRead)
	}

	// 服务前端静态文件
	r.Static("/static", "./static")
	r.StaticFile("/", "./static/index.html")
	r.NoRoute(func(ctx context.Context, c *app.RequestContext) {
		// 对于非API路由，返回index.html（支持SPA）
		if !strings.HasPrefix(string(c.Request.URI().Path()), "/api") &&
			!strings.HasPrefix(string(c.Request.URI().Path()), "/share") &&
			!strings.HasPrefix(string(c.Request.URI().Path()), "/user") &&
			!strings.HasPrefix(string(c.Request.URI().Path()), "/admin") &&
			!strings.HasPrefix(string(c.Request.URI().Path()), "/chunk") {
			c.File("./static/index.html")
		} else {
			c.Status(404)
			c.JSON(404, map[string]interface{}{
				"code":    404,
				"message": "API endpoint not found",
			})
		}
	})
}
