// Code generated by hertz generator.

package main

import (
	"context"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/zy84338719/fileCodeBox/backend/gen/http/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// 服务前端静态文件
	r.Static("/static", "./static")
	r.StaticFile("/", "./static/index.html")
	r.NoRoute(func(ctx context.Context, c *app.RequestContext) {
		// 对于非API路由，返回index.html（支持SPA）
		if !strings.HasPrefix(string(c.Request.URI().Path()), "/api") &&
			!strings.HasPrefix(string(c.Request.URI().Path()), "/share") &&
			!strings.HasPrefix(string(c.Request.URI().Path()), "/user") &&
			!strings.HasPrefix(string(c.Request.URI().Path()), "/admin") &&
			!strings.HasPrefix(string(c.Request.URI().Path()), "/chunk") {
			c.File("./static/index.html")
		} else {
			c.Status(404)
			c.JSON(404, map[string]interface{}{
				"code":    404,
				"message": "API endpoint not found",
			})
		}
	})
}
