#!/usr/bin/env bash
set -euo pipefail

############################################
# 基础配置
############################################

MODULE="github.com/zy84338719/fileCodeBox/backend"
IDL_DIR="idl"
HZ_OUT_DIR="."                        # hz --out_dir，相对于项目根（.hz 在此目录）
HANDLER_DIR="gen/http/handler"        # 相对于 HZ_OUT_DIR
MODEL_DIR="gen/http/model"            # 相对于 HZ_OUT_DIR
ROUTER_DIR="gen/http/router"          # 相对于 HZ_OUT_DIR
HZ_META_FILE=".hz"                    # .hz 位置（out_dir 根）
RPC_OUT_DIR="gen/rpc"

############################################
# 工具函数
############################################

log() {
  echo -e "\033[1;32m[INFO]\033[0m $1"
}

warn() {
  echo -e "\033[1;33m[WARN]\033[0m $1"
}

err() {
  echo -e "\033[1;31m[ERROR]\033[0m $1"
  exit 1
}

check_hz() {
  if ! command -v hz &> /dev/null; then
    err "hz 未安装，请执行：go install github.com/cloudwego/hertz/cmd/hz@latest"
  fi
}

check_thriftgo() {
  if ! command -v thriftgo &> /dev/null; then
    err "thriftgo 未安装，请执行：go install github.com/cloudwego/thriftgo/cmd/thriftgo@latest"
  fi
}

check_kitex() {
  if ! command -v kitex &> /dev/null; then
    err "kitex 未安装，请执行：go install github.com/cloudwego/kitex/tool/cmd/kitex@latest"
  fi
}

############################################
# 使用说明
############################################

usage() {
  echo "Usage:"
  echo "  ./scripts/gen.sh <command> [idl_file]"
  echo ""
  echo "Commands:"
  echo "  hz-new          初始化 Hz HTTP 项目（指定单个 IDL）"
  echo "  hz-update       更新 Hz HTTP 代码（指定单个 IDL，.hz 不存在时自动初始化）"
  echo "  hz-update-all   扫描所有 idl/*.proto 和 idl/http/*.proto 批量更新"
  echo "  hz-init         强制重新初始化 .hz 配置（备份 handler 后 hz new --force）"
  echo "  thrift-new      初始化 Hz HTTP 项目（指定单个 thrift IDL）"
  echo "  thrift-update   更新 Hz HTTP 代码（指定单个 thrift IDL）"
  echo "  thrift-update-all  扫描所有 idl/*.thrift 批量更新"
  echo "  kitex           生成 Kitex RPC 代码（指定单个 IDL）"
  echo ""
  echo "Examples:"
  echo "  ./scripts/gen.sh hz-new idl/common.proto"
  echo "  ./scripts/gen.sh hz-update idl/common.proto"
  echo "  ./scripts/gen.sh hz-update idl/http/health.proto"
  echo "  ./scripts/gen.sh hz-update-all"
  echo "  ./scripts/gen.sh hz-init idl/common.proto"
  echo "  ./scripts/gen.sh thrift-new idl/common.thrift"
  echo "  ./scripts/gen.sh thrift-update idl/http/health.thrift"
  echo "  ./scripts/gen.sh thrift-update-all"
  echo "  ./scripts/gen.sh kitex idl/rpc/user.proto"
  exit 1
}

############################################
# 参数解析
############################################

if [[ $# -lt 1 ]]; then
  usage
fi

ACTION=$1
IDL_FILE="${2:-}"

############################################
# 防止生成到 biz/
############################################

if [[ -d "biz" ]]; then
  err "检测到 biz/ 目录，请删除或迁移，避免生成到错误目录"
fi

############################################
# 核心函数：创建 .hz 元数据文件
############################################

_ensure_hz_meta() {
  if [[ ! -f "$HZ_META_FILE" ]]; then
    warn ".hz 配置文件不存在，自动创建..."
    printf '// Code generated by hz. DO NOT EDIT.\n\nhz version: v0.9.7\nhandlerDir: %s\nmodelDir: %s\nrouterDir: %s\n' \
      "$HANDLER_DIR" "$MODEL_DIR" "$ROUTER_DIR" > "$HZ_META_FILE"
    log ".hz 创建完成"
  fi
}

############################################
# 核心函数：构建 --exclude_file 参数列表
# 保护已存在的 handler 文件不被 hz 覆盖
############################################

_build_exclude_args() {
  local _varname=$1
  local _idx=0
  eval "$_varname=()"
  while IFS= read -r -d '' f; do
    eval "$_varname[$_idx]=\"-E\""
    _idx=$((_idx + 1))
    eval "$_varname[$_idx]=\"$f\""
    _idx=$((_idx + 1))
  done < <(find "$HANDLER_DIR" -name "*.go" -print0 2>/dev/null)
}

############################################
# 核心函数：判断是否需要 -I IDL_DIR
# IDL 文件在 idl/ 根目录时不加（避免 shadowing）
# IDL 文件在子目录时必须加（解析 import "api/api.proto"）
############################################

_build_proto_path_args() {
  local _varname=$1
  local idl_file=$2
  local idl_dir
  idl_dir="$(dirname "$idl_file")"
  local _idx=0
  eval "$_varname=()"
  # 如果 IDL 文件不在 IDL_DIR 根目录，需要添加 -I 让 protoc 找到依赖
  if [[ "$idl_dir" != "$IDL_DIR" ]]; then
    eval "$_varname[$_idx]=\"-I\""
    _idx=$((_idx + 1))
    eval "$_varname[$_idx]=\"$IDL_DIR\""
    _idx=$((_idx + 1))
  fi
}

############################################
# Hz HTTP 代码生成
############################################

gen_hz_new() {
  check_hz
  if [[ -z "$IDL_FILE" ]]; then
    err "hz-new 需要指定 IDL 文件，用法: ./scripts/gen.sh hz-new idl/common.proto"
  fi
  if [[ ! -f "$IDL_FILE" ]]; then
    err "IDL 文件不存在: $IDL_FILE"
  fi

  mkdir -p "$HANDLER_DIR" "$MODEL_DIR" "$ROUTER_DIR"

  local proto_path_args
  _build_proto_path_args proto_path_args "$IDL_FILE"

  log "执行 hz new: $IDL_FILE"
  hz new \
    --idl "$IDL_FILE" \
    --module "$MODULE" \
    --out_dir "$HZ_OUT_DIR" \
    --handler_dir "$HANDLER_DIR" \
    --model_dir "$MODEL_DIR" \
    --router_dir "$ROUTER_DIR" \
    "${proto_path_args[@]+"${proto_path_args[@]}"}"
  _fix_hz_meta
}

gen_hz_init() {
  check_hz
  if [[ -z "$IDL_FILE" ]]; then
    err "hz-init 需要指定 IDL 文件，用法: ./scripts/gen.sh hz-init idl/common.proto"
  fi
  if [[ ! -f "$IDL_FILE" ]]; then
    err "IDL 文件不存在: $IDL_FILE"
  fi

  mkdir -p "$HANDLER_DIR" "$MODEL_DIR" "$ROUTER_DIR"

  # 备份现有 handler 目录
  local handler_backup="/tmp/hz_handler_backup_$$"
  if [[ -d "$HANDLER_DIR" ]]; then
    cp -r "$HANDLER_DIR" "$handler_backup"
    log "已备份 ${HANDLER_DIR} -> ${handler_backup}"
  fi

  local proto_path_args
  _build_proto_path_args proto_path_args "$IDL_FILE"

  log "强制重新初始化 (hz new --force): $IDL_FILE"
  hz new \
    --idl "$IDL_FILE" \
    --module "$MODULE" \
    --out_dir "$HZ_OUT_DIR" \
    --handler_dir "$HANDLER_DIR" \
    --model_dir "$MODEL_DIR" \
    --router_dir "$ROUTER_DIR" \
    "${proto_path_args[@]+"${proto_path_args[@]}"}" \
    --force

  # 恢复 handler 目录
  if [[ -d "$handler_backup" ]]; then
    cp -r "$handler_backup/." "$HANDLER_DIR/"
    rm -rf "$handler_backup"
    log "已恢复 ${HANDLER_DIR}"
  fi

  _fix_hz_meta
}

# hz new 会重置 .hz 的 dirs，重新写入正确值
_fix_hz_meta() {
  printf '// Code generated by hz. DO NOT EDIT.\n\nhz version: v0.9.7\nhandlerDir: %s\nmodelDir: %s\nrouterDir: %s\n' \
    "$HANDLER_DIR" "$MODEL_DIR" "$ROUTER_DIR" > "$HZ_META_FILE"
  log ".hz 已更新为正确的目录配置"
}

gen_hz_update() {
  check_hz
  if [[ -z "$IDL_FILE" ]]; then
    err "hz-update 需要指定 IDL 文件，用法: ./scripts/gen.sh hz-update idl/common.proto"
  fi
  if [[ ! -f "$IDL_FILE" ]]; then
    err "IDL 文件不存在: $IDL_FILE"
  fi

  mkdir -p "$HANDLER_DIR" "$MODEL_DIR" "$ROUTER_DIR"

  # .hz 不存在时自动创建
  _ensure_hz_meta

  # 收集已存在的 handler 文件（保护自定义代码不被覆盖）
  local exclude_args
  _build_exclude_args exclude_args

  # 根据 IDL 文件位置决定是否需要 -I 参数
  local proto_path_args
  _build_proto_path_args proto_path_args "$IDL_FILE"

  log "执行 hz update: $IDL_FILE"
  hz update \
    --idl "$IDL_FILE" \
    --module "$MODULE" \
    --out_dir "$HZ_OUT_DIR" \
    --model_dir "$MODEL_DIR" \
    "${proto_path_args[@]+"${proto_path_args[@]}"}" \
    "${exclude_args[@]+"${exclude_args[@]}"}"
}

gen_hz_update_all() {
  check_hz
  mkdir -p "$HANDLER_DIR" "$MODEL_DIR" "$ROUTER_DIR"

  # 收集所有 HTTP IDL 文件：idl/*.proto + idl/http/*.proto
  local idl_files=()
  while IFS= read -r -d '' f; do
    idl_files+=("$f")
  done < <(find "$IDL_DIR" -maxdepth 1 -name "*.proto" -print0 2>/dev/null)
  while IFS= read -r -d '' f; do
    idl_files+=("$f")
  done < <(find "$IDL_DIR/http" -name "*.proto" -print0 2>/dev/null)

  if [[ ${#idl_files[@]} -eq 0 ]]; then
    err "未在 ${IDL_DIR} 或 ${IDL_DIR}/http 中找到任何 .proto 文件"
  fi

  log "共找到 ${#idl_files[@]} 个 IDL 文件，开始批量更新..."

  # 确保 .hz 存在（一次性）
  _ensure_hz_meta

  # 收集已存在的 handler 文件（所有 IDL 共用同一个 exclude 列表）
  local exclude_args
  _build_exclude_args exclude_args

  for f in "${idl_files[@]}"; do
    IDL_FILE="$f"
    log "-------------------------------------------"
    log "处理 IDL: $f"

    # 根据 IDL 文件位置决定是否需要 -I 参数
    local proto_path_args
    _build_proto_path_args proto_path_args "$IDL_FILE"

    log "执行 hz update: $IDL_FILE"
    hz update \
      --idl "$IDL_FILE" \
      --module "$MODULE" \
      --out_dir "$HZ_OUT_DIR" \
      --model_dir "$MODEL_DIR" \
      "${proto_path_args[@]+"${proto_path_args[@]}"}" \
      "${exclude_args[@]+"${exclude_args[@]}"}"
  done

  log "==========================================="
  log "批量更新完成，共处理 ${#idl_files[@]} 个 IDL 文件"
}

############################################
# Kitex RPC 代码生成
############################################

gen_kitex() {
  check_kitex
  if [[ -z "$IDL_FILE" ]]; then
    err "kitex 需要指定 IDL 文件，用法: ./scripts/gen.sh kitex idl/rpc/user.proto"
  fi
  if [[ ! -f "$IDL_FILE" ]]; then
    err "IDL 文件不存在: $IDL_FILE"
  fi

  mkdir -p "$RPC_OUT_DIR"
  log "执行 kitex 生成 RPC 代码: $IDL_FILE"
  kitex \
    -module "$MODULE" \
    -gen-path "$RPC_OUT_DIR" \
    -I "$IDL_DIR" \
    "$IDL_FILE"
}

############################################
# Thrift IDL 代码生成（与 proto 共用同一 gen/http/ 输出目录）
############################################

# 校验 IDL 是 thrift
_check_thrift() {
  case "$IDL_FILE" in
    *.thrift) ;;
    *) err "thrift 命令要求 .thrift 文件: $IDL_FILE" ;;
  esac
}

# thrift 包含路径：thrift 用 include 关键字解析，不需要 -I 参数
# 简单实现：thrift IDL 应在 idl/ 根或 idl/http/ 子目录，thriftgo 会自动找
_build_thrift_include_args() {
  local _varname=$1
  eval "$_varname=()"
  # thrift include path：idl/ 根目录，让 hz 找到 api.thrift 等
  eval "$_varname[0]=\"-I\""
  eval "$_varname[1]=\"$IDL_DIR\""
}

gen_thrift_new() {
  check_hz
  check_thriftgo
  _check_thrift
  if [[ -z "$IDL_FILE" ]]; then
    err "thrift-new 需要指定 IDL 文件，用法: ./scripts/gen.sh thrift-new idl/common.thrift"
  fi
  if [[ ! -f "$IDL_FILE" ]]; then
    err "IDL 文件不存在: $IDL_FILE"
  fi

  mkdir -p "$HANDLER_DIR" "$MODEL_DIR" "$ROUTER_DIR"

  local thrift_args
  _build_thrift_include_args thrift_args

  log "执行 hz new (thrift): $IDL_FILE"
  hz new \
    --idl "$IDL_FILE" \
    --module "$MODULE" \
    --out_dir "$HZ_OUT_DIR" \
    --handler_dir "$HANDLER_DIR" \
    --model_dir "$MODEL_DIR" \
    --router_dir "$ROUTER_DIR" \
    "${thrift_args[@]+"${thrift_args[@]}"}"
  _fix_hz_meta
}

gen_thrift_update() {
  check_hz
  check_thriftgo
  _check_thrift
  if [[ -z "$IDL_FILE" ]]; then
    err "thrift-update 需要指定 IDL 文件，用法: ./scripts/gen.sh thrift-update idl/common.thrift"
  fi
  if [[ ! -f "$IDL_FILE" ]]; then
    err "IDL 文件不存在: $IDL_FILE"
  fi

  mkdir -p "$HANDLER_DIR" "$MODEL_DIR" "$ROUTER_DIR"

  _ensure_hz_meta

  local exclude_args
  _build_exclude_args exclude_args

  local thrift_args
  _build_thrift_include_args thrift_args

  log "执行 hz update (thrift): $IDL_FILE"
  hz update \
    --idl "$IDL_FILE" \
    --module "$MODULE" \
    --out_dir "$HZ_OUT_DIR" \
    --model_dir "$MODEL_DIR" \
    "${thrift_args[@]+"${thrift_args[@]}"}" \
    "${exclude_args[@]+"${exclude_args[@]}"}"
}

gen_thrift_update_all() {
  check_hz
  check_thriftgo
  mkdir -p "$HANDLER_DIR" "$MODEL_DIR" "$ROUTER_DIR"

  # 收集所有 HTTP IDL 文件：idl/*.thrift + idl/http/*.thrift
  local idl_files=()
  while IFS= read -r -d '' f; do
    idl_files+=("$f")
  done < <(find "$IDL_DIR" -maxdepth 1 -name "*.thrift" -print0 2>/dev/null)
  while IFS= read -r -d '' f; do
    idl_files+=("$f")
  done < <(find "$IDL_DIR/http" -name "*.thrift" -print0 2>/dev/null)

  if [[ ${#idl_files[@]} -eq 0 ]]; then
    err "未在 ${IDL_DIR} 或 ${IDL_DIR}/http 中找到任何 .thrift 文件"
  fi

  # 过滤：跳过没有 service 定义的 IDL（纯 struct/文档）
  # 不带 service 的 IDL 不应该生成 handler/router 桩
  local real_idl_files=()
  local skipped=()
  for f in "${idl_files[@]}"; do
    if grep -qE '^[[:space:]]*service[[:space:]]+[A-Za-z_][A-Za-z0-9_]*[[:space:]]*\{' "$f"; then
      real_idl_files+=("$f")
    else
      skipped+=("$f")
    fi
  done

  if [[ ${#skipped[@]} -gt 0 ]]; then
    warn "跳过非服务 IDL（无 service 定义，仅为 struct/文档）:"
    for s in "${skipped[@]}"; do
      warn "  - $s"
    done
  fi

  log "共找到 ${#real_idl_files[@]} 个有效 thrift IDL 文件（service 定义），开始批量更新..."

  _ensure_hz_meta

  local exclude_args
  _build_exclude_args exclude_args

  for f in "${real_idl_files[@]}"; do
    IDL_FILE="$f"
    log "-------------------------------------------"
    log "处理 thrift IDL: $f"

    local thrift_args
    _build_thrift_include_args thrift_args

    log "执行 hz update (thrift): $f"
    hz update \
      --idl "$f" \
      --module "$MODULE" \
      --out_dir "$HZ_OUT_DIR" \
      --model_dir "$MODEL_DIR" \
      "${thrift_args[@]+"${thrift_args[@]}"}" \
      "${exclude_args[@]+"${exclude_args[@]}"}"
  done

  log "==========================================="
  log "批量更新完成，共处理 ${#real_idl_files[@]} 个 thrift IDL 文件"
}

############################################
# 执行生成
############################################

case "$ACTION" in
  hz-new)
    gen_hz_new
    ;;
  hz-update)
    gen_hz_update
    ;;
  hz-update-all)
    gen_hz_update_all
    ;;
  hz-init)
    gen_hz_init
    ;;
  thrift-new)
    gen_thrift_new
    ;;
  thrift-update)
    gen_thrift_update
    ;;
  thrift-update-all)
    gen_thrift_update_all
    ;;
  kitex)
    gen_kitex
    ;;
  # 兼容旧命令
  new)
    gen_hz_new
    ;;
  update)
    gen_hz_update
    ;;
  *)
    err "未知命令: $ACTION"
    ;;
esac

############################################
# 自动整理
############################################

log "执行 go mod tidy..."
if [[ "${SKIP_TIDY:-0}" != "1" ]]; then
  go mod tidy
else
  warn "跳过 go mod tidy (SKIP_TIDY=1)"
fi

log "执行 go fmt..."
if [[ "${SKIP_FMT:-0}" != "1" ]]; then
  go fmt ./...
else
  warn "跳过 go fmt (SKIP_FMT=1)"
fi

log "生成完成 ✅"
