// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: http/admin.proto

package admin

import (
	_ "github.com/zy84338719/fileCodeBox/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginReq) Reset() {
	*x = AdminLoginReq{}
	mi := &file_http_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginReq) ProtoMessage() {}

func (x *AdminLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginReq.ProtoReflect.Descriptor instead.
func (*AdminLoginReq) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminLoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *AdminLoginData        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginResp) Reset() {
	*x = AdminLoginResp{}
	mi := &file_http_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginResp) ProtoMessage() {}

func (x *AdminLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginResp.ProtoReflect.Descriptor instead.
func (*AdminLoginResp) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminLoginResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminLoginResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminLoginResp) GetData() *AdminLoginData {
	if x != nil {
		return x.Data
	}
	return nil
}

type AdminLoginData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginData) Reset() {
	*x = AdminLoginData{}
	mi := &file_http_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginData) ProtoMessage() {}

func (x *AdminLoginData) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginData.ProtoReflect.Descriptor instead.
func (*AdminLoginData) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminLoginData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdminLoginData) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *AdminLoginData) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type AdminStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminStatsReq) Reset() {
	*x = AdminStatsReq{}
	mi := &file_http_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStatsReq) ProtoMessage() {}

func (x *AdminStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStatsReq.ProtoReflect.Descriptor instead.
func (*AdminStatsReq) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{3}
}

type AdminStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *AdminStatsData        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminStatsResp) Reset() {
	*x = AdminStatsResp{}
	mi := &file_http_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStatsResp) ProtoMessage() {}

func (x *AdminStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStatsResp.ProtoReflect.Descriptor instead.
func (*AdminStatsResp) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AdminStatsResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminStatsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminStatsResp) GetData() *AdminStatsData {
	if x != nil {
		return x.Data
	}
	return nil
}

type AdminStatsData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalFiles     int64                  `protobuf:"varint,1,opt,name=total_files,json=totalFiles,proto3" json:"total_files,omitempty"`
	TotalUsers     int64                  `protobuf:"varint,2,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	TotalSize      int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	TodayUploads   int64                  `protobuf:"varint,4,opt,name=today_uploads,json=todayUploads,proto3" json:"today_uploads,omitempty"`
	TodayDownloads int64                  `protobuf:"varint,5,opt,name=today_downloads,json=todayDownloads,proto3" json:"today_downloads,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminStatsData) Reset() {
	*x = AdminStatsData{}
	mi := &file_http_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStatsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStatsData) ProtoMessage() {}

func (x *AdminStatsData) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStatsData.ProtoReflect.Descriptor instead.
func (*AdminStatsData) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{5}
}

func (x *AdminStatsData) GetTotalFiles() int64 {
	if x != nil {
		return x.TotalFiles
	}
	return 0
}

func (x *AdminStatsData) GetTotalUsers() int64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *AdminStatsData) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *AdminStatsData) GetTodayUploads() int64 {
	if x != nil {
		return x.TodayUploads
	}
	return 0
}

func (x *AdminStatsData) GetTodayDownloads() int64 {
	if x != nil {
		return x.TodayDownloads
	}
	return 0
}

type AdminListFilesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	SortBy        string                 `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListFilesReq) Reset() {
	*x = AdminListFilesReq{}
	mi := &file_http_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListFilesReq) ProtoMessage() {}

func (x *AdminListFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListFilesReq.ProtoReflect.Descriptor instead.
func (*AdminListFilesReq) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{6}
}

func (x *AdminListFilesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminListFilesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AdminListFilesReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *AdminListFilesReq) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type AdminListFilesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *AdminFileList         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListFilesResp) Reset() {
	*x = AdminListFilesResp{}
	mi := &file_http_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListFilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListFilesResp) ProtoMessage() {}

func (x *AdminListFilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListFilesResp.ProtoReflect.Descriptor instead.
func (*AdminListFilesResp) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{7}
}

func (x *AdminListFilesResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminListFilesResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminListFilesResp) GetData() *AdminFileList {
	if x != nil {
		return x.Data
	}
	return nil
}

type AdminFileList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FileItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFileList) Reset() {
	*x = AdminFileList{}
	mi := &file_http_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFileList) ProtoMessage() {}

func (x *AdminFileList) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFileList.ProtoReflect.Descriptor instead.
func (*AdminFileList) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{8}
}

func (x *AdminFileList) GetItems() []*FileItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AdminFileList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AdminFileList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminFileList) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FileItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,5,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	ViewCount     int32                  `protobuf:"varint,6,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	DownloadCount int32                  `protobuf:"varint,7,opt,name=download_count,json=downloadCount,proto3" json:"download_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileItem) Reset() {
	*x = FileItem{}
	mi := &file_http_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileItem) ProtoMessage() {}

func (x *FileItem) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileItem.ProtoReflect.Descriptor instead.
func (*FileItem) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{9}
}

func (x *FileItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FileItem) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileItem) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileItem) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

func (x *FileItem) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *FileItem) GetDownloadCount() int32 {
	if x != nil {
		return x.DownloadCount
	}
	return 0
}

func (x *FileItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AdminDeleteFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteFileReq) Reset() {
	*x = AdminDeleteFileReq{}
	mi := &file_http_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteFileReq) ProtoMessage() {}

func (x *AdminDeleteFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteFileReq.ProtoReflect.Descriptor instead.
func (*AdminDeleteFileReq) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{10}
}

func (x *AdminDeleteFileReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminDeleteFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteFileResp) Reset() {
	*x = AdminDeleteFileResp{}
	mi := &file_http_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteFileResp) ProtoMessage() {}

func (x *AdminDeleteFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteFileResp.ProtoReflect.Descriptor instead.
func (*AdminDeleteFileResp) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{11}
}

func (x *AdminDeleteFileResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminDeleteFileResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AdminListUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListUsersReq) Reset() {
	*x = AdminListUsersReq{}
	mi := &file_http_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListUsersReq) ProtoMessage() {}

func (x *AdminListUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListUsersReq.ProtoReflect.Descriptor instead.
func (*AdminListUsersReq) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{12}
}

func (x *AdminListUsersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminListUsersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AdminListUsersReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *AdminListUsersReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AdminListUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *AdminUserList         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListUsersResp) Reset() {
	*x = AdminListUsersResp{}
	mi := &file_http_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListUsersResp) ProtoMessage() {}

func (x *AdminListUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListUsersResp.ProtoReflect.Descriptor instead.
func (*AdminListUsersResp) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{13}
}

func (x *AdminListUsersResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminListUsersResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminListUsersResp) GetData() *AdminUserList {
	if x != nil {
		return x.Data
	}
	return nil
}

type AdminUserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserList) Reset() {
	*x = AdminUserList{}
	mi := &file_http_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserList) ProtoMessage() {}

func (x *AdminUserList) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserList.ProtoReflect.Descriptor instead.
func (*AdminUserList) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{14}
}

func (x *AdminUserList) GetItems() []*UserItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AdminUserList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AdminUserList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminUserList) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	QuotaUsed     int64                  `protobuf:"varint,6,opt,name=quota_used,json=quotaUsed,proto3" json:"quota_used,omitempty"`
	QuotaLimit    int64                  `protobuf:"varint,7,opt,name=quota_limit,json=quotaLimit,proto3" json:"quota_limit,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserItem) Reset() {
	*x = UserItem{}
	mi := &file_http_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserItem) ProtoMessage() {}

func (x *UserItem) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserItem.ProtoReflect.Descriptor instead.
func (*UserItem) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{15}
}

func (x *UserItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserItem) GetQuotaUsed() int64 {
	if x != nil {
		return x.QuotaUsed
	}
	return 0
}

func (x *UserItem) GetQuotaLimit() int64 {
	if x != nil {
		return x.QuotaLimit
	}
	return 0
}

func (x *UserItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AdminUpdateUserStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateUserStatusReq) Reset() {
	*x = AdminUpdateUserStatusReq{}
	mi := &file_http_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateUserStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateUserStatusReq) ProtoMessage() {}

func (x *AdminUpdateUserStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateUserStatusReq.ProtoReflect.Descriptor instead.
func (*AdminUpdateUserStatusReq) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{16}
}

func (x *AdminUpdateUserStatusReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUpdateUserStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AdminUpdateUserStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateUserStatusResp) Reset() {
	*x = AdminUpdateUserStatusResp{}
	mi := &file_http_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateUserStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateUserStatusResp) ProtoMessage() {}

func (x *AdminUpdateUserStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateUserStatusResp.ProtoReflect.Descriptor instead.
func (*AdminUpdateUserStatusResp) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{17}
}

func (x *AdminUpdateUserStatusResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminUpdateUserStatusResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AdminGetConfigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetConfigReq) Reset() {
	*x = AdminGetConfigReq{}
	mi := &file_http_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetConfigReq) ProtoMessage() {}

func (x *AdminGetConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetConfigReq.ProtoReflect.Descriptor instead.
func (*AdminGetConfigReq) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{18}
}

type AdminGetConfigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ConfigData            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetConfigResp) Reset() {
	*x = AdminGetConfigResp{}
	mi := &file_http_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetConfigResp) ProtoMessage() {}

func (x *AdminGetConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetConfigResp.ProtoReflect.Descriptor instead.
func (*AdminGetConfigResp) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{19}
}

func (x *AdminGetConfigResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminGetConfigResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminGetConfigResp) GetData() *ConfigData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ConfigData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseConfig            `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Storage       *StorageConfig         `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage,omitempty"`
	Transfer      *TransferConfig        `protobuf:"bytes,3,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigData) Reset() {
	*x = ConfigData{}
	mi := &file_http_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigData) ProtoMessage() {}

func (x *ConfigData) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigData.ProtoReflect.Descriptor instead.
func (*ConfigData) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{20}
}

func (x *ConfigData) GetBase() *BaseConfig {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ConfigData) GetStorage() *StorageConfig {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *ConfigData) GetTransfer() *TransferConfig {
	if x != nil {
		return x.Transfer
	}
	return nil
}

type BaseConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseConfig) Reset() {
	*x = BaseConfig{}
	mi := &file_http_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseConfig) ProtoMessage() {}

func (x *BaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseConfig.ProtoReflect.Descriptor instead.
func (*BaseConfig) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{21}
}

func (x *BaseConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BaseConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type StorageConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	MaxSize       int64                  `protobuf:"varint,2,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageConfig) Reset() {
	*x = StorageConfig{}
	mi := &file_http_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageConfig) ProtoMessage() {}

func (x *StorageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageConfig.ProtoReflect.Descriptor instead.
func (*StorageConfig) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{22}
}

func (x *StorageConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StorageConfig) GetMaxSize() int64 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

type TransferConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxCount      int32                  `protobuf:"varint,1,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	ExpireDefault int32                  `protobuf:"varint,2,opt,name=expire_default,json=expireDefault,proto3" json:"expire_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferConfig) Reset() {
	*x = TransferConfig{}
	mi := &file_http_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferConfig) ProtoMessage() {}

func (x *TransferConfig) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferConfig.ProtoReflect.Descriptor instead.
func (*TransferConfig) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{23}
}

func (x *TransferConfig) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *TransferConfig) GetExpireDefault() int32 {
	if x != nil {
		return x.ExpireDefault
	}
	return 0
}

type AdminUpdateConfigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ConfigData            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateConfigReq) Reset() {
	*x = AdminUpdateConfigReq{}
	mi := &file_http_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateConfigReq) ProtoMessage() {}

func (x *AdminUpdateConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateConfigReq.ProtoReflect.Descriptor instead.
func (*AdminUpdateConfigReq) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{24}
}

func (x *AdminUpdateConfigReq) GetConfig() *ConfigData {
	if x != nil {
		return x.Config
	}
	return nil
}

type AdminUpdateConfigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateConfigResp) Reset() {
	*x = AdminUpdateConfigResp{}
	mi := &file_http_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateConfigResp) ProtoMessage() {}

func (x *AdminUpdateConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateConfigResp.ProtoReflect.Descriptor instead.
func (*AdminUpdateConfigResp) Descriptor() ([]byte, []int) {
	return file_http_admin_proto_rawDescGZIP(), []int{25}
}

func (x *AdminUpdateConfigResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminUpdateConfigResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_http_admin_proto protoreflect.FileDescriptor

const file_http_admin_proto_rawDesc = "" +
	"\n" +
	"\x10http/admin.proto\x12\n" +
	"http.admin\x1a\rapi/api.proto\"c\n" +
	"\rAdminLoginReq\x12(\n" +
	"\busername\x18\x01 \x01(\tB\fʻ\x18\busernameR\busername\x12(\n" +
	"\bpassword\x18\x02 \x01(\tB\fʻ\x18\bpasswordR\bpassword\"\x8f\x01\n" +
	"\x0eAdminLoginResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x128\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.http.admin.AdminLoginDataB\bʻ\x18\x04dataR\x04data\"\x8f\x01\n" +
	"\x0eAdminLoginData\x12\x1f\n" +
	"\x05token\x18\x01 \x01(\tB\tʻ\x18\x05tokenR\x05token\x12-\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tB\x0eʻ\x18\n" +
	"token_typeR\ttokenType\x12-\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03B\x0eʻ\x18\n" +
	"expires_inR\texpiresIn\"\x0f\n" +
	"\rAdminStatsReq\"\x8f\x01\n" +
	"\x0eAdminStatsResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x128\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.http.admin.AdminStatsDataB\bʻ\x18\x04dataR\x04data\"\x99\x02\n" +
	"\x0eAdminStatsData\x120\n" +
	"\vtotal_files\x18\x01 \x01(\x03B\x0fʻ\x18\vtotal_filesR\n" +
	"totalFiles\x120\n" +
	"\vtotal_users\x18\x02 \x01(\x03B\x0fʻ\x18\vtotal_usersR\n" +
	"totalUsers\x12-\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03B\x0eʻ\x18\n" +
	"total_sizeR\ttotalSize\x126\n" +
	"\rtoday_uploads\x18\x04 \x01(\x03B\x11ʻ\x18\rtoday_uploadsR\ftodayUploads\x12<\n" +
	"\x0ftoday_downloads\x18\x05 \x01(\x03B\x13ʻ\x18\x0ftoday_downloadsR\x0etodayDownloads\"\xaa\x01\n" +
	"\x11AdminListFilesReq\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\x05B\b\xb2\xbb\x18\x04pageR\x04page\x12*\n" +
	"\tpage_size\x18\x02 \x01(\x05B\r\xb2\xbb\x18\tpage_sizeR\bpageSize\x12%\n" +
	"\akeyword\x18\x03 \x01(\tB\v\xb2\xbb\x18\akeywordR\akeyword\x12$\n" +
	"\asort_by\x18\x04 \x01(\tB\v\xb2\xbb\x18\asort_byR\x06sortBy\"\x92\x01\n" +
	"\x12AdminListFilesResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x127\n" +
	"\x04data\x18\x03 \x01(\v2\x19.http.admin.AdminFileListB\bʻ\x18\x04dataR\x04data\"\xb1\x01\n" +
	"\rAdminFileList\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x14.http.admin.FileItemB\tʻ\x18\x05itemsR\x05items\x12\x1f\n" +
	"\x05total\x18\x02 \x01(\x03B\tʻ\x18\x05totalR\x05total\x12\x1c\n" +
	"\x04page\x18\x03 \x01(\x05B\bʻ\x18\x04pageR\x04page\x12*\n" +
	"\tpage_size\x18\x04 \x01(\x05B\rʻ\x18\tpage_sizeR\bpageSize\"\xe3\x02\n" +
	"\bFileItem\x12\x16\n" +
	"\x02id\x18\x01 \x01(\rB\x06ʻ\x18\x02idR\x02id\x12\x1c\n" +
	"\x04code\x18\x02 \x01(\tB\bʻ\x18\x04codeR\x04code\x12*\n" +
	"\tfile_name\x18\x03 \x01(\tB\rʻ\x18\tfile_nameR\bfileName\x12*\n" +
	"\tfile_size\x18\x04 \x01(\x03B\rʻ\x18\tfile_sizeR\bfileSize\x120\n" +
	"\vexpire_time\x18\x05 \x01(\tB\x0fʻ\x18\vexpire_timeR\n" +
	"expireTime\x12-\n" +
	"\n" +
	"view_count\x18\x06 \x01(\x05B\x0eʻ\x18\n" +
	"view_countR\tviewCount\x129\n" +
	"\x0edownload_count\x18\a \x01(\x05B\x12ʻ\x18\x0edownload_countR\rdownloadCount\x12-\n" +
	"\n" +
	"created_at\x18\b \x01(\tB\x0eʻ\x18\n" +
	"created_atR\tcreatedAt\",\n" +
	"\x12AdminDeleteFileReq\x12\x16\n" +
	"\x02id\x18\x01 \x01(\rB\x06һ\x18\x02idR\x02id\"Z\n" +
	"\x13AdminDeleteFileResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\"\xa8\x01\n" +
	"\x11AdminListUsersReq\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\x05B\b\xb2\xbb\x18\x04pageR\x04page\x12*\n" +
	"\tpage_size\x18\x02 \x01(\x05B\r\xb2\xbb\x18\tpage_sizeR\bpageSize\x12%\n" +
	"\akeyword\x18\x03 \x01(\tB\v\xb2\xbb\x18\akeywordR\akeyword\x12\"\n" +
	"\x06status\x18\x04 \x01(\x05B\n" +
	"\xb2\xbb\x18\x06statusR\x06status\"\x92\x01\n" +
	"\x12AdminListUsersResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x127\n" +
	"\x04data\x18\x03 \x01(\v2\x19.http.admin.AdminUserListB\bʻ\x18\x04dataR\x04data\"\xb1\x01\n" +
	"\rAdminUserList\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x14.http.admin.UserItemB\tʻ\x18\x05itemsR\x05items\x12\x1f\n" +
	"\x05total\x18\x02 \x01(\x03B\tʻ\x18\x05totalR\x05total\x12\x1c\n" +
	"\x04page\x18\x03 \x01(\x05B\bʻ\x18\x04pageR\x04page\x12*\n" +
	"\tpage_size\x18\x04 \x01(\x05B\rʻ\x18\tpage_sizeR\bpageSize\"\xcb\x02\n" +
	"\bUserItem\x12\x16\n" +
	"\x02id\x18\x01 \x01(\rB\x06ʻ\x18\x02idR\x02id\x12(\n" +
	"\busername\x18\x02 \x01(\tB\fʻ\x18\busernameR\busername\x12\x1f\n" +
	"\x05email\x18\x03 \x01(\tB\tʻ\x18\x05emailR\x05email\x12(\n" +
	"\bnickname\x18\x04 \x01(\tB\fʻ\x18\bnicknameR\bnickname\x12\"\n" +
	"\x06status\x18\x05 \x01(\x05B\n" +
	"ʻ\x18\x06statusR\x06status\x12-\n" +
	"\n" +
	"quota_used\x18\x06 \x01(\x03B\x0eʻ\x18\n" +
	"quota_usedR\tquotaUsed\x120\n" +
	"\vquota_limit\x18\a \x01(\x03B\x0fʻ\x18\vquota_limitR\n" +
	"quotaLimit\x12-\n" +
	"\n" +
	"created_at\x18\b \x01(\tB\x0eʻ\x18\n" +
	"created_atR\tcreatedAt\"V\n" +
	"\x18AdminUpdateUserStatusReq\x12\x16\n" +
	"\x02id\x18\x01 \x01(\rB\x06һ\x18\x02idR\x02id\x12\"\n" +
	"\x06status\x18\x02 \x01(\x05B\n" +
	"ʻ\x18\x06statusR\x06status\"`\n" +
	"\x19AdminUpdateUserStatusResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\"\x13\n" +
	"\x11AdminGetConfigReq\"\x8f\x01\n" +
	"\x12AdminGetConfigResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x124\n" +
	"\x04data\x18\x03 \x01(\v2\x16.http.admin.ConfigDataB\bʻ\x18\x04dataR\x04data\"\xca\x01\n" +
	"\n" +
	"ConfigData\x124\n" +
	"\x04base\x18\x01 \x01(\v2\x16.http.admin.BaseConfigB\bʻ\x18\x04baseR\x04base\x12@\n" +
	"\astorage\x18\x02 \x01(\v2\x19.http.admin.StorageConfigB\vʻ\x18\astorageR\astorage\x12D\n" +
	"\btransfer\x18\x03 \x01(\v2\x1a.http.admin.TransferConfigB\fʻ\x18\btransferR\btransfer\"{\n" +
	"\n" +
	"BaseConfig\x12\x1c\n" +
	"\x04name\x18\x01 \x01(\tB\bʻ\x18\x04nameR\x04name\x121\n" +
	"\vdescription\x18\x02 \x01(\tB\x0fʻ\x18\vdescriptionR\vdescription\x12\x1c\n" +
	"\x04port\x18\x03 \x01(\x05B\bʻ\x18\x04portR\x04port\"V\n" +
	"\rStorageConfig\x12\x1c\n" +
	"\x04type\x18\x01 \x01(\tB\bʻ\x18\x04typeR\x04type\x12'\n" +
	"\bmax_size\x18\x02 \x01(\x03B\fʻ\x18\bmax_sizeR\amaxSize\"w\n" +
	"\x0eTransferConfig\x12*\n" +
	"\tmax_count\x18\x01 \x01(\x05B\rʻ\x18\tmax_countR\bmaxCount\x129\n" +
	"\x0eexpire_default\x18\x02 \x01(\x05B\x12ʻ\x18\x0eexpire_defaultR\rexpireDefault\"R\n" +
	"\x14AdminUpdateConfigReq\x12:\n" +
	"\x06config\x18\x01 \x01(\v2\x16.http.admin.ConfigDataB\n" +
	"ʻ\x18\x06configR\x06config\"\\\n" +
	"\x15AdminUpdateConfigResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage2\xc1\x06\n" +
	"\fAdminService\x12U\n" +
	"\n" +
	"AdminLogin\x12\x19.http.admin.AdminLoginReq\x1a\x1a.http.admin.AdminLoginResp\"\x10\xd2\xc1\x18\f/admin/login\x12U\n" +
	"\n" +
	"AdminStats\x12\x19.http.admin.AdminStatsReq\x1a\x1a.http.admin.AdminStatsResp\"\x10\xca\xc1\x18\f/admin/stats\x12a\n" +
	"\x0eAdminListFiles\x12\x1d.http.admin.AdminListFilesReq\x1a\x1e.http.admin.AdminListFilesResp\"\x10\xca\xc1\x18\f/admin/files\x12h\n" +
	"\x0fAdminDeleteFile\x12\x1e.http.admin.AdminDeleteFileReq\x1a\x1f.http.admin.AdminDeleteFileResp\"\x14\xe2\xc1\x18\x10/admin/files/:id\x12a\n" +
	"\x0eAdminListUsers\x12\x1d.http.admin.AdminListUsersReq\x1a\x1e.http.admin.AdminListUsersResp\"\x10\xca\xc1\x18\f/admin/users\x12\x81\x01\n" +
	"\x15AdminUpdateUserStatus\x12$.http.admin.AdminUpdateUserStatusReq\x1a%.http.admin.AdminUpdateUserStatusResp\"\x1b\xda\xc1\x18\x17/admin/users/:id/status\x12b\n" +
	"\x0eAdminGetConfig\x12\x1d.http.admin.AdminGetConfigReq\x1a\x1e.http.admin.AdminGetConfigResp\"\x11\xca\xc1\x18\r/admin/config\x12k\n" +
	"\x11AdminUpdateConfig\x12 .http.admin.AdminUpdateConfigReq\x1a!.http.admin.AdminUpdateConfigResp\"\x11\xda\xc1\x18\r/admin/configB3Z1github.com/zy84338719/fileCodeBox/biz/model/adminb\x06proto3"

var (
	file_http_admin_proto_rawDescOnce sync.Once
	file_http_admin_proto_rawDescData []byte
)

func file_http_admin_proto_rawDescGZIP() []byte {
	file_http_admin_proto_rawDescOnce.Do(func() {
		file_http_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_http_admin_proto_rawDesc), len(file_http_admin_proto_rawDesc)))
	})
	return file_http_admin_proto_rawDescData
}

var file_http_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_http_admin_proto_goTypes = []any{
	(*AdminLoginReq)(nil),             // 0: http.admin.AdminLoginReq
	(*AdminLoginResp)(nil),            // 1: http.admin.AdminLoginResp
	(*AdminLoginData)(nil),            // 2: http.admin.AdminLoginData
	(*AdminStatsReq)(nil),             // 3: http.admin.AdminStatsReq
	(*AdminStatsResp)(nil),            // 4: http.admin.AdminStatsResp
	(*AdminStatsData)(nil),            // 5: http.admin.AdminStatsData
	(*AdminListFilesReq)(nil),         // 6: http.admin.AdminListFilesReq
	(*AdminListFilesResp)(nil),        // 7: http.admin.AdminListFilesResp
	(*AdminFileList)(nil),             // 8: http.admin.AdminFileList
	(*FileItem)(nil),                  // 9: http.admin.FileItem
	(*AdminDeleteFileReq)(nil),        // 10: http.admin.AdminDeleteFileReq
	(*AdminDeleteFileResp)(nil),       // 11: http.admin.AdminDeleteFileResp
	(*AdminListUsersReq)(nil),         // 12: http.admin.AdminListUsersReq
	(*AdminListUsersResp)(nil),        // 13: http.admin.AdminListUsersResp
	(*AdminUserList)(nil),             // 14: http.admin.AdminUserList
	(*UserItem)(nil),                  // 15: http.admin.UserItem
	(*AdminUpdateUserStatusReq)(nil),  // 16: http.admin.AdminUpdateUserStatusReq
	(*AdminUpdateUserStatusResp)(nil), // 17: http.admin.AdminUpdateUserStatusResp
	(*AdminGetConfigReq)(nil),         // 18: http.admin.AdminGetConfigReq
	(*AdminGetConfigResp)(nil),        // 19: http.admin.AdminGetConfigResp
	(*ConfigData)(nil),                // 20: http.admin.ConfigData
	(*BaseConfig)(nil),                // 21: http.admin.BaseConfig
	(*StorageConfig)(nil),             // 22: http.admin.StorageConfig
	(*TransferConfig)(nil),            // 23: http.admin.TransferConfig
	(*AdminUpdateConfigReq)(nil),      // 24: http.admin.AdminUpdateConfigReq
	(*AdminUpdateConfigResp)(nil),     // 25: http.admin.AdminUpdateConfigResp
}
var file_http_admin_proto_depIdxs = []int32{
	2,  // 0: http.admin.AdminLoginResp.data:type_name -> http.admin.AdminLoginData
	5,  // 1: http.admin.AdminStatsResp.data:type_name -> http.admin.AdminStatsData
	8,  // 2: http.admin.AdminListFilesResp.data:type_name -> http.admin.AdminFileList
	9,  // 3: http.admin.AdminFileList.items:type_name -> http.admin.FileItem
	14, // 4: http.admin.AdminListUsersResp.data:type_name -> http.admin.AdminUserList
	15, // 5: http.admin.AdminUserList.items:type_name -> http.admin.UserItem
	20, // 6: http.admin.AdminGetConfigResp.data:type_name -> http.admin.ConfigData
	21, // 7: http.admin.ConfigData.base:type_name -> http.admin.BaseConfig
	22, // 8: http.admin.ConfigData.storage:type_name -> http.admin.StorageConfig
	23, // 9: http.admin.ConfigData.transfer:type_name -> http.admin.TransferConfig
	20, // 10: http.admin.AdminUpdateConfigReq.config:type_name -> http.admin.ConfigData
	0,  // 11: http.admin.AdminService.AdminLogin:input_type -> http.admin.AdminLoginReq
	3,  // 12: http.admin.AdminService.AdminStats:input_type -> http.admin.AdminStatsReq
	6,  // 13: http.admin.AdminService.AdminListFiles:input_type -> http.admin.AdminListFilesReq
	10, // 14: http.admin.AdminService.AdminDeleteFile:input_type -> http.admin.AdminDeleteFileReq
	12, // 15: http.admin.AdminService.AdminListUsers:input_type -> http.admin.AdminListUsersReq
	16, // 16: http.admin.AdminService.AdminUpdateUserStatus:input_type -> http.admin.AdminUpdateUserStatusReq
	18, // 17: http.admin.AdminService.AdminGetConfig:input_type -> http.admin.AdminGetConfigReq
	24, // 18: http.admin.AdminService.AdminUpdateConfig:input_type -> http.admin.AdminUpdateConfigReq
	1,  // 19: http.admin.AdminService.AdminLogin:output_type -> http.admin.AdminLoginResp
	4,  // 20: http.admin.AdminService.AdminStats:output_type -> http.admin.AdminStatsResp
	7,  // 21: http.admin.AdminService.AdminListFiles:output_type -> http.admin.AdminListFilesResp
	11, // 22: http.admin.AdminService.AdminDeleteFile:output_type -> http.admin.AdminDeleteFileResp
	13, // 23: http.admin.AdminService.AdminListUsers:output_type -> http.admin.AdminListUsersResp
	17, // 24: http.admin.AdminService.AdminUpdateUserStatus:output_type -> http.admin.AdminUpdateUserStatusResp
	19, // 25: http.admin.AdminService.AdminGetConfig:output_type -> http.admin.AdminGetConfigResp
	25, // 26: http.admin.AdminService.AdminUpdateConfig:output_type -> http.admin.AdminUpdateConfigResp
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_http_admin_proto_init() }
func file_http_admin_proto_init() {
	if File_http_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_admin_proto_rawDesc), len(file_http_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_http_admin_proto_goTypes,
		DependencyIndexes: file_http_admin_proto_depIdxs,
		MessageInfos:      file_http_admin_proto_msgTypes,
	}.Build()
	File_http_admin_proto = out.File
	file_http_admin_proto_goTypes = nil
	file_http_admin_proto_depIdxs = nil
}
