// Code generated by hertz generator.

package chunk

import (
	"context"
	"crypto/md5"
	"encoding/hex"
	"fmt"
	"io"
	"path/filepath"
	"strconv"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	chunkmodel "github.com/zy84338719/fileCodeBox/biz/model/chunk"
	chunkService "github.com/zy84338719/fileCodeBox/internal/app/chunk"
	shareService "github.com/zy84338719/fileCodeBox/internal/app/share"
	"github.com/zy84338719/fileCodeBox/internal/pkg/utils"
	"github.com/zy84338719/fileCodeBox/internal/storage"
	"github.com/google/uuid"
)

var chunkSvc *chunkService.Service
var shareSvc *shareService.Service
var storageSvc storage.StorageInterface

// 配置常量（应从配置读取，这里使用默认值）
const (
	defaultStoragePath = "./data"
	defaultBaseURL     = "http://localhost:12345"
)

func getChunkService() *chunkService.Service {
	if chunkSvc == nil {
		chunkSvc = chunkService.NewService()
	}
	return chunkSvc
}

func getStorageService() storage.StorageInterface {
	if storageSvc == nil {
		storageSvc = storage.NewStorageService(&storage.StorageConfig{
			Type:     storage.StorageTypeLocal,
			DataPath: defaultStoragePath,
			BaseURL:  defaultBaseURL,
		})
	}
	return storageSvc
}

func getShareService() *shareService.Service {
	if shareSvc == nil {
		shareSvc = shareService.NewService(defaultBaseURL, getStorageService())
	}
	return shareSvc
}

// ChunkUploadInit .
// @router /chunk/upload/init/ [POST]
func ChunkUploadInit(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chunkmodel.ChunkUploadInitReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": err.Error(),
		})
		return
	}

	// 参数验证
	if req.FileName == "" {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": "文件名不能为空",
		})
		return
	}
	if req.FileSize <= 0 {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": "文件大小必须大于0",
		})
		return
	}
	if req.ChunkSize <= 0 {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": "分片大小必须大于0",
		})
		return
	}

	// 生成上传ID
	uploadID := req.FileHash
	if uploadID == "" {
		uploadID = uuid.New().String()
	}

	// 检查快速上传：如果文件已存在，直接返回分享代码
	if req.FileHash != "" {
		shareCode, err := getChunkService().CheckQuickUpload(ctx, req.FileHash, req.FileSize)
		if err == nil && shareCode != "" {
			resp := &chunkmodel.ChunkUploadInitResp{
				Code:    200,
				Message: "文件已存在，快速上传成功",
				Data: &chunkmodel.ChunkUploadInitData{
					UploadId:      uploadID,
					ChunkSize:     fmt.Sprintf("%d", req.ChunkSize),
					TotalChunks:   fmt.Sprintf("%d", req.TotalChunks),
					IsQuickUpload: true,
					ShareCode:     shareCode,
				},
			}
			c.JSON(consts.StatusOK, resp)
			return
		}
	}

	// 初始化上传
	initReq := &chunkService.InitiateUploadReq{
		UploadID:    uploadID,
		FileName:    req.FileName,
		TotalChunks: int(req.TotalChunks),
		FileSize:    req.FileSize,
		ChunkSize:   int(req.ChunkSize),
	}

	result, err := getChunkService().InitiateUpload(ctx, initReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "初始化上传失败: " + err.Error(),
		})
		return
	}

	resp := &chunkmodel.ChunkUploadInitResp{
		Code:    200,
		Message: "初始化成功",
		Data: &chunkmodel.ChunkUploadInitData{
			UploadId:      result.UploadID,
			ChunkSize:     fmt.Sprintf("%d", result.ChunkSize),
			TotalChunks:   fmt.Sprintf("%d", result.TotalChunks),
			IsQuickUpload: false,
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// ChunkUpload .
// @router /chunk/upload/chunk/:upload_id/:chunk_index [POST]
func ChunkUpload(ctx context.Context, c *app.RequestContext) {
	var err error

	// 获取路径参数
	uploadID := c.Param("upload_id")
	chunkIndexStr := c.Param("chunk_index")

	if uploadID == "" {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": "上传ID不能为空",
		})
		return
	}

	chunkIndex, err := strconv.Atoi(chunkIndexStr)
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": "分片索引格式错误",
		})
		return
	}

	// 获取上传的文件
	file, err := c.FormFile("chunk")
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": "请上传分片文件",
		})
		return
	}

	// 读取文件内容
	src, err := file.Open()
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "读取文件失败: " + err.Error(),
		})
		return
	}
	defer src.Close()

	// 读取文件数据到内存
	data := make([]byte, file.Size)
	_, err = io.ReadFull(src, data)
	if err != nil && err != io.EOF && err != io.ErrUnexpectedEOF {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "读取文件内容失败: " + err.Error(),
		})
		return
	}

	// 计算分片哈希
	hash := md5.Sum(data)
	chunkHash := hex.EncodeToString(hash[:])

	// 保存分片到存储
	err = getStorageService().SaveChunk(ctx, uploadID, chunkIndex, data)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "保存分片失败: " + err.Error(),
		})
		return
	}

	// 记录分片上传信息
	uploadReq := &chunkService.UploadChunkReq{
		UploadID:   uploadID,
		ChunkIndex: chunkIndex,
		ChunkHash:  chunkHash,
		ChunkSize:  int(file.Size),
	}

	result, err := getChunkService().UploadChunk(ctx, uploadReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "记录分片信息失败: " + err.Error(),
		})
		return
	}

	resp := &chunkmodel.ChunkUploadResp{
		Code:    200,
		Message: "分片上传成功",
		Data: &chunkmodel.ChunkUploadData{
			ChunkIndex: int32(result.ChunkIndex),
			ChunkHash:  result.ChunkHash,
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// ChunkUploadStatus .
// @router /chunk/upload/status/:upload_id [GET]
func ChunkUploadStatus(ctx context.Context, c *app.RequestContext) {
	var err error

	// 获取上传ID
	uploadID := c.Param("upload_id")
	if uploadID == "" {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": "上传ID不能为空",
		})
		return
	}

	// 获取上传信息
	info, err := getChunkService().GetUploadInfo(ctx, uploadID)
	if err != nil {
		c.JSON(consts.StatusNotFound, map[string]interface{}{
			"code":    404,
			"message": "上传记录不存在",
		})
		return
	}

	// 获取已上传分片索引
	uploadedIndexes, err := getChunkService().GetUploadedChunkIndexes(ctx, uploadID)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "获取上传进度失败: " + err.Error(),
		})
		return
	}

	// 计算进度
	var progress float64
	if info.TotalChunks > 0 {
		progress = float64(len(uploadedIndexes)) / float64(info.TotalChunks) * 100
	}

	// 确定状态
	status := "uploading"
	if len(uploadedIndexes) == info.TotalChunks {
		status = "completed"
	} else if len(uploadedIndexes) == 0 {
		status = "pending"
	}

	// 转换索引数组
	uploadedIndexes32 := make([]int32, len(uploadedIndexes))
	for i, idx := range uploadedIndexes {
		uploadedIndexes32[i] = int32(idx)
	}

	resp := &chunkmodel.ChunkUploadStatusResp{
		Code:    200,
		Message: "获取成功",
		Data: &chunkmodel.ChunkUploadStatusData{
			UploadId:        info.UploadID,
			TotalChunks:     int32(info.TotalChunks),
			UploadedChunks:  int32(len(uploadedIndexes)),
			UploadedIndexes: uploadedIndexes32,
			Progress:        int32(progress),
			Status:          status,
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// ChunkUploadComplete .
// @router /chunk/upload/complete/:upload_id [POST]
func ChunkUploadComplete(ctx context.Context, c *app.RequestContext) {
	var err error

	// 获取上传ID
	uploadID := c.Param("upload_id")
	if uploadID == "" {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": "上传ID不能为空",
		})
		return
	}

	// 解析请求参数
	var req chunkmodel.ChunkUploadCompleteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": err.Error(),
		})
		return
	}

	// 获取上传信息
	info, err := getChunkService().GetUploadInfo(ctx, uploadID)
	if err != nil {
		c.JSON(consts.StatusNotFound, map[string]interface{}{
			"code":    404,
			"message": "上传记录不存在",
		})
		return
	}

	// 检查所有分片是否已上传
	uploadedIndexes, err := getChunkService().GetUploadedChunkIndexes(ctx, uploadID)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "检查上传状态失败: " + err.Error(),
		})
		return
	}

	if len(uploadedIndexes) < info.TotalChunks {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": fmt.Sprintf("还有 %d 个分片未上传", info.TotalChunks-len(uploadedIndexes)),
		})
		return
	}

	// 合并分片
	now := time.Now()
	fileExt := filepath.Ext(info.FileName)
	uuidFileName := uuid.New().String() + fileExt

	relativePath := filepath.Join(
		"uploads",
		now.Format("2006"),
		now.Format("01"),
		now.Format("02"),
		uuidFileName,
	)

	err = getStorageService().MergeChunks(ctx, uploadID, info.TotalChunks, relativePath)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "合并分片失败: " + err.Error(),
		})
		return
	}

	// 计算过期时间
	expireTime := utils.CalculateExpireTime(int(req.ExpireValue), req.ExpireStyle)
	expireCount := utils.CalculateExpireCount(req.ExpireStyle, int(req.ExpireValue))

	// 获取用户ID（如果有）
	var userID *uint
	if uid, exists := c.Get("user_id"); exists {
		if uidUint, ok := uid.(uint); ok {
			userID = &uidUint
		}
	}

	// 获取客户端 IP
	ownerIP := c.ClientIP()

	// 确定上传类型
	uploadType := "anonymous"
	if userID != nil {
		uploadType = "authenticated"
	}

	// 创建分享记录
	shareReq := &shareService.ShareFileReq{
		FilePath:     relativePath,
		Size:         info.FileSize,
		Text:         info.FileName,
		ExpiredAt:    expireTime,
		ExpiredCount: expireCount,
		RequireAuth:  req.RequireAuth,
		UserID:       userID,
		UploadType:   uploadType,
		OwnerIP:      ownerIP,
		FileHash:     uploadID,
		IsChunked:    true,
		UploadID:     uploadID,
	}

	shareResult, err := getShareService().ShareFile(ctx, shareReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "创建分享记录失败: " + err.Error(),
		})
		return
	}

	// 更新上传状态为完成
	err = getChunkService().CompleteUpload(ctx, uploadID)
	if err != nil {
		// 记录错误但不影响返回结果
		fmt.Printf("更新上传状态失败: %v\n", err)
	}

	// 生成分享URL
	fullShareURL := fmt.Sprintf("%s/share/%s", defaultBaseURL, shareResult.Code)

	resp := &chunkmodel.ChunkUploadCompleteResp{
		Code:    200,
		Message: "上传完成",
		Data: &chunkmodel.ChunkUploadCompleteData{
			ShareCode: shareResult.Code,
			ShareUrl:  fullShareURL,
			FileName:  info.FileName,
			FileSize:  info.FileSize,
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// ChunkUploadCancel .
// @router /chunk/upload/cancel/:upload_id [DELETE]
func ChunkUploadCancel(ctx context.Context, c *app.RequestContext) {
	// 获取上传ID
	uploadID := c.Param("upload_id")
	if uploadID == "" {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": "上传ID不能为空",
		})
		return
	}

	// 删除分片存储
	err := getStorageService().CleanChunks(ctx, uploadID)
	if err != nil {
		fmt.Printf("清理分片文件失败: %v\n", err)
	}

	// 删除上传记录
	err = getChunkService().DeleteUpload(ctx, uploadID)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "取消上传失败: " + err.Error(),
		})
		return
	}

	resp := &chunkmodel.ChunkUploadCancelResp{
		Code:    200,
		Message: "上传已取消",
	}

	c.JSON(consts.StatusOK, resp)
}
