// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/zy84338719/fileCodeBox/internal/pkg/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changepasswordMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.AuthMiddleware(),
	}
}

func _userinfoMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.AuthMiddleware(),
	}
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprofileMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.AuthMiddleware(),
	}
}

func _registerMw() []app.HandlerFunc {
	// 注册不需要认证
	return nil
}

func _userstatsMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.AuthMiddleware(),
	}
}

func _api_keysMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listapikeysMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.AuthMiddleware(),
	}
}

func _deleteapikeyMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.AuthMiddleware(),
	}
}

func _createapikeyMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.AuthMiddleware(),
	}
}

func _userfilesMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.AuthMiddleware(),
	}
}
