// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: http/storage.proto

package storage

import (
	_ "github.com/zy84338719/fileCodeBox/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStorageInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageInfoReq) Reset() {
	*x = GetStorageInfoReq{}
	mi := &file_http_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageInfoReq) ProtoMessage() {}

func (x *GetStorageInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageInfoReq.ProtoReflect.Descriptor instead.
func (*GetStorageInfoReq) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{0}
}

type GetStorageInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *StorageInfoData       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageInfoResp) Reset() {
	*x = GetStorageInfoResp{}
	mi := &file_http_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageInfoResp) ProtoMessage() {}

func (x *GetStorageInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageInfoResp.ProtoReflect.Descriptor instead.
func (*GetStorageInfoResp) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{1}
}

func (x *GetStorageInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetStorageInfoResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetStorageInfoResp) GetData() *StorageInfoData {
	if x != nil {
		return x.Data
	}
	return nil
}

type StorageInfoData struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	Current        string                    `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`                                                                                                               // 当前存储类型
	Available      []string                  `protobuf:"bytes,2,rep,name=available,proto3" json:"available,omitempty"`                                                                                                           // 可用存储类型列表
	StorageDetails map[string]*StorageDetail `protobuf:"bytes,3,rep,name=storage_details,json=storageDetails,proto3" json:"storage_details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 各存储类型详细信息
	StorageConfig  *StorageConfig            `protobuf:"bytes,4,opt,name=storage_config,json=storageConfig,proto3" json:"storage_config,omitempty"`                                                                              // 存储配置
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StorageInfoData) Reset() {
	*x = StorageInfoData{}
	mi := &file_http_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageInfoData) ProtoMessage() {}

func (x *StorageInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageInfoData.ProtoReflect.Descriptor instead.
func (*StorageInfoData) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{2}
}

func (x *StorageInfoData) GetCurrent() string {
	if x != nil {
		return x.Current
	}
	return ""
}

func (x *StorageInfoData) GetAvailable() []string {
	if x != nil {
		return x.Available
	}
	return nil
}

func (x *StorageInfoData) GetStorageDetails() map[string]*StorageDetail {
	if x != nil {
		return x.StorageDetails
	}
	return nil
}

func (x *StorageInfoData) GetStorageConfig() *StorageConfig {
	if x != nil {
		return x.StorageConfig
	}
	return nil
}

type StorageDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Available     bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	StoragePath   string                 `protobuf:"bytes,3,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	UsagePercent  int32                  `protobuf:"varint,4,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDetail) Reset() {
	*x = StorageDetail{}
	mi := &file_http_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDetail) ProtoMessage() {}

func (x *StorageDetail) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDetail.ProtoReflect.Descriptor instead.
func (*StorageDetail) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{3}
}

func (x *StorageDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StorageDetail) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *StorageDetail) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *StorageDetail) GetUsagePercent() int32 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *StorageDetail) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StorageConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	StoragePath   string                 `protobuf:"bytes,2,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	Webdav        *WebDAVConfig          `protobuf:"bytes,3,opt,name=webdav,proto3" json:"webdav,omitempty"`
	S3            *S3Config              `protobuf:"bytes,4,opt,name=s3,proto3" json:"s3,omitempty"`
	Nfs           *NFSConfig             `protobuf:"bytes,5,opt,name=nfs,proto3" json:"nfs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageConfig) Reset() {
	*x = StorageConfig{}
	mi := &file_http_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageConfig) ProtoMessage() {}

func (x *StorageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageConfig.ProtoReflect.Descriptor instead.
func (*StorageConfig) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{4}
}

func (x *StorageConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StorageConfig) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *StorageConfig) GetWebdav() *WebDAVConfig {
	if x != nil {
		return x.Webdav
	}
	return nil
}

func (x *StorageConfig) GetS3() *S3Config {
	if x != nil {
		return x.S3
	}
	return nil
}

func (x *StorageConfig) GetNfs() *NFSConfig {
	if x != nil {
		return x.Nfs
	}
	return nil
}

type WebDAVConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	RootPath      string                 `protobuf:"bytes,4,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebDAVConfig) Reset() {
	*x = WebDAVConfig{}
	mi := &file_http_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebDAVConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebDAVConfig) ProtoMessage() {}

func (x *WebDAVConfig) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebDAVConfig.ProtoReflect.Descriptor instead.
func (*WebDAVConfig) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{5}
}

func (x *WebDAVConfig) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WebDAVConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WebDAVConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *WebDAVConfig) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

func (x *WebDAVConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type S3Config struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	BucketName      string                 `protobuf:"bytes,3,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	EndpointUrl     string                 `protobuf:"bytes,4,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	RegionName      string                 `protobuf:"bytes,5,opt,name=region_name,json=regionName,proto3" json:"region_name,omitempty"`
	Hostname        string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Proxy           string                 `protobuf:"bytes,7,opt,name=proxy,proto3" json:"proxy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S3Config) Reset() {
	*x = S3Config{}
	mi := &file_http_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Config) ProtoMessage() {}

func (x *S3Config) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Config.ProtoReflect.Descriptor instead.
func (*S3Config) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{6}
}

func (x *S3Config) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *S3Config) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *S3Config) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *S3Config) GetEndpointUrl() string {
	if x != nil {
		return x.EndpointUrl
	}
	return ""
}

func (x *S3Config) GetRegionName() string {
	if x != nil {
		return x.RegionName
	}
	return ""
}

func (x *S3Config) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *S3Config) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

type NFSConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	MountPoint    string                 `protobuf:"bytes,3,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Options       string                 `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	Timeout       int32                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	AutoMount     int32                  `protobuf:"varint,7,opt,name=auto_mount,json=autoMount,proto3" json:"auto_mount,omitempty"`
	RetryCount    int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	SubPath       string                 `protobuf:"bytes,9,opt,name=sub_path,json=subPath,proto3" json:"sub_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NFSConfig) Reset() {
	*x = NFSConfig{}
	mi := &file_http_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NFSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NFSConfig) ProtoMessage() {}

func (x *NFSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NFSConfig.ProtoReflect.Descriptor instead.
func (*NFSConfig) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{7}
}

func (x *NFSConfig) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *NFSConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NFSConfig) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *NFSConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NFSConfig) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

func (x *NFSConfig) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *NFSConfig) GetAutoMount() int32 {
	if x != nil {
		return x.AutoMount
	}
	return 0
}

func (x *NFSConfig) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *NFSConfig) GetSubPath() string {
	if x != nil {
		return x.SubPath
	}
	return ""
}

type SwitchStorageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchStorageReq) Reset() {
	*x = SwitchStorageReq{}
	mi := &file_http_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchStorageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchStorageReq) ProtoMessage() {}

func (x *SwitchStorageReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchStorageReq.ProtoReflect.Descriptor instead.
func (*SwitchStorageReq) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{8}
}

func (x *SwitchStorageReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SwitchStorageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *SwitchStorageData     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchStorageResp) Reset() {
	*x = SwitchStorageResp{}
	mi := &file_http_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchStorageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchStorageResp) ProtoMessage() {}

func (x *SwitchStorageResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchStorageResp.ProtoReflect.Descriptor instead.
func (*SwitchStorageResp) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{9}
}

func (x *SwitchStorageResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SwitchStorageResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SwitchStorageResp) GetData() *SwitchStorageData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SwitchStorageData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CurrentType   string                 `protobuf:"bytes,3,opt,name=current_type,json=currentType,proto3" json:"current_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchStorageData) Reset() {
	*x = SwitchStorageData{}
	mi := &file_http_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchStorageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchStorageData) ProtoMessage() {}

func (x *SwitchStorageData) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchStorageData.ProtoReflect.Descriptor instead.
func (*SwitchStorageData) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{10}
}

func (x *SwitchStorageData) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SwitchStorageData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SwitchStorageData) GetCurrentType() string {
	if x != nil {
		return x.CurrentType
	}
	return ""
}

type TestStorageConnectionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestStorageConnectionReq) Reset() {
	*x = TestStorageConnectionReq{}
	mi := &file_http_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestStorageConnectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestStorageConnectionReq) ProtoMessage() {}

func (x *TestStorageConnectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestStorageConnectionReq.ProtoReflect.Descriptor instead.
func (*TestStorageConnectionReq) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{11}
}

func (x *TestStorageConnectionReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type TestStorageConnectionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TestStorageData       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestStorageConnectionResp) Reset() {
	*x = TestStorageConnectionResp{}
	mi := &file_http_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestStorageConnectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestStorageConnectionResp) ProtoMessage() {}

func (x *TestStorageConnectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestStorageConnectionResp.ProtoReflect.Descriptor instead.
func (*TestStorageConnectionResp) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{12}
}

func (x *TestStorageConnectionResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TestStorageConnectionResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestStorageConnectionResp) GetData() *TestStorageData {
	if x != nil {
		return x.Data
	}
	return nil
}

type TestStorageData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestStorageData) Reset() {
	*x = TestStorageData{}
	mi := &file_http_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestStorageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestStorageData) ProtoMessage() {}

func (x *TestStorageData) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestStorageData.ProtoReflect.Descriptor instead.
func (*TestStorageData) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{13}
}

func (x *TestStorageData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TestStorageData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateStorageConfigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Config        *UpdateConfig          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStorageConfigReq) Reset() {
	*x = UpdateStorageConfigReq{}
	mi := &file_http_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStorageConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStorageConfigReq) ProtoMessage() {}

func (x *UpdateStorageConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStorageConfigReq.ProtoReflect.Descriptor instead.
func (*UpdateStorageConfigReq) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateStorageConfigReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateStorageConfigReq) GetConfig() *UpdateConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoragePath   string                 `protobuf:"bytes,1,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	Webdav        *WebDAVConfig          `protobuf:"bytes,2,opt,name=webdav,proto3" json:"webdav,omitempty"`
	S3            *S3Config              `protobuf:"bytes,3,opt,name=s3,proto3" json:"s3,omitempty"`
	Nfs           *NFSConfig             `protobuf:"bytes,4,opt,name=nfs,proto3" json:"nfs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfig) Reset() {
	*x = UpdateConfig{}
	mi := &file_http_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfig) ProtoMessage() {}

func (x *UpdateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfig.ProtoReflect.Descriptor instead.
func (*UpdateConfig) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateConfig) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *UpdateConfig) GetWebdav() *WebDAVConfig {
	if x != nil {
		return x.Webdav
	}
	return nil
}

func (x *UpdateConfig) GetS3() *S3Config {
	if x != nil {
		return x.S3
	}
	return nil
}

func (x *UpdateConfig) GetNfs() *NFSConfig {
	if x != nil {
		return x.Nfs
	}
	return nil
}

type UpdateStorageConfigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStorageConfigResp) Reset() {
	*x = UpdateStorageConfigResp{}
	mi := &file_http_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStorageConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStorageConfigResp) ProtoMessage() {}

func (x *UpdateStorageConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStorageConfigResp.ProtoReflect.Descriptor instead.
func (*UpdateStorageConfigResp) Descriptor() ([]byte, []int) {
	return file_http_storage_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateStorageConfigResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateStorageConfigResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_http_storage_proto protoreflect.FileDescriptor

const file_http_storage_proto_rawDesc = "" +
	"\n" +
	"\x12http/storage.proto\x12\fhttp.storage\x1a\rapi/api.proto\"\x13\n" +
	"\x11GetStorageInfoReq\"\x96\x01\n" +
	"\x12GetStorageInfoResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x12;\n" +
	"\x04data\x18\x03 \x01(\v2\x1d.http.storage.StorageInfoDataB\bʻ\x18\x04dataR\x04data\"\x8e\x03\n" +
	"\x0fStorageInfoData\x12%\n" +
	"\acurrent\x18\x01 \x01(\tB\vʻ\x18\acurrentR\acurrent\x12+\n" +
	"\tavailable\x18\x02 \x03(\tB\rʻ\x18\tavailableR\tavailable\x12o\n" +
	"\x0fstorage_details\x18\x03 \x03(\v21.http.storage.StorageInfoData.StorageDetailsEntryB\x13ʻ\x18\x0fstorage_detailsR\x0estorageDetails\x12V\n" +
	"\x0estorage_config\x18\x04 \x01(\v2\x1b.http.storage.StorageConfigB\x12ʻ\x18\x0estorage_configR\rstorageConfig\x1a^\n" +
	"\x13StorageDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.http.storage.StorageDetailR\x05value:\x028\x01\"\xe8\x01\n" +
	"\rStorageDetail\x12\x1c\n" +
	"\x04type\x18\x01 \x01(\tB\bʻ\x18\x04typeR\x04type\x12+\n" +
	"\tavailable\x18\x02 \x01(\bB\rʻ\x18\tavailableR\tavailable\x123\n" +
	"\fstorage_path\x18\x03 \x01(\tB\x10ʻ\x18\fstorage_pathR\vstoragePath\x126\n" +
	"\rusage_percent\x18\x04 \x01(\x05B\x11ʻ\x18\rusage_percentR\fusagePercent\x12\x1f\n" +
	"\x05error\x18\x05 \x01(\tB\tʻ\x18\x05errorR\x05error\"\x86\x02\n" +
	"\rStorageConfig\x12\x1c\n" +
	"\x04type\x18\x01 \x01(\tB\bʻ\x18\x04typeR\x04type\x123\n" +
	"\fstorage_path\x18\x02 \x01(\tB\x10ʻ\x18\fstorage_pathR\vstoragePath\x12>\n" +
	"\x06webdav\x18\x03 \x01(\v2\x1a.http.storage.WebDAVConfigB\n" +
	"ʻ\x18\x06webdavR\x06webdav\x12.\n" +
	"\x02s3\x18\x04 \x01(\v2\x16.http.storage.S3ConfigB\x06ʻ\x18\x02s3R\x02s3\x122\n" +
	"\x03nfs\x18\x05 \x01(\v2\x17.http.storage.NFSConfigB\aʻ\x18\x03nfsR\x03nfs\"\xd3\x01\n" +
	"\fWebDAVConfig\x12(\n" +
	"\bhostname\x18\x01 \x01(\tB\fʻ\x18\bhostnameR\bhostname\x12(\n" +
	"\busername\x18\x02 \x01(\tB\fʻ\x18\busernameR\busername\x12(\n" +
	"\bpassword\x18\x03 \x01(\tB\fʻ\x18\bpasswordR\bpassword\x12*\n" +
	"\troot_path\x18\x04 \x01(\tB\rʻ\x18\troot_pathR\brootPath\x12\x19\n" +
	"\x03url\x18\x05 \x01(\tB\aʻ\x18\x03urlR\x03url\"\xe8\x02\n" +
	"\bS3Config\x125\n" +
	"\raccess_key_id\x18\x01 \x01(\tB\x11ʻ\x18\raccess_key_idR\vaccessKeyId\x12A\n" +
	"\x11secret_access_key\x18\x02 \x01(\tB\x15ʻ\x18\x11secret_access_keyR\x0fsecretAccessKey\x120\n" +
	"\vbucket_name\x18\x03 \x01(\tB\x0fʻ\x18\vbucket_nameR\n" +
	"bucketName\x123\n" +
	"\fendpoint_url\x18\x04 \x01(\tB\x10ʻ\x18\fendpoint_urlR\vendpointUrl\x120\n" +
	"\vregion_name\x18\x05 \x01(\tB\x0fʻ\x18\vregion_nameR\n" +
	"regionName\x12(\n" +
	"\bhostname\x18\x06 \x01(\tB\fʻ\x18\bhostnameR\bhostname\x12\x1f\n" +
	"\x05proxy\x18\a \x01(\tB\tʻ\x18\x05proxyR\x05proxy\"\xfe\x02\n" +
	"\tNFSConfig\x12\"\n" +
	"\x06server\x18\x01 \x01(\tB\n" +
	"ʻ\x18\x06serverR\x06server\x12\x1c\n" +
	"\x04path\x18\x02 \x01(\tB\bʻ\x18\x04pathR\x04path\x120\n" +
	"\vmount_point\x18\x03 \x01(\tB\x0fʻ\x18\vmount_pointR\n" +
	"mountPoint\x12%\n" +
	"\aversion\x18\x04 \x01(\tB\vʻ\x18\aversionR\aversion\x12%\n" +
	"\aoptions\x18\x05 \x01(\tB\vʻ\x18\aoptionsR\aoptions\x12%\n" +
	"\atimeout\x18\x06 \x01(\x05B\vʻ\x18\atimeoutR\atimeout\x12-\n" +
	"\n" +
	"auto_mount\x18\a \x01(\x05B\x0eʻ\x18\n" +
	"auto_mountR\tautoMount\x120\n" +
	"\vretry_count\x18\b \x01(\x05B\x0fʻ\x18\vretry_countR\n" +
	"retryCount\x12'\n" +
	"\bsub_path\x18\t \x01(\tB\fʻ\x18\bsub_pathR\asubPath\"0\n" +
	"\x10SwitchStorageReq\x12\x1c\n" +
	"\x04type\x18\x01 \x01(\tB\bʻ\x18\x04typeR\x04type\"\x97\x01\n" +
	"\x11SwitchStorageResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x12=\n" +
	"\x04data\x18\x03 \x01(\v2\x1f.http.storage.SwitchStorageDataB\bʻ\x18\x04dataR\x04data\"\x96\x01\n" +
	"\x11SwitchStorageData\x12%\n" +
	"\asuccess\x18\x01 \x01(\bB\vʻ\x18\asuccessR\asuccess\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x123\n" +
	"\fcurrent_type\x18\x03 \x01(\tB\x10ʻ\x18\fcurrent_typeR\vcurrentType\"8\n" +
	"\x18TestStorageConnectionReq\x12\x1c\n" +
	"\x04type\x18\x01 \x01(\tB\bһ\x18\x04typeR\x04type\"\x9d\x01\n" +
	"\x19TestStorageConnectionResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x12;\n" +
	"\x04data\x18\x03 \x01(\v2\x1d.http.storage.TestStorageDataB\bʻ\x18\x04dataR\x04data\"S\n" +
	"\x0fTestStorageData\x12\x1c\n" +
	"\x04type\x18\x01 \x01(\tB\bʻ\x18\x04typeR\x04type\x12\"\n" +
	"\x06status\x18\x02 \x01(\tB\n" +
	"ʻ\x18\x06statusR\x06status\"v\n" +
	"\x16UpdateStorageConfigReq\x12\x1c\n" +
	"\x04type\x18\x01 \x01(\tB\bʻ\x18\x04typeR\x04type\x12>\n" +
	"\x06config\x18\x02 \x01(\v2\x1a.http.storage.UpdateConfigB\n" +
	"ʻ\x18\x06configR\x06config\"\xe7\x01\n" +
	"\fUpdateConfig\x123\n" +
	"\fstorage_path\x18\x01 \x01(\tB\x10ʻ\x18\fstorage_pathR\vstoragePath\x12>\n" +
	"\x06webdav\x18\x02 \x01(\v2\x1a.http.storage.WebDAVConfigB\n" +
	"ʻ\x18\x06webdavR\x06webdav\x12.\n" +
	"\x02s3\x18\x03 \x01(\v2\x16.http.storage.S3ConfigB\x06ʻ\x18\x02s3R\x02s3\x122\n" +
	"\x03nfs\x18\x04 \x01(\v2\x17.http.storage.NFSConfigB\aʻ\x18\x03nfsR\x03nfs\"^\n" +
	"\x17UpdateStorageConfigResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage2\xef\x03\n" +
	"\x0eStorageService\x12g\n" +
	"\x0eGetStorageInfo\x12\x1f.http.storage.GetStorageInfoReq\x1a .http.storage.GetStorageInfoResp\"\x12\xca\xc1\x18\x0e/admin/storage\x12k\n" +
	"\rSwitchStorage\x12\x1e.http.storage.SwitchStorageReq\x1a\x1f.http.storage.SwitchStorageResp\"\x19\xd2\xc1\x18\x15/admin/storage/switch\x12\x87\x01\n" +
	"\x15TestStorageConnection\x12&.http.storage.TestStorageConnectionReq\x1a'.http.storage.TestStorageConnectionResp\"\x1d\xca\xc1\x18\x19/admin/storage/test/:type\x12}\n" +
	"\x13UpdateStorageConfig\x12$.http.storage.UpdateStorageConfigReq\x1a%.http.storage.UpdateStorageConfigResp\"\x19\xda\xc1\x18\x15/admin/storage/configB5Z3github.com/zy84338719/fileCodeBox/biz/model/storageb\x06proto3"

var (
	file_http_storage_proto_rawDescOnce sync.Once
	file_http_storage_proto_rawDescData []byte
)

func file_http_storage_proto_rawDescGZIP() []byte {
	file_http_storage_proto_rawDescOnce.Do(func() {
		file_http_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_http_storage_proto_rawDesc), len(file_http_storage_proto_rawDesc)))
	})
	return file_http_storage_proto_rawDescData
}

var file_http_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_http_storage_proto_goTypes = []any{
	(*GetStorageInfoReq)(nil),         // 0: http.storage.GetStorageInfoReq
	(*GetStorageInfoResp)(nil),        // 1: http.storage.GetStorageInfoResp
	(*StorageInfoData)(nil),           // 2: http.storage.StorageInfoData
	(*StorageDetail)(nil),             // 3: http.storage.StorageDetail
	(*StorageConfig)(nil),             // 4: http.storage.StorageConfig
	(*WebDAVConfig)(nil),              // 5: http.storage.WebDAVConfig
	(*S3Config)(nil),                  // 6: http.storage.S3Config
	(*NFSConfig)(nil),                 // 7: http.storage.NFSConfig
	(*SwitchStorageReq)(nil),          // 8: http.storage.SwitchStorageReq
	(*SwitchStorageResp)(nil),         // 9: http.storage.SwitchStorageResp
	(*SwitchStorageData)(nil),         // 10: http.storage.SwitchStorageData
	(*TestStorageConnectionReq)(nil),  // 11: http.storage.TestStorageConnectionReq
	(*TestStorageConnectionResp)(nil), // 12: http.storage.TestStorageConnectionResp
	(*TestStorageData)(nil),           // 13: http.storage.TestStorageData
	(*UpdateStorageConfigReq)(nil),    // 14: http.storage.UpdateStorageConfigReq
	(*UpdateConfig)(nil),              // 15: http.storage.UpdateConfig
	(*UpdateStorageConfigResp)(nil),   // 16: http.storage.UpdateStorageConfigResp
	nil,                               // 17: http.storage.StorageInfoData.StorageDetailsEntry
}
var file_http_storage_proto_depIdxs = []int32{
	2,  // 0: http.storage.GetStorageInfoResp.data:type_name -> http.storage.StorageInfoData
	17, // 1: http.storage.StorageInfoData.storage_details:type_name -> http.storage.StorageInfoData.StorageDetailsEntry
	4,  // 2: http.storage.StorageInfoData.storage_config:type_name -> http.storage.StorageConfig
	5,  // 3: http.storage.StorageConfig.webdav:type_name -> http.storage.WebDAVConfig
	6,  // 4: http.storage.StorageConfig.s3:type_name -> http.storage.S3Config
	7,  // 5: http.storage.StorageConfig.nfs:type_name -> http.storage.NFSConfig
	10, // 6: http.storage.SwitchStorageResp.data:type_name -> http.storage.SwitchStorageData
	13, // 7: http.storage.TestStorageConnectionResp.data:type_name -> http.storage.TestStorageData
	15, // 8: http.storage.UpdateStorageConfigReq.config:type_name -> http.storage.UpdateConfig
	5,  // 9: http.storage.UpdateConfig.webdav:type_name -> http.storage.WebDAVConfig
	6,  // 10: http.storage.UpdateConfig.s3:type_name -> http.storage.S3Config
	7,  // 11: http.storage.UpdateConfig.nfs:type_name -> http.storage.NFSConfig
	3,  // 12: http.storage.StorageInfoData.StorageDetailsEntry.value:type_name -> http.storage.StorageDetail
	0,  // 13: http.storage.StorageService.GetStorageInfo:input_type -> http.storage.GetStorageInfoReq
	8,  // 14: http.storage.StorageService.SwitchStorage:input_type -> http.storage.SwitchStorageReq
	11, // 15: http.storage.StorageService.TestStorageConnection:input_type -> http.storage.TestStorageConnectionReq
	14, // 16: http.storage.StorageService.UpdateStorageConfig:input_type -> http.storage.UpdateStorageConfigReq
	1,  // 17: http.storage.StorageService.GetStorageInfo:output_type -> http.storage.GetStorageInfoResp
	9,  // 18: http.storage.StorageService.SwitchStorage:output_type -> http.storage.SwitchStorageResp
	12, // 19: http.storage.StorageService.TestStorageConnection:output_type -> http.storage.TestStorageConnectionResp
	16, // 20: http.storage.StorageService.UpdateStorageConfig:output_type -> http.storage.UpdateStorageConfigResp
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_http_storage_proto_init() }
func file_http_storage_proto_init() {
	if File_http_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_storage_proto_rawDesc), len(file_http_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_http_storage_proto_goTypes,
		DependencyIndexes: file_http_storage_proto_depIdxs,
		MessageInfos:      file_http_storage_proto_msgTypes,
	}.Build()
	File_http_storage_proto = out.File
	file_http_storage_proto_goTypes = nil
	file_http_storage_proto_depIdxs = nil
}
