CREATE TABLE `users` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`username` text,`email` text,`password_hash` text,`nickname` text,`avatar` text,`role` text DEFAULT "user",`status` text DEFAULT "active",`email_verified` numeric DEFAULT false,`last_login_at` datetime,`last_login_ip` text,`total_uploads` integer DEFAULT 0,`total_downloads` integer DEFAULT 0,`total_storage` integer DEFAULT 0,`max_upload_size` integer DEFAULT 0,`max_storage_quota` integer DEFAULT 0);
CREATE UNIQUE INDEX `idx_users_email` ON `users`(`email`);
CREATE UNIQUE INDEX `idx_users_username` ON `users`(`username`);
CREATE INDEX `idx_users_deleted_at` ON `users`(`deleted_at`);
CREATE TABLE `file_codes` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`code` text,`prefix` text,`suffix` text,`uuid_file_name` text,`file_path` text,`size` integer DEFAULT 0,`text` text,`expired_at` datetime,`expired_count` integer DEFAULT 0,`used_count` integer DEFAULT 0,`file_hash` text,`is_chunked` numeric DEFAULT false,`upload_id` text,`user_id` integer,`upload_type` text DEFAULT "anonymous",`require_auth` numeric DEFAULT false,`owner_ip` text,`viewer_ip` text,`viewer_at` datetime,`viewer_count` integer DEFAULT 0,`last_notified_at` datetime);
CREATE INDEX `idx_file_codes_user_id` ON `file_codes`(`user_id`);
CREATE UNIQUE INDEX `idx_file_codes_code` ON `file_codes`(`code`);
CREATE INDEX `idx_file_codes_deleted_at` ON `file_codes`(`deleted_at`);
CREATE TABLE `upload_chunks` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`upload_id` text,`chunk_index` integer,`chunk_hash` text,`total_chunks` integer,`file_size` integer,`chunk_size` integer,`file_name` text,`completed` numeric DEFAULT false,`retry_count` integer DEFAULT 0,`last_error` text,`status` text DEFAULT "pending");
CREATE INDEX `idx_upload_chunks_upload_id` ON `upload_chunks`(`upload_id`);
CREATE INDEX `idx_upload_chunks_deleted_at` ON `upload_chunks`(`deleted_at`);
CREATE TABLE `transfer_logs` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`operation` text,`file_code_id` integer,`file_code` text,`file_name` text,`file_size` integer,`user_id` integer,`username` text,`ip` text,`duration_ms` integer);
CREATE INDEX `idx_transfer_logs_user_id` ON `transfer_logs`(`user_id`);
CREATE INDEX `idx_transfer_logs_file_code_id` ON `transfer_logs`(`file_code_id`);
CREATE INDEX `idx_transfer_logs_operation` ON `transfer_logs`(`operation`);
CREATE INDEX `idx_transfer_logs_deleted_at` ON `transfer_logs`(`deleted_at`);
CREATE TABLE `admin_operation_logs` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`action` text,`target` text,`success` numeric,`message` text,`actor_id` integer,`actor_name` text,`ip` text,`latency_ms` integer);
CREATE INDEX `idx_admin_operation_logs_actor_id` ON `admin_operation_logs`(`actor_id`);
CREATE INDEX `idx_admin_operation_logs_action` ON `admin_operation_logs`(`action`);
CREATE INDEX `idx_admin_operation_logs_deleted_at` ON `admin_operation_logs`(`deleted_at`);
CREATE TABLE `user_api_keys` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`user_id` integer,`name` text,`prefix` text,`key_hash` text,`last_used_at` datetime,`expires_at` datetime,`revoked_at` datetime,`revoked` numeric DEFAULT false);
CREATE INDEX `idx_user_api_keys_user_id` ON `user_api_keys`(`user_id`);
CREATE INDEX `idx_user_api_keys_deleted_at` ON `user_api_keys`(`deleted_at`);
CREATE UNIQUE INDEX `idx_user_api_keys_key_hash` ON `user_api_keys`(`key_hash`);
CREATE TABLE `file_previews` (`id` integer PRIMARY KEY AUTOINCREMENT,`file_code_id` integer NOT NULL,`preview_type` text NOT NULL,`thumbnail` text,`preview_url` text,`width` integer,`height` integer,`duration` integer,`page_count` integer,`text_content` text,`mime_type` text,`file_size` integer,`created_at` datetime,`updated_at` datetime);
CREATE UNIQUE INDEX `idx_file_previews_file_code_id` ON `file_previews`(`file_code_id`);
CREATE TABLE `notifies` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`title` text NOT NULL,`content` text NOT NULL,`type` text DEFAULT "system",`level` text DEFAULT "info",`status` integer DEFAULT 1,`start_at` datetime,`end_at` datetime,`author_id` integer,`target_user_id` integer,`read_at` datetime);
CREATE INDEX `idx_notifies_target_user_id` ON `notifies`(`target_user_id`);
CREATE INDEX `idx_notifies_author_id` ON `notifies`(`author_id`);
CREATE INDEX `idx_notifies_status` ON `notifies`(`status`);
CREATE INDEX `idx_notifies_level` ON `notifies`(`level`);
CREATE INDEX `idx_notifies_type` ON `notifies`(`type`);
CREATE INDEX `idx_notifies_deleted_at` ON `notifies`(`deleted_at`);
CREATE INDEX `idx_notifies_read_at` ON `notifies`(`read_at`);
