// Code generated by hertz generator.

package admin

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	admin "github.com/zy84338719/fileCodeBox/biz/model/admin"
	adminsvc "github.com/zy84338719/fileCodeBox/internal/app/admin"
)

var maintenanceService *adminsvc.Service

func init() {
	maintenanceService = adminsvc.NewService()
}

// CleanExpiredFiles .
// @router /admin/maintenance/clean-expired [POST]
func CleanExpiredFiles(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.CleanExpiredFilesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用服务层清理过期文件
	deletedCount, freedSpace, err := maintenanceService.CleanExpiredFiles(ctx)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &admin.CleanExpiredFilesResp{
			Code:    500,
			Message: "清理失败: " + err.Error(),
		})
		return
	}

	resp := &admin.CleanExpiredFilesResp{
		Code:    200,
		Message: "清理完成",
		Data: &admin.CleanExpiredFilesData{
			DeletedCount: deletedCount,
			FreedSpace:   freedSpace,
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// CleanTempFiles .
// @router /admin/maintenance/clean-temp [POST]
func CleanTempFiles(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.CleanTempFilesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用服务层清理临时文件
	deletedCount, _, err := maintenanceService.CleanTempFiles(ctx)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &admin.CleanTempFilesResp{
			Code:    500,
			Message: "清理失败: " + err.Error(),
		})
		return
	}

	resp := &admin.CleanTempFilesResp{
		Code:    200,
		Message: "清理完成",
		Data: &admin.CleanTempFilesData{
			DeletedCount: deletedCount,
			FreedSpace:   0,
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// GetSystemInfo .
// @router /admin/maintenance/system-info [GET]
func GetSystemInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.GetSystemInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用服务层获取系统信息
	info, err := maintenanceService.GetSystemInfo(ctx)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &admin.GetSystemInfoResp{
			Code:    500,
			Message: "获取系统信息失败: " + err.Error(),
		})
		return
	}

	resp := &admin.GetSystemInfoResp{
		Code:    200,
		Message: "获取成功",
		Data: &admin.SystemInfoData{
			Version:      info.Version,
			Os:           info.OS,
			Arch:         info.Arch,
			Uptime:       info.Uptime,
			Goroutines:   info.Goroutines,
			MemoryAlloc:  info.MemoryAlloc,
			MemoryTotal:  info.MemoryTotal,
			MemorySys:    info.MemorySys,
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// GetStorageStatus .
// @router /admin/maintenance/monitor/storage [GET]
func GetStorageStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.GetStorageStatusReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用服务层获取存储状态
	status, err := maintenanceService.GetStorageStatus(ctx)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &admin.GetStorageStatusResp{
			Code:    500,
			Message: "获取存储状态失败: " + err.Error(),
		})
		return
	}

	resp := &admin.GetStorageStatusResp{
		Code:    200,
		Message: "获取成功",
		Data: &admin.StorageStatusData{
			StorageType: status.StorageType,
			TotalSpace:  status.TotalSpace,
			UsedSpace:   status.UsedSpace,
			FreeSpace:   status.FreeSpace,
			FileCount:   status.FileCount,
			UsagePercent: status.UsagePercent,
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// GetSystemLogs .
// @router /admin/maintenance/logs [GET]
func GetSystemLogs(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.GetSystemLogsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 处理分页参数
	page := req.Page
	pageSize := req.PageSize
	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 || pageSize > 100 {
		pageSize = 20
	}

	// 调用服务层获取系统日志
	logs, total, err := maintenanceService.GetSystemLogs(ctx, req.Level, int(page), int(pageSize))
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &admin.GetSystemLogsResp{
			Code:    500,
			Message: "获取系统日志失败: " + err.Error(),
		})
		return
	}

	// 转换为响应格式
	logEntries := make([]*admin.LogEntry, len(logs))
	for i, log := range logs {
		logEntries[i] = &admin.LogEntry{
			Id:        log.ID,
			Level:     log.Level,
			Message:   log.Message,
			CreatedAt: log.CreatedAt,
			Module:    log.Module,
			UserId:    log.UserID,
		}
	}

	resp := &admin.GetSystemLogsResp{
		Code:    200,
		Message: "获取成功",
		Data: &admin.SystemLogsData{
			Logs:     logEntries,
			Total:    total,
			Page:     page,
			PageSize:  pageSize,
		},
	}

	c.JSON(consts.StatusOK, resp)
}
