// Code generated by hertz generator. DO NOT EDIT.

package admin

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	admin "github.com/zy84338719/fileCodeBox/biz/handler/admin"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// RegisterMaintenance register maintenance routes based on the IDL 'api.${HTTP Method}' annotation.
func RegisterMaintenance(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_admin := root.Group("/admin", _adminMw()...)
		{
			_maintenance := _admin.Group("/maintenance", _maintenanceMw()...)
			_maintenance.POST("/clean-expired", append(_cleanexpiredfilesMw(), admin.CleanExpiredFiles)...)
			_maintenance.POST("/clean-temp", append(_cleantempfilesMw(), admin.CleanTempFiles)...)
			_maintenance.GET("/logs", append(_getsystemlogsMw(), admin.GetSystemLogs)...)
			_maintenance.GET("/system-info", append(_getsysteminfoMw(), admin.GetSystemInfo)...)
			{
				_monitor := _maintenance.Group("/monitor", _monitorMw()...)
				_monitor.GET("/storage", append(_getstoragestatusMw(), admin.GetStorageStatus)...)
			}
		}
	}
}
