// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	admin "github.com/zy84338719/fileCodeBox/biz/router/admin"
	chunk "github.com/zy84338719/fileCodeBox/biz/router/chunk"
	health "github.com/zy84338719/fileCodeBox/biz/router/health"
	preview "github.com/zy84338719/fileCodeBox/biz/router/preview"
	qrcode "github.com/zy84338719/fileCodeBox/biz/router/qrcode"
	setup "github.com/zy84338719/fileCodeBox/biz/router/setup"
	share "github.com/zy84338719/fileCodeBox/biz/router/share"
	storage "github.com/zy84338719/fileCodeBox/biz/router/storage"
	user "github.com/zy84338719/fileCodeBox/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	health.Register(r)

	qrcode.Register(r)

	setup.Register(r)

	storage.Register(r)

	chunk.Register(r)

	admin.Register(r)
	admin.RegisterMaintenance(r)

	user.Register(r)

	share.Register(r)

	preview.Register(r)
}
