// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: http/share.proto

package share

import (
	_ "github.com/zy84338719/fileCodeBox/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShareTextReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	ExpireValue   int32                  `protobuf:"varint,2,opt,name=expire_value,json=expireValue,proto3" json:"expire_value,omitempty"`
	ExpireStyle   string                 `protobuf:"bytes,3,opt,name=expire_style,json=expireStyle,proto3" json:"expire_style,omitempty"` // minute, hour, day, week, month, year, forever
	RequireAuth   bool                   `protobuf:"varint,4,opt,name=require_auth,json=requireAuth,proto3" json:"require_auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareTextReq) Reset() {
	*x = ShareTextReq{}
	mi := &file_http_share_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareTextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareTextReq) ProtoMessage() {}

func (x *ShareTextReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_share_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareTextReq.ProtoReflect.Descriptor instead.
func (*ShareTextReq) Descriptor() ([]byte, []int) {
	return file_http_share_proto_rawDescGZIP(), []int{0}
}

func (x *ShareTextReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ShareTextReq) GetExpireValue() int32 {
	if x != nil {
		return x.ExpireValue
	}
	return 0
}

func (x *ShareTextReq) GetExpireStyle() string {
	if x != nil {
		return x.ExpireStyle
	}
	return ""
}

func (x *ShareTextReq) GetRequireAuth() bool {
	if x != nil {
		return x.RequireAuth
	}
	return false
}

type ShareTextResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ShareData             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareTextResp) Reset() {
	*x = ShareTextResp{}
	mi := &file_http_share_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareTextResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareTextResp) ProtoMessage() {}

func (x *ShareTextResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_share_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareTextResp.ProtoReflect.Descriptor instead.
func (*ShareTextResp) Descriptor() ([]byte, []int) {
	return file_http_share_proto_rawDescGZIP(), []int{1}
}

func (x *ShareTextResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ShareTextResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ShareTextResp) GetData() *ShareData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ShareData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareData) Reset() {
	*x = ShareData{}
	mi := &file_http_share_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareData) ProtoMessage() {}

func (x *ShareData) ProtoReflect() protoreflect.Message {
	mi := &file_http_share_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareData.ProtoReflect.Descriptor instead.
func (*ShareData) Descriptor() ([]byte, []int) {
	return file_http_share_proto_rawDescGZIP(), []int{2}
}

func (x *ShareData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShareData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShareFileReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 文件通过 multipart/form-data 上传
	ExpireValue   int32  `protobuf:"varint,1,opt,name=expire_value,json=expireValue,proto3" json:"expire_value,omitempty"`
	ExpireStyle   string `protobuf:"bytes,2,opt,name=expire_style,json=expireStyle,proto3" json:"expire_style,omitempty"`
	RequireAuth   bool   `protobuf:"varint,3,opt,name=require_auth,json=requireAuth,proto3" json:"require_auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareFileReq) Reset() {
	*x = ShareFileReq{}
	mi := &file_http_share_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareFileReq) ProtoMessage() {}

func (x *ShareFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_share_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareFileReq.ProtoReflect.Descriptor instead.
func (*ShareFileReq) Descriptor() ([]byte, []int) {
	return file_http_share_proto_rawDescGZIP(), []int{3}
}

func (x *ShareFileReq) GetExpireValue() int32 {
	if x != nil {
		return x.ExpireValue
	}
	return 0
}

func (x *ShareFileReq) GetExpireStyle() string {
	if x != nil {
		return x.ExpireStyle
	}
	return ""
}

func (x *ShareFileReq) GetRequireAuth() bool {
	if x != nil {
		return x.RequireAuth
	}
	return false
}

type ShareFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ShareData             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareFileResp) Reset() {
	*x = ShareFileResp{}
	mi := &file_http_share_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareFileResp) ProtoMessage() {}

func (x *ShareFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_share_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareFileResp.ProtoReflect.Descriptor instead.
func (*ShareFileResp) Descriptor() ([]byte, []int) {
	return file_http_share_proto_rawDescGZIP(), []int{4}
}

func (x *ShareFileResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ShareFileResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ShareFileResp) GetData() *ShareData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetShareReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareReq) Reset() {
	*x = GetShareReq{}
	mi := &file_http_share_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareReq) ProtoMessage() {}

func (x *GetShareReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_share_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareReq.ProtoReflect.Descriptor instead.
func (*GetShareReq) Descriptor() ([]byte, []int) {
	return file_http_share_proto_rawDescGZIP(), []int{5}
}

func (x *GetShareReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetShareReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetShareResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ShareDetail           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareResp) Reset() {
	*x = GetShareResp{}
	mi := &file_http_share_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareResp) ProtoMessage() {}

func (x *GetShareResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_share_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareResp.ProtoReflect.Descriptor instead.
func (*GetShareResp) Descriptor() ([]byte, []int) {
	return file_http_share_proto_rawDescGZIP(), []int{6}
}

func (x *GetShareResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetShareResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetShareResp) GetData() *ShareDetail {
	if x != nil {
		return x.Data
	}
	return nil
}

type ShareDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      string                 `protobuf:"bytes,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	HasPassword   bool                   `protobuf:"varint,6,opt,name=has_password,json=hasPassword,proto3" json:"has_password,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,7,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareDetail) Reset() {
	*x = ShareDetail{}
	mi := &file_http_share_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareDetail) ProtoMessage() {}

func (x *ShareDetail) ProtoReflect() protoreflect.Message {
	mi := &file_http_share_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareDetail.ProtoReflect.Descriptor instead.
func (*ShareDetail) Descriptor() ([]byte, []int) {
	return file_http_share_proto_rawDescGZIP(), []int{7}
}

func (x *ShareDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShareDetail) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ShareDetail) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ShareDetail) GetFileSize() string {
	if x != nil {
		return x.FileSize
	}
	return ""
}

func (x *ShareDetail) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ShareDetail) GetHasPassword() bool {
	if x != nil {
		return x.HasPassword
	}
	return false
}

func (x *ShareDetail) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

type DownloadFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileReq) Reset() {
	*x = DownloadFileReq{}
	mi := &file_http_share_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileReq) ProtoMessage() {}

func (x *DownloadFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_share_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileReq.ProtoReflect.Descriptor instead.
func (*DownloadFileReq) Descriptor() ([]byte, []int) {
	return file_http_share_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadFileReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DownloadFileReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DownloadFileResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 文件下载使用流式响应，此消息用于 JSON 错误响应
	Code          int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResp) Reset() {
	*x = DownloadFileResp{}
	mi := &file_http_share_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResp) ProtoMessage() {}

func (x *DownloadFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_share_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResp.ProtoReflect.Descriptor instead.
func (*DownloadFileResp) Descriptor() ([]byte, []int) {
	return file_http_share_proto_rawDescGZIP(), []int{9}
}

func (x *DownloadFileResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DownloadFileResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_http_share_proto protoreflect.FileDescriptor

const file_http_share_proto_rawDesc = "" +
	"\n" +
	"\x10http/share.proto\x12\n" +
	"http.share\x1a\rapi/api.proto\"\xcb\x01\n" +
	"\fShareTextReq\x12\x1c\n" +
	"\x04text\x18\x01 \x01(\tB\bʻ\x18\x04textR\x04text\x123\n" +
	"\fexpire_value\x18\x02 \x01(\x05B\x10ʻ\x18\fexpire_valueR\vexpireValue\x123\n" +
	"\fexpire_style\x18\x03 \x01(\tB\x10ʻ\x18\fexpire_styleR\vexpireStyle\x123\n" +
	"\frequire_auth\x18\x04 \x01(\bB\x10ʻ\x18\frequire_authR\vrequireAuth\"\x89\x01\n" +
	"\rShareTextResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x123\n" +
	"\x04data\x18\x03 \x01(\v2\x15.http.share.ShareDataB\bʻ\x18\x04dataR\x04data\"D\n" +
	"\tShareData\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\tB\bʻ\x18\x04codeR\x04code\x12\x19\n" +
	"\x03url\x18\x02 \x01(\tB\aʻ\x18\x03urlR\x03url\"\xad\x01\n" +
	"\fShareFileReq\x123\n" +
	"\fexpire_value\x18\x01 \x01(\x05B\x10\xe2\xbb\x18\fexpire_valueR\vexpireValue\x123\n" +
	"\fexpire_style\x18\x02 \x01(\tB\x10\xe2\xbb\x18\fexpire_styleR\vexpireStyle\x123\n" +
	"\frequire_auth\x18\x03 \x01(\bB\x10\xe2\xbb\x18\frequire_authR\vrequireAuth\"\x89\x01\n" +
	"\rShareFileResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x123\n" +
	"\x04data\x18\x03 \x01(\v2\x15.http.share.ShareDataB\bʻ\x18\x04dataR\x04data\"U\n" +
	"\vGetShareReq\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\tB\bһ\x18\x04codeR\x04code\x12(\n" +
	"\bpassword\x18\x02 \x01(\tB\f\xb2\xbb\x18\bpasswordR\bpassword\"\x8a\x01\n" +
	"\fGetShareResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x125\n" +
	"\x04data\x18\x03 \x01(\v2\x17.http.share.ShareDetailB\bʻ\x18\x04dataR\x04data\"\xa3\x02\n" +
	"\vShareDetail\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\tB\bʻ\x18\x04codeR\x04code\x12\x1c\n" +
	"\x04text\x18\x02 \x01(\tB\bʻ\x18\x04textR\x04text\x12*\n" +
	"\tfile_name\x18\x03 \x01(\tB\rʻ\x18\tfile_nameR\bfileName\x12*\n" +
	"\tfile_size\x18\x04 \x01(\tB\rʻ\x18\tfile_sizeR\bfileSize\x12\x19\n" +
	"\x03url\x18\x05 \x01(\tB\aʻ\x18\x03urlR\x03url\x123\n" +
	"\fhas_password\x18\x06 \x01(\bB\x10ʻ\x18\fhas_passwordR\vhasPassword\x120\n" +
	"\vexpire_time\x18\a \x01(\tB\x0fʻ\x18\vexpire_timeR\n" +
	"expireTime\"Y\n" +
	"\x0fDownloadFileReq\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\tB\b\xb2\xbb\x18\x04codeR\x04code\x12(\n" +
	"\bpassword\x18\x02 \x01(\tB\f\xb2\xbb\x18\bpasswordR\bpassword\"W\n" +
	"\x10DownloadFileResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage2\xe9\x02\n" +
	"\fShareService\x12R\n" +
	"\tShareText\x12\x18.http.share.ShareTextReq\x1a\x19.http.share.ShareTextResp\"\x10\xd2\xc1\x18\f/share/text/\x12R\n" +
	"\tShareFile\x12\x18.http.share.ShareFileReq\x1a\x19.http.share.ShareFileResp\"\x10\xd2\xc1\x18\f/share/file/\x12Q\n" +
	"\bGetShare\x12\x17.http.share.GetShareReq\x1a\x18.http.share.GetShareResp\"\x12\xca\xc1\x18\x0e/share/select/\x12^\n" +
	"\fDownloadFile\x12\x1b.http.share.DownloadFileReq\x1a\x1c.http.share.DownloadFileResp\"\x13\xca\xc1\x18\x0f/share/downloadB3Z1github.com/zy84338719/fileCodeBox/biz/model/shareb\x06proto3"

var (
	file_http_share_proto_rawDescOnce sync.Once
	file_http_share_proto_rawDescData []byte
)

func file_http_share_proto_rawDescGZIP() []byte {
	file_http_share_proto_rawDescOnce.Do(func() {
		file_http_share_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_http_share_proto_rawDesc), len(file_http_share_proto_rawDesc)))
	})
	return file_http_share_proto_rawDescData
}

var file_http_share_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_http_share_proto_goTypes = []any{
	(*ShareTextReq)(nil),     // 0: http.share.ShareTextReq
	(*ShareTextResp)(nil),    // 1: http.share.ShareTextResp
	(*ShareData)(nil),        // 2: http.share.ShareData
	(*ShareFileReq)(nil),     // 3: http.share.ShareFileReq
	(*ShareFileResp)(nil),    // 4: http.share.ShareFileResp
	(*GetShareReq)(nil),      // 5: http.share.GetShareReq
	(*GetShareResp)(nil),     // 6: http.share.GetShareResp
	(*ShareDetail)(nil),      // 7: http.share.ShareDetail
	(*DownloadFileReq)(nil),  // 8: http.share.DownloadFileReq
	(*DownloadFileResp)(nil), // 9: http.share.DownloadFileResp
}
var file_http_share_proto_depIdxs = []int32{
	2, // 0: http.share.ShareTextResp.data:type_name -> http.share.ShareData
	2, // 1: http.share.ShareFileResp.data:type_name -> http.share.ShareData
	7, // 2: http.share.GetShareResp.data:type_name -> http.share.ShareDetail
	0, // 3: http.share.ShareService.ShareText:input_type -> http.share.ShareTextReq
	3, // 4: http.share.ShareService.ShareFile:input_type -> http.share.ShareFileReq
	5, // 5: http.share.ShareService.GetShare:input_type -> http.share.GetShareReq
	8, // 6: http.share.ShareService.DownloadFile:input_type -> http.share.DownloadFileReq
	1, // 7: http.share.ShareService.ShareText:output_type -> http.share.ShareTextResp
	4, // 8: http.share.ShareService.ShareFile:output_type -> http.share.ShareFileResp
	6, // 9: http.share.ShareService.GetShare:output_type -> http.share.GetShareResp
	9, // 10: http.share.ShareService.DownloadFile:output_type -> http.share.DownloadFileResp
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_http_share_proto_init() }
func file_http_share_proto_init() {
	if File_http_share_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_share_proto_rawDesc), len(file_http_share_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_http_share_proto_goTypes,
		DependencyIndexes: file_http_share_proto_depIdxs,
		MessageInfos:      file_http_share_proto_msgTypes,
	}.Build()
	File_http_share_proto = out.File
	file_http_share_proto_goTypes = nil
	file_http_share_proto_depIdxs = nil
}
