// Code generated by hertz generator.

package share

import (
	"context"
	"fmt"
	"html"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	sharemodel "github.com/zy84338719/fileCodeBox/biz/model/share"
	shareService "github.com/zy84338719/fileCodeBox/internal/app/share"
	"github.com/zy84338719/fileCodeBox/internal/pkg/utils"
	"github.com/zy84338719/fileCodeBox/internal/storage"
	"github.com/google/uuid"
)

var shareSvc *shareService.Service
var storageSvc storage.StorageInterface

// 配置常量（应从配置读取，这里使用默认值）
const (
	defaultMaxUploadSize = 10485760 // 10MB
	defaultStoragePath   = "./data/uploads"
	defaultBaseURL       = "http://localhost:12345"
)

func getStorageService() storage.StorageInterface {
	if storageSvc == nil {
		storageSvc = storage.NewStorageService(&storage.StorageConfig{
			Type:     storage.StorageTypeLocal,
			DataPath: defaultStoragePath,
			BaseURL:  defaultBaseURL,
		})
	}
	return storageSvc
}

func getShareService() *shareService.Service {
	if shareSvc == nil {
		shareSvc = shareService.NewService(defaultBaseURL, getStorageService())
	}
	return shareSvc
}

// ShareText .
// @router /share/text/ [POST]
func ShareText(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sharemodel.ShareTextReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": err.Error(),
		})
		return
	}

	// 空文本验证：拒绝空文本或只包含空白字符的文本
	if strings.TrimSpace(req.Text) == "" {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": "分享内容不能为空",
		})
		return
	}

	// XSS 防护：对文本内容进行 HTML 转义
	safeText := html.EscapeString(req.Text)

	// 获取用户ID（如果有）
	var userID *uint
	if uid, exists := c.Get("user_id"); exists {
		if uidUint, ok := uid.(uint); ok {
			userID = &uidUint
		}
	}

	// 获取客户端 IP
	ownerIP := c.ClientIP()

	// 调用 service（使用转义后的安全文本）
	result, err := getShareService().ShareTextWithAuth(
		ctx,
		safeText,
		int(req.ExpireValue),
		req.ExpireStyle,
		userID,
		ownerIP,
	)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": err.Error(),
		})
		return
	}

	resp := &sharemodel.ShareTextResp{
		Code:    200,
		Message: "分享成功",
		Data: &sharemodel.ShareData{
			Code: result.Code,
			Url:  result.FullShareURL,
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// ShareFile .
// @router /share/file/ [POST]
func ShareFile(ctx context.Context, c *app.RequestContext) {
	// 1. 解析表单参数
	expireValueStr := c.DefaultPostForm("expire_value", "1")
	expireStyle := c.DefaultPostForm("expire_style", "day")
	requireAuth := c.DefaultPostForm("require_auth", "false") == "true"
	password := c.DefaultPostForm("password", "")

	expireValue, err := strconv.Atoi(expireValueStr)
	if err != nil {
		expireValue = 1
	}

	// 2. 获取上传文件
	file, err := c.FormFile("file")
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": "请上传文件",
		})
		return
	}

	// 3. 检查文件大小
	if file.Size > defaultMaxUploadSize {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": fmt.Sprintf("文件大小超过限制（最大 %d MB）", defaultMaxUploadSize/1024/1024),
		})
		return
	}

	// 4. 生成唯一文件名
	originalFilename := file.Filename
	fileExt := filepath.Ext(originalFilename)
	uuidFileName := uuid.New().String() + fileExt

	// 5. 生成存储路径（按日期分目录）
	now := time.Now()
	relativePath := filepath.Join(
		"uploads",
		now.Format("2006"),
		now.Format("01"),
		now.Format("02"),
	)
	savePath := filepath.Join(relativePath, uuidFileName)

	// 6. 保存文件到存储
	storageSvc := getStorageService()
	result, err := storageSvc.SaveFile(ctx, file, savePath)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": fmt.Sprintf("文件保存失败: %v", err),
		})
		return
	}

	// 7. 计算过期时间
	expireTime := utils.CalculateExpireTime(expireValue, expireStyle)
	expireCount := utils.CalculateExpireCount(expireStyle, expireValue)

	// 8. 获取用户ID（如果有）
	var userID *uint
	if uid, exists := c.Get("user_id"); exists {
		if uidUint, ok := uid.(uint); ok {
			userID = &uidUint
		}
	}

	// 9. 获取客户端 IP
	ownerIP := c.ClientIP()

	// 10. 确定上传类型
	uploadType := "anonymous"
	if userID != nil {
		uploadType = "authenticated"
	}

	// 11. 构建分享请求
	shareReq := &shareService.ShareFileReq{
		FilePath:     result.FilePath,
		Size:         result.FileSize,
		Text:         originalFilename, // 存储原始文件名
		ExpiredAt:    expireTime,
		ExpiredCount: expireCount,
		RequireAuth:  requireAuth,
		UserID:       userID,
		UploadType:   uploadType,
		OwnerIP:      ownerIP,
		FileHash:     result.FileHash,
	}

	// 12. 调用 service 创建分享记录
	shareResult, err := getShareService().ShareFile(ctx, shareReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": fmt.Sprintf("创建分享记录失败: %v", err),
		})
		return
	}

	// 13. 构建响应
	fullShareURL := fmt.Sprintf("%s/share/%s", defaultBaseURL, shareResult.Code)

	resp := &sharemodel.ShareFileResp{
		Code:    200,
		Message: "文件上传成功",
		Data: &sharemodel.ShareData{
			Code: shareResult.Code,
			Url:  fullShareURL,
		},
	}

	// 保存 password 用于验证（如果需要）
	_ = password // TODO: 实现密码验证逻辑

	c.JSON(consts.StatusOK, resp)
}

// GetUserShares 获取用户的分享列表
// @router /share/user [GET]
func GetUserShares(ctx context.Context, c *app.RequestContext) {
	// 获取用户ID（需要登录）
	userIDVal, exists := c.Get("user_id")
	if !exists {
		c.JSON(consts.StatusUnauthorized, map[string]interface{}{
			"code":    401,
			"message": "请先登录",
		})
		return
	}

	userID, ok := userIDVal.(uint)
	if !ok {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "用户ID格式错误",
		})
		return
	}

	// 获取分页参数
	page := 1
	pageSize := 10
	if p := c.Query("page"); p != "" {
		fmt.Sscanf(p, "%d", &page)
	}
	if ps := c.Query("page_size"); ps != "" {
		fmt.Sscanf(ps, "%d", &pageSize)
	}

	// 调用 service
	files, total, err := getShareService().GetFilesByUserID(ctx, userID, page, pageSize)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": err.Error(),
		})
		return
	}

	// 转换为响应格式
	items := make([]map[string]interface{}, len(files))
	for i, f := range files {
		items[i] = map[string]interface{}{
			"code":           f.Code,
			"filename":       f.UUIDFileName,
			"file_size":      f.Size,
			"content_type":   f.UploadType,
			"download_count": f.UsedCount,
			"created_at":     f.CreatedAt.Format("2006-01-02 15:04:05"),
		}
		if f.ExpiredAt != nil {
			items[i]["expire_time"] = f.ExpiredAt.Format("2006-01-02 15:04:05")
		}
	}

	c.JSON(consts.StatusOK, map[string]interface{}{
		"code":    200,
		"message": "获取成功",
		"data": map[string]interface{}{
			"items":    items,
			"total":    total,
			"page":     page,
			"page_size": pageSize,
		},
	})
}

// DeleteShare 删除分享
// @router /share/:code [DELETE]
func DeleteShare(ctx context.Context, c *app.RequestContext) {
	// 获取用户ID（需要登录）
	userIDVal, exists := c.Get("user_id")
	if !exists {
		c.JSON(consts.StatusUnauthorized, map[string]interface{}{
			"code":    401,
			"message": "请先登录",
		})
		return
	}

	userID, ok := userIDVal.(uint)
	if !ok {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "用户ID格式错误",
		})
		return
	}

	code := c.Param("code")
	if code == "" {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": "请提供分享码",
		})
		return
	}

	// 调用 service 删除分享
	err := getShareService().DeleteFileByCode(ctx, code, userID)
	if err != nil {
		// 根据错误类型返回不同的状态码
		errMsg := err.Error()
		if errMsg == "分享不存在" {
			c.JSON(consts.StatusNotFound, map[string]interface{}{
				"code":    404,
				"message": errMsg,
			})
			return
		}
		if errMsg == "无权限删除此分享" {
			c.JSON(consts.StatusForbidden, map[string]interface{}{
				"code":    403,
				"message": errMsg,
			})
			return
		}

		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": fmt.Sprintf("删除失败: %s", errMsg),
		})
		return
	}

	c.JSON(consts.StatusOK, map[string]interface{}{
		"code":    200,
		"message": "删除成功",
	})
}

// GetShare .
// @router /share/select/ [GET]
func GetShare(ctx context.Context, c *app.RequestContext) {
	code := c.Query("code")
	password := c.Query("password")

	if code == "" {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": "请提供分享码",
		})
		return
	}

	// 获取分享内容
	fileCode, err := getShareService().GetFileByCode(ctx, code)
	if err != nil {
		c.JSON(consts.StatusNotFound, map[string]interface{}{
			"code":    404,
			"message": "分享不存在或已过期",
		})
		return
	}

	// 检查是否需要密码
	if fileCode.RequireAuth && password == "" {
		c.JSON(consts.StatusUnauthorized, map[string]interface{}{
			"code":    401,
			"message": "需要密码",
			"data": map[string]interface{}{
				"has_password": true,
			},
		})
		return
	}

	// TODO: 验证密码

	// 构建响应
	resp := &sharemodel.GetShareResp{
		Code:    200,
		Message: "获取成功",
		Data: &sharemodel.ShareDetail{
			Code:        fileCode.Code,
			Text:        fileCode.Text,
			FileName:    fileCode.UUIDFileName,
			FileSize:    fmt.Sprintf("%d", fileCode.Size),
			Url:         fmt.Sprintf("/download/%s", fileCode.Code),
			HasPassword: fileCode.RequireAuth,
			// ExpireTime:  fileCode.ExpiredAt.Format("2006-01-02 15:04:05"),
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// DownloadFile 下载分享文件
// @router /share/download [GET]
func DownloadFile(ctx context.Context, c *app.RequestContext) {
	code := c.Query("code")
	password := c.Query("password")

	if code == "" {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": "请提供分享码",
		})
		return
	}

	// 获取分享内容并增加使用次数
	fileCode, err := getShareService().GetFileWithUsage(ctx, code, password)
	if err != nil {
		if err.Error() == "需要密码" {
			c.JSON(consts.StatusUnauthorized, map[string]interface{}{
				"code":    401,
				"message": "需要密码",
				"data": map[string]interface{}{
					"has_password": true,
				},
			})
			return
		}
		c.JSON(consts.StatusNotFound, map[string]interface{}{
			"code":    404,
			"message": "分享不存在或已过期",
		})
		return
	}

	// 更新下载次数
	if err := getShareService().UpdateFileUsage(ctx, code); err != nil {
		// 记录错误但不阻止下载
		fmt.Printf("更新下载次数失败: %v\n", err)
	}

	// 如果是文本分享，直接返回文本
	if fileCode.Text != "" {
		c.Header("Content-Type", "text/plain; charset=utf-8")
		c.Header("Content-Disposition", `inline; filename="text.txt"`)
		c.SetBodyString(fileCode.Text)
		return
	}

	// 如果是文件分享，流式返回文件
	filePath := fileCode.GetFilePath()
	if filePath == "" {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "文件路径为空",
		})
		return
	}

	// 获取文件读取器
	reader, fileSize, err := getStorageService().GetFileReader(ctx, filePath)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": fmt.Sprintf("获取文件失败: %v", err),
		})
		return
	}
	defer reader.Close()

	// 设置文件下载头
	fileName := fileCode.UUIDFileName
	if fileName == "" {
		// 向后兼容：如果UUIDFileName为空，则使用Prefix + Suffix
		fileName = fileCode.Prefix + fileCode.Suffix
	}
	c.Header("Content-Type", "application/octet-stream")
	c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, fileName))
	c.Header("Content-Length", fmt.Sprintf("%d", fileSize))

	// 流式传输文件内容
	c.SetBodyStream(reader, int(fileSize))
}
