// Code generated by hertz generator.

package health

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Health 健康检查
func Health(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, map[string]interface{}{
		"code":    200,
		"message": "ok",
	})
}

// Liveness 存活检查
func Liveness(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, map[string]interface{}{
		"code":    200,
		"message": "alive",
	})
}

// Ping ping检查
func Ping(ctx context.Context, c *app.RequestContext) {
	c.String(consts.StatusOK, "pong")
}

// Readiness 就绪检查
func Readiness(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, map[string]interface{}{
		"code":    200,
		"message": "ready",
	})
}

// Version 版本信息
func Version(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, map[string]interface{}{
		"code":    200,
		"message": "v1.0.0",
	})
}
