// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: http/user.proto

package user

import (
	_ "github.com/zy84338719/fileCodeBox/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_http_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserData              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_http_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResp) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_http_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *LoginData             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_http_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResp) GetData() *LoginData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoginData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User          *UserData              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginData) Reset() {
	*x = LoginData{}
	mi := &file_http_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginData) ProtoMessage() {}

func (x *LoginData) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginData.ProtoReflect.Descriptor instead.
func (*LoginData) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginData) GetUser() *UserData {
	if x != nil {
		return x.User
	}
	return nil
}

type UserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoReq) Reset() {
	*x = UserInfoReq{}
	mi := &file_http_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReq) ProtoMessage() {}

func (x *UserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReq.ProtoReflect.Descriptor instead.
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{5}
}

type UserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserData              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResp) Reset() {
	*x = UserInfoResp{}
	mi := &file_http_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResp) ProtoMessage() {}

func (x *UserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResp.ProtoReflect.Descriptor instead.
func (*UserInfoResp) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserInfoResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserInfoResp) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_http_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserData) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserData) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UpdateProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileReq) Reset() {
	*x = UpdateProfileReq{}
	mi := &file_http_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileReq) ProtoMessage() {}

func (x *UpdateProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateProfileReq) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProfileReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfileReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserData              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResp) Reset() {
	*x = UpdateProfileResp{}
	mi := &file_http_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResp) ProtoMessage() {}

func (x *UpdateProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResp.ProtoReflect.Descriptor instead.
func (*UpdateProfileResp) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProfileResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateProfileResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateProfileResp) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChangePasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordReq) Reset() {
	*x = ChangePasswordReq{}
	mi := &file_http_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordReq) ProtoMessage() {}

func (x *ChangePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordReq.ProtoReflect.Descriptor instead.
func (*ChangePasswordReq) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{10}
}

func (x *ChangePasswordReq) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResp) Reset() {
	*x = ChangePasswordResp{}
	mi := &file_http_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResp) ProtoMessage() {}

func (x *ChangePasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResp.ProtoReflect.Descriptor instead.
func (*ChangePasswordResp) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{11}
}

func (x *ChangePasswordResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChangePasswordResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatsReq) Reset() {
	*x = UserStatsReq{}
	mi := &file_http_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsReq) ProtoMessage() {}

func (x *UserStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsReq.ProtoReflect.Descriptor instead.
func (*UserStatsReq) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{12}
}

type UserStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserStats             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatsResp) Reset() {
	*x = UserStatsResp{}
	mi := &file_http_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsResp) ProtoMessage() {}

func (x *UserStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsResp.ProtoReflect.Descriptor instead.
func (*UserStatsResp) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{13}
}

func (x *UserStatsResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserStatsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserStatsResp) GetData() *UserStats {
	if x != nil {
		return x.Data
	}
	return nil
}

type EmptyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	mi := &file_http_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{14}
}

type UserStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalUploads  int64                  `protobuf:"varint,1,opt,name=total_uploads,json=totalUploads,proto3" json:"total_uploads,omitempty"`
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	QuotaUsed     int64                  `protobuf:"varint,3,opt,name=quota_used,json=quotaUsed,proto3" json:"quota_used,omitempty"`
	QuotaLimit    int64                  `protobuf:"varint,4,opt,name=quota_limit,json=quotaLimit,proto3" json:"quota_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStats) Reset() {
	*x = UserStats{}
	mi := &file_http_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStats) ProtoMessage() {}

func (x *UserStats) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStats.ProtoReflect.Descriptor instead.
func (*UserStats) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{15}
}

func (x *UserStats) GetTotalUploads() int64 {
	if x != nil {
		return x.TotalUploads
	}
	return 0
}

func (x *UserStats) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *UserStats) GetQuotaUsed() int64 {
	if x != nil {
		return x.QuotaUsed
	}
	return 0
}

func (x *UserStats) GetQuotaLimit() int64 {
	if x != nil {
		return x.QuotaLimit
	}
	return 0
}

type UserFilesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFilesReq) Reset() {
	*x = UserFilesReq{}
	mi := &file_http_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFilesReq) ProtoMessage() {}

func (x *UserFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFilesReq.ProtoReflect.Descriptor instead.
func (*UserFilesReq) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{16}
}

func (x *UserFilesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserFilesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserFilesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserFileList          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFilesResp) Reset() {
	*x = UserFilesResp{}
	mi := &file_http_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFilesResp) ProtoMessage() {}

func (x *UserFilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFilesResp.ProtoReflect.Descriptor instead.
func (*UserFilesResp) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{17}
}

func (x *UserFilesResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserFilesResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserFilesResp) GetData() *UserFileList {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserFileList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*UserFileItem        `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Pagination    *UserFilePagination    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFileList) Reset() {
	*x = UserFileList{}
	mi := &file_http_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFileList) ProtoMessage() {}

func (x *UserFileList) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFileList.ProtoReflect.Descriptor instead.
func (*UserFileList) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{18}
}

func (x *UserFileList) GetFiles() []*UserFileItem {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *UserFileList) GetPagination() *UserFilePagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UserFileItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix        string                 `protobuf:"bytes,4,opt,name=suffix,proto3" json:"suffix,omitempty"`
	FileName      string                 `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FilePath      string                 `protobuf:"bytes,6,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Size          int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	ExpiredAt     string                 `protobuf:"bytes,8,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	ExpiredCount  int32                  `protobuf:"varint,9,opt,name=expired_count,json=expiredCount,proto3" json:"expired_count,omitempty"`
	UsedCount     int32                  `protobuf:"varint,10,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFileItem) Reset() {
	*x = UserFileItem{}
	mi := &file_http_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFileItem) ProtoMessage() {}

func (x *UserFileItem) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFileItem.ProtoReflect.Descriptor instead.
func (*UserFileItem) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{19}
}

func (x *UserFileItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserFileItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserFileItem) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *UserFileItem) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *UserFileItem) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UserFileItem) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UserFileItem) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UserFileItem) GetExpiredAt() string {
	if x != nil {
		return x.ExpiredAt
	}
	return ""
}

func (x *UserFileItem) GetExpiredCount() int32 {
	if x != nil {
		return x.ExpiredCount
	}
	return 0
}

func (x *UserFileItem) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *UserFileItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserFileItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UserFilePagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	HasNext       bool                   `protobuf:"varint,5,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrev       bool                   `protobuf:"varint,6,opt,name=has_prev,json=hasPrev,proto3" json:"has_prev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFilePagination) Reset() {
	*x = UserFilePagination{}
	mi := &file_http_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFilePagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFilePagination) ProtoMessage() {}

func (x *UserFilePagination) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFilePagination.ProtoReflect.Descriptor instead.
func (*UserFilePagination) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{20}
}

func (x *UserFilePagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserFilePagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *UserFilePagination) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserFilePagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *UserFilePagination) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *UserFilePagination) GetHasPrev() bool {
	if x != nil {
		return x.HasPrev
	}
	return false
}

type APIKeyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	LastUsedAt    string                 `protobuf:"bytes,4,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Revoked       bool                   `protobuf:"varint,7,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyData) Reset() {
	*x = APIKeyData{}
	mi := &file_http_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyData) ProtoMessage() {}

func (x *APIKeyData) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyData.ProtoReflect.Descriptor instead.
func (*APIKeyData) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{21}
}

func (x *APIKeyData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *APIKeyData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKeyData) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *APIKeyData) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

func (x *APIKeyData) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *APIKeyData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *APIKeyData) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type APIKeyListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Keys          []*APIKeyData          `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyListResp) Reset() {
	*x = APIKeyListResp{}
	mi := &file_http_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyListResp) ProtoMessage() {}

func (x *APIKeyListResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyListResp.ProtoReflect.Descriptor instead.
func (*APIKeyListResp) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{22}
}

func (x *APIKeyListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *APIKeyListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *APIKeyListResp) GetKeys() []*APIKeyData {
	if x != nil {
		return x.Keys
	}
	return nil
}

type CreateAPIKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ExpiresInDays int64                  `protobuf:"varint,3,opt,name=expires_in_days,json=expiresInDays,proto3" json:"expires_in_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyReq) Reset() {
	*x = CreateAPIKeyReq{}
	mi := &file_http_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyReq) ProtoMessage() {}

func (x *CreateAPIKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyReq.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyReq) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{23}
}

func (x *CreateAPIKeyReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAPIKeyReq) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *CreateAPIKeyReq) GetExpiresInDays() int64 {
	if x != nil {
		return x.ExpiresInDays
	}
	return 0
}

type CreateAPIKeyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CreateAPIKeyResp_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyResp) Reset() {
	*x = CreateAPIKeyResp{}
	mi := &file_http_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyResp) ProtoMessage() {}

func (x *CreateAPIKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyResp.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyResp) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{24}
}

func (x *CreateAPIKeyResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateAPIKeyResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateAPIKeyResp) GetData() *CreateAPIKeyResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteAPIKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAPIKeyReq) Reset() {
	*x = DeleteAPIKeyReq{}
	mi := &file_http_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAPIKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPIKeyReq) ProtoMessage() {}

func (x *DeleteAPIKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPIKeyReq.ProtoReflect.Descriptor instead.
func (*DeleteAPIKeyReq) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteAPIKeyReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAPIKeyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAPIKeyResp) Reset() {
	*x = DeleteAPIKeyResp{}
	mi := &file_http_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAPIKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPIKeyResp) ProtoMessage() {}

func (x *DeleteAPIKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPIKeyResp.ProtoReflect.Descriptor instead.
func (*DeleteAPIKeyResp) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteAPIKeyResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteAPIKeyResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateAPIKeyResp_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ApiKey        *APIKeyData            `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyResp_Data) Reset() {
	*x = CreateAPIKeyResp_Data{}
	mi := &file_http_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyResp_Data) ProtoMessage() {}

func (x *CreateAPIKeyResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_http_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyResp_Data.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyResp_Data) Descriptor() ([]byte, []int) {
	return file_http_user_proto_rawDescGZIP(), []int{24, 0}
}

func (x *CreateAPIKeyResp_Data) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateAPIKeyResp_Data) GetApiKey() *APIKeyData {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

var File_http_user_proto protoreflect.FileDescriptor

const file_http_user_proto_rawDesc = "" +
	"\n" +
	"\x0fhttp/user.proto\x12\thttp.user\x1a\rapi/api.proto\"\xac\x01\n" +
	"\vRegisterReq\x12(\n" +
	"\busername\x18\x01 \x01(\tB\fʻ\x18\busernameR\busername\x12\x1f\n" +
	"\x05email\x18\x02 \x01(\tB\tʻ\x18\x05emailR\x05email\x12(\n" +
	"\bpassword\x18\x03 \x01(\tB\fʻ\x18\bpasswordR\bpassword\x12(\n" +
	"\bnickname\x18\x04 \x01(\tB\fʻ\x18\bnicknameR\bnickname\"\x86\x01\n" +
	"\fRegisterResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x121\n" +
	"\x04data\x18\x03 \x01(\v2\x13.http.user.UserDataB\bʻ\x18\x04dataR\x04data\"^\n" +
	"\bLoginReq\x12(\n" +
	"\busername\x18\x01 \x01(\tB\fʻ\x18\busernameR\busername\x12(\n" +
	"\bpassword\x18\x02 \x01(\tB\fʻ\x18\bpasswordR\bpassword\"\x84\x01\n" +
	"\tLoginResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x122\n" +
	"\x04data\x18\x03 \x01(\v2\x14.http.user.LoginDataB\bʻ\x18\x04dataR\x04data\"_\n" +
	"\tLoginData\x12\x1f\n" +
	"\x05token\x18\x01 \x01(\tB\tʻ\x18\x05tokenR\x05token\x121\n" +
	"\x04user\x18\x02 \x01(\v2\x13.http.user.UserDataB\bʻ\x18\x04userR\x04user\"\r\n" +
	"\vUserInfoReq\"\x86\x01\n" +
	"\fUserInfoResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x121\n" +
	"\x04data\x18\x03 \x01(\v2\x13.http.user.UserDataB\bʻ\x18\x04dataR\x04data\"\x8e\x02\n" +
	"\bUserData\x12\x16\n" +
	"\x02id\x18\x01 \x01(\rB\x06ʻ\x18\x02idR\x02id\x12(\n" +
	"\busername\x18\x02 \x01(\tB\fʻ\x18\busernameR\busername\x12\x1f\n" +
	"\x05email\x18\x03 \x01(\tB\tʻ\x18\x05emailR\x05email\x12(\n" +
	"\bnickname\x18\x04 \x01(\tB\fʻ\x18\bnicknameR\bnickname\x12\"\n" +
	"\x06avatar\x18\x05 \x01(\tB\n" +
	"ʻ\x18\x06avatarR\x06avatar\x12\"\n" +
	"\x06status\x18\x06 \x01(\x05B\n" +
	"ʻ\x18\x06statusR\x06status\x12-\n" +
	"\n" +
	"created_at\x18\a \x01(\tB\x0eʻ\x18\n" +
	"created_atR\tcreatedAt\"`\n" +
	"\x10UpdateProfileReq\x12(\n" +
	"\bnickname\x18\x01 \x01(\tB\fʻ\x18\bnicknameR\bnickname\x12\"\n" +
	"\x06avatar\x18\x02 \x01(\tB\n" +
	"ʻ\x18\x06avatarR\x06avatar\"\x8b\x01\n" +
	"\x11UpdateProfileResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x121\n" +
	"\x04data\x18\x03 \x01(\v2\x13.http.user.UserDataB\bʻ\x18\x04dataR\x04data\"}\n" +
	"\x11ChangePasswordReq\x123\n" +
	"\fold_password\x18\x01 \x01(\tB\x10ʻ\x18\fold_passwordR\voldPassword\x123\n" +
	"\fnew_password\x18\x02 \x01(\tB\x10ʻ\x18\fnew_passwordR\vnewPassword\"Y\n" +
	"\x12ChangePasswordResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\"\x0e\n" +
	"\fUserStatsReq\"\x88\x01\n" +
	"\rUserStatsResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x122\n" +
	"\x04data\x18\x03 \x01(\v2\x14.http.user.UserStatsB\bʻ\x18\x04dataR\x04data\"\n" +
	"\n" +
	"\bEmptyReq\"\xd3\x01\n" +
	"\tUserStats\x126\n" +
	"\rtotal_uploads\x18\x01 \x01(\x03B\x11ʻ\x18\rtotal_uploadsR\ftotalUploads\x12-\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03B\x0eʻ\x18\n" +
	"total_sizeR\ttotalSize\x12-\n" +
	"\n" +
	"quota_used\x18\x03 \x01(\x03B\x0eʻ\x18\n" +
	"quota_usedR\tquotaUsed\x120\n" +
	"\vquota_limit\x18\x04 \x01(\x03B\x0fʻ\x18\vquota_limitR\n" +
	"quotaLimit\"X\n" +
	"\fUserFilesReq\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\x05B\b\xb2\xbb\x18\x04pageR\x04page\x12*\n" +
	"\tpage_size\x18\x02 \x01(\x05B\r\xb2\xbb\x18\tpage_sizeR\bpageSize\"\x8b\x01\n" +
	"\rUserFilesResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x125\n" +
	"\x04data\x18\x03 \x01(\v2\x17.http.user.UserFileListB\bʻ\x18\x04dataR\x04data\"\x97\x01\n" +
	"\fUserFileList\x128\n" +
	"\x05files\x18\x01 \x03(\v2\x17.http.user.UserFileItemB\tʻ\x18\x05filesR\x05files\x12M\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.http.user.UserFilePaginationB\x0eʻ\x18\n" +
	"paginationR\n" +
	"pagination\"\xf6\x03\n" +
	"\fUserFileItem\x12\x16\n" +
	"\x02id\x18\x01 \x01(\rB\x06ʻ\x18\x02idR\x02id\x12\x1c\n" +
	"\x04code\x18\x02 \x01(\tB\bʻ\x18\x04codeR\x04code\x12\"\n" +
	"\x06prefix\x18\x03 \x01(\tB\n" +
	"ʻ\x18\x06prefixR\x06prefix\x12\"\n" +
	"\x06suffix\x18\x04 \x01(\tB\n" +
	"ʻ\x18\x06suffixR\x06suffix\x12*\n" +
	"\tfile_name\x18\x05 \x01(\tB\rʻ\x18\tfile_nameR\bfileName\x12*\n" +
	"\tfile_path\x18\x06 \x01(\tB\rʻ\x18\tfile_pathR\bfilePath\x12\x1c\n" +
	"\x04size\x18\a \x01(\x03B\bʻ\x18\x04sizeR\x04size\x12-\n" +
	"\n" +
	"expired_at\x18\b \x01(\tB\x0eʻ\x18\n" +
	"expired_atR\texpiredAt\x126\n" +
	"\rexpired_count\x18\t \x01(\x05B\x11ʻ\x18\rexpired_countR\fexpiredCount\x12-\n" +
	"\n" +
	"used_count\x18\n" +
	" \x01(\x05B\x0eʻ\x18\n" +
	"used_countR\tusedCount\x12-\n" +
	"\n" +
	"created_at\x18\v \x01(\tB\x0eʻ\x18\n" +
	"created_atR\tcreatedAt\x12-\n" +
	"\n" +
	"updated_at\x18\f \x01(\tB\x0eʻ\x18\n" +
	"updated_atR\tupdatedAt\"\x83\x02\n" +
	"\x12UserFilePagination\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\x05B\bʻ\x18\x04pageR\x04page\x12*\n" +
	"\tpage_size\x18\x02 \x01(\x05B\rʻ\x18\tpage_sizeR\bpageSize\x12\x1f\n" +
	"\x05total\x18\x03 \x01(\x03B\tʻ\x18\x05totalR\x05total\x120\n" +
	"\vtotal_pages\x18\x04 \x01(\x05B\x0fʻ\x18\vtotal_pagesR\n" +
	"totalPages\x12'\n" +
	"\bhas_next\x18\x05 \x01(\bB\fʻ\x18\bhas_nextR\ahasNext\x12'\n" +
	"\bhas_prev\x18\x06 \x01(\bB\fʻ\x18\bhas_prevR\ahasPrev\"\x9f\x02\n" +
	"\n" +
	"APIKeyData\x12\x16\n" +
	"\x02id\x18\x01 \x01(\rB\x06ʻ\x18\x02idR\x02id\x12\x1c\n" +
	"\x04name\x18\x02 \x01(\tB\bʻ\x18\x04nameR\x04name\x12\"\n" +
	"\x06prefix\x18\x03 \x01(\tB\n" +
	"ʻ\x18\x06prefixR\x06prefix\x122\n" +
	"\flast_used_at\x18\x04 \x01(\tB\x10ʻ\x18\flast_used_atR\n" +
	"lastUsedAt\x12-\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tB\x0eʻ\x18\n" +
	"expires_atR\texpiresAt\x12-\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tB\x0eʻ\x18\n" +
	"created_atR\tcreatedAt\x12%\n" +
	"\arevoked\x18\a \x01(\bB\vʻ\x18\arevokedR\arevoked\"\x8a\x01\n" +
	"\x0eAPIKeyListResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x123\n" +
	"\x04keys\x18\x03 \x03(\v2\x15.http.user.APIKeyDataB\bʻ\x18\x04keysR\x04keys\"\x9b\x01\n" +
	"\x0fCreateAPIKeyReq\x12\x1c\n" +
	"\x04name\x18\x01 \x01(\tB\bʻ\x18\x04nameR\x04name\x12-\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tB\x0eʻ\x18\n" +
	"expires_atR\texpiresAt\x12;\n" +
	"\x0fexpires_in_days\x18\x03 \x01(\x03B\x13ʻ\x18\x0fexpires_in_daysR\rexpiresInDays\"\xf7\x01\n" +
	"\x10CreateAPIKeyResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\x12>\n" +
	"\x04data\x18\x03 \x01(\v2 .http.user.CreateAPIKeyResp.DataB\bʻ\x18\x04dataR\x04data\x1a^\n" +
	"\x04Data\x12\x19\n" +
	"\x03key\x18\x01 \x01(\tB\aʻ\x18\x03keyR\x03key\x12;\n" +
	"\aapi_key\x18\x02 \x01(\v2\x15.http.user.APIKeyDataB\vʻ\x18\aapi_keyR\x06apiKey\")\n" +
	"\x0fDeleteAPIKeyReq\x12\x16\n" +
	"\x02id\x18\x01 \x01(\rB\x06һ\x18\x02idR\x02id\"W\n" +
	"\x10DeleteAPIKeyResp\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\x05B\bʻ\x18\x04codeR\x04code\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage2\xec\x06\n" +
	"\vUserService\x12O\n" +
	"\bRegister\x12\x16.http.user.RegisterReq\x1a\x17.http.user.RegisterResp\"\x12\xd2\xc1\x18\x0e/user/register\x12C\n" +
	"\x05Login\x12\x13.http.user.LoginReq\x1a\x14.http.user.LoginResp\"\x0f\xd2\xc1\x18\v/user/login\x12K\n" +
	"\bUserInfo\x12\x16.http.user.UserInfoReq\x1a\x17.http.user.UserInfoResp\"\x0e\xca\xc1\x18\n" +
	"/user/info\x12]\n" +
	"\rUpdateProfile\x12\x1b.http.user.UpdateProfileReq\x1a\x1c.http.user.UpdateProfileResp\"\x11\xda\xc1\x18\r/user/profile\x12h\n" +
	"\x0eChangePassword\x12\x1c.http.user.ChangePasswordReq\x1a\x1d.http.user.ChangePasswordResp\"\x19\xd2\xc1\x18\x15/user/change-password\x12O\n" +
	"\tUserStats\x12\x17.http.user.UserStatsReq\x1a\x18.http.user.UserStatsResp\"\x0f\xca\xc1\x18\v/user/stats\x12O\n" +
	"\tUserFiles\x12\x17.http.user.UserFilesReq\x1a\x18.http.user.UserFilesResp\"\x0f\xca\xc1\x18\v/user/files\x12Q\n" +
	"\vListAPIKeys\x12\x13.http.user.EmptyReq\x1a\x19.http.user.APIKeyListResp\"\x12\xca\xc1\x18\x0e/user/api-keys\x12[\n" +
	"\fCreateAPIKey\x12\x1a.http.user.CreateAPIKeyReq\x1a\x1b.http.user.CreateAPIKeyResp\"\x12\xd2\xc1\x18\x0e/user/api-keys\x12_\n" +
	"\fDeleteAPIKey\x12\x1a.http.user.DeleteAPIKeyReq\x1a\x1b.http.user.DeleteAPIKeyResp\"\x16\xe2\xc1\x18\x12/user/api-keys/:idB2Z0github.com/zy84338719/fileCodeBox/biz/model/userb\x06proto3"

var (
	file_http_user_proto_rawDescOnce sync.Once
	file_http_user_proto_rawDescData []byte
)

func file_http_user_proto_rawDescGZIP() []byte {
	file_http_user_proto_rawDescOnce.Do(func() {
		file_http_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_http_user_proto_rawDesc), len(file_http_user_proto_rawDesc)))
	})
	return file_http_user_proto_rawDescData
}

var file_http_user_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_http_user_proto_goTypes = []any{
	(*RegisterReq)(nil),           // 0: http.user.RegisterReq
	(*RegisterResp)(nil),          // 1: http.user.RegisterResp
	(*LoginReq)(nil),              // 2: http.user.LoginReq
	(*LoginResp)(nil),             // 3: http.user.LoginResp
	(*LoginData)(nil),             // 4: http.user.LoginData
	(*UserInfoReq)(nil),           // 5: http.user.UserInfoReq
	(*UserInfoResp)(nil),          // 6: http.user.UserInfoResp
	(*UserData)(nil),              // 7: http.user.UserData
	(*UpdateProfileReq)(nil),      // 8: http.user.UpdateProfileReq
	(*UpdateProfileResp)(nil),     // 9: http.user.UpdateProfileResp
	(*ChangePasswordReq)(nil),     // 10: http.user.ChangePasswordReq
	(*ChangePasswordResp)(nil),    // 11: http.user.ChangePasswordResp
	(*UserStatsReq)(nil),          // 12: http.user.UserStatsReq
	(*UserStatsResp)(nil),         // 13: http.user.UserStatsResp
	(*EmptyReq)(nil),              // 14: http.user.EmptyReq
	(*UserStats)(nil),             // 15: http.user.UserStats
	(*UserFilesReq)(nil),          // 16: http.user.UserFilesReq
	(*UserFilesResp)(nil),         // 17: http.user.UserFilesResp
	(*UserFileList)(nil),          // 18: http.user.UserFileList
	(*UserFileItem)(nil),          // 19: http.user.UserFileItem
	(*UserFilePagination)(nil),    // 20: http.user.UserFilePagination
	(*APIKeyData)(nil),            // 21: http.user.APIKeyData
	(*APIKeyListResp)(nil),        // 22: http.user.APIKeyListResp
	(*CreateAPIKeyReq)(nil),       // 23: http.user.CreateAPIKeyReq
	(*CreateAPIKeyResp)(nil),      // 24: http.user.CreateAPIKeyResp
	(*DeleteAPIKeyReq)(nil),       // 25: http.user.DeleteAPIKeyReq
	(*DeleteAPIKeyResp)(nil),      // 26: http.user.DeleteAPIKeyResp
	(*CreateAPIKeyResp_Data)(nil), // 27: http.user.CreateAPIKeyResp.Data
}
var file_http_user_proto_depIdxs = []int32{
	7,  // 0: http.user.RegisterResp.data:type_name -> http.user.UserData
	4,  // 1: http.user.LoginResp.data:type_name -> http.user.LoginData
	7,  // 2: http.user.LoginData.user:type_name -> http.user.UserData
	7,  // 3: http.user.UserInfoResp.data:type_name -> http.user.UserData
	7,  // 4: http.user.UpdateProfileResp.data:type_name -> http.user.UserData
	15, // 5: http.user.UserStatsResp.data:type_name -> http.user.UserStats
	18, // 6: http.user.UserFilesResp.data:type_name -> http.user.UserFileList
	19, // 7: http.user.UserFileList.files:type_name -> http.user.UserFileItem
	20, // 8: http.user.UserFileList.pagination:type_name -> http.user.UserFilePagination
	21, // 9: http.user.APIKeyListResp.keys:type_name -> http.user.APIKeyData
	27, // 10: http.user.CreateAPIKeyResp.data:type_name -> http.user.CreateAPIKeyResp.Data
	21, // 11: http.user.CreateAPIKeyResp.Data.api_key:type_name -> http.user.APIKeyData
	0,  // 12: http.user.UserService.Register:input_type -> http.user.RegisterReq
	2,  // 13: http.user.UserService.Login:input_type -> http.user.LoginReq
	5,  // 14: http.user.UserService.UserInfo:input_type -> http.user.UserInfoReq
	8,  // 15: http.user.UserService.UpdateProfile:input_type -> http.user.UpdateProfileReq
	10, // 16: http.user.UserService.ChangePassword:input_type -> http.user.ChangePasswordReq
	12, // 17: http.user.UserService.UserStats:input_type -> http.user.UserStatsReq
	16, // 18: http.user.UserService.UserFiles:input_type -> http.user.UserFilesReq
	14, // 19: http.user.UserService.ListAPIKeys:input_type -> http.user.EmptyReq
	23, // 20: http.user.UserService.CreateAPIKey:input_type -> http.user.CreateAPIKeyReq
	25, // 21: http.user.UserService.DeleteAPIKey:input_type -> http.user.DeleteAPIKeyReq
	1,  // 22: http.user.UserService.Register:output_type -> http.user.RegisterResp
	3,  // 23: http.user.UserService.Login:output_type -> http.user.LoginResp
	6,  // 24: http.user.UserService.UserInfo:output_type -> http.user.UserInfoResp
	9,  // 25: http.user.UserService.UpdateProfile:output_type -> http.user.UpdateProfileResp
	11, // 26: http.user.UserService.ChangePassword:output_type -> http.user.ChangePasswordResp
	13, // 27: http.user.UserService.UserStats:output_type -> http.user.UserStatsResp
	17, // 28: http.user.UserService.UserFiles:output_type -> http.user.UserFilesResp
	22, // 29: http.user.UserService.ListAPIKeys:output_type -> http.user.APIKeyListResp
	24, // 30: http.user.UserService.CreateAPIKey:output_type -> http.user.CreateAPIKeyResp
	26, // 31: http.user.UserService.DeleteAPIKey:output_type -> http.user.DeleteAPIKeyResp
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_http_user_proto_init() }
func file_http_user_proto_init() {
	if File_http_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_user_proto_rawDesc), len(file_http_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_http_user_proto_goTypes,
		DependencyIndexes: file_http_user_proto_depIdxs,
		MessageInfos:      file_http_user_proto_msgTypes,
	}.Build()
	File_http_user_proto = out.File
	file_http_user_proto_goTypes = nil
	file_http_user_proto_depIdxs = nil
}
