// Code generated by hertz generator.

package share

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	share "github.com/zy84338719/fileCodeBox/biz/model/share"
)

// ShareText .
// @router /share/text/ [POST]
func ShareText(ctx context.Context, c *app.RequestContext) {
	var err error
	var req share.ShareTextReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(share.ShareTextResp)

	c.JSON(consts.StatusOK, resp)
}

// ShareFile .
// @router /share/file/ [POST]
func ShareFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req share.ShareFileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(share.ShareFileResp)

	c.JSON(consts.StatusOK, resp)
}

// GetShare .
// @router /share/select/ [GET]
func GetShare(ctx context.Context, c *app.RequestContext) {
	var err error
	var req share.GetShareReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(share.GetShareResp)

	c.JSON(consts.StatusOK, resp)
}

// DownloadFile .
// @router /share/download [GET]
func DownloadFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req share.DownloadFileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(share.DownloadFileResp)

	c.JSON(consts.StatusOK, resp)
}
