// Code generated by hertz generator.

package storage

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _storageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstorageinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatestorageconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _switchstorageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _testMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _teststorageconnectionMw() []app.HandlerFunc {
	// your code...
	return nil
}
