// Package docs Code generated by swaggo/swag at
// 2025-01-11 20:00:00.000000 +0800 CST m=+0.021639876.
// This file was generated by swaggo/swag
// Enhanced version with comprehensive API documentation

package docs

import (
	"github.com/swaggo/swag"
)

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/zy84338719/filecodebox/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        },
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        }
    },
    "tags": [
        {
            "name": "系统",
            "description": "系统相关接口"
        },
        {
            "name": "分享",
            "description": "文件和文本分享接口"
        },
        {
            "name": "分片上传",
            "description": "大文件分片上传接口"
        },
        {
            "name": "用户",
            "description": "用户认证和管理接口"
        },
        {
            "name": "管理员",
            "description": "管理员接口"
        },
        {
            "name": "存储",
            "description": "存储管理接口"
        }
    ],
    "paths": {
        "/health": {
            "get": {
                "tags": [
                    "系统"
                ],
                "summary": "健康检查",
                "description": "检查服务器健康状态",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "健康状态信息",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/config": {
            "get": {
                "tags": [
                    "系统"
                ],
                "summary": "获取系统配置",
                "description": "获取前端所需的系统配置信息",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "系统配置信息",
                        "schema": {
                            "$ref": "#/definitions/models.SystemConfig"
                        }
                    }
                }
            }
        },
        "/share/text/": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "分享"
                ],
                "summary": "分享文本内容",
                "description": "分享文本内容并生成分享代码",
                "consumes": [
                    "multipart/form-data",
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "文本内容",
                        "name": "text",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "过期值",
                        "name": "expire_value",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            "minute",
                            "hour",
                            "day",
                            "week",
                            "month",
                            "year",
                            "forever"
                        ],
                        "type": "string",
                        "default": "day",
                        "description": "过期样式",
                        "name": "expire_style",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "是否需要认证",
                        "name": "require_auth",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分享成功",
                        "schema": {
                            "$ref": "#/definitions/models.ShareResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "认证失败",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/share/file/": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "分享"
                ],
                "summary": "分享文件",
                "description": "上传并分享文件，生成分享代码",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "file",
                        "description": "要分享的文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "过期值",
                        "name": "expire_value",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            "minute",
                            "hour",
                            "day",
                            "week",
                            "month",
                            "year",
                            "forever"
                        ],
                        "type": "string",
                        "default": "day",
                        "description": "过期样式",
                        "name": "expire_style",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "是否需要认证",
                        "name": "require_auth",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分享成功",
                        "schema": {
                            "$ref": "#/definitions/models.ShareResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "413": {
                        "description": "文件过大",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/share/select/": {
            "get": {
                "tags": [
                    "分享"
                ],
                "summary": "获取分享信息",
                "description": "根据分享代码获取文件或文本的详细信息",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享代码",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分享信息",
                        "schema": {
                            "$ref": "#/definitions/models.ShareInfo"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "分享代码不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "410": {
                        "description": "分享已过期",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "分享"
                ],
                "summary": "获取分享信息",
                "description": "根据分享代码获取文件或文本的详细信息（POST方式）",
                "consumes": [
                    "application/json",
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享代码",
                        "name": "code",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分享信息",
                        "schema": {
                            "$ref": "#/definitions/models.ShareInfo"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "分享代码不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/share/download": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "分享"
                ],
                "summary": "下载分享文件",
                "description": "根据分享代码下载文件或获取文本内容",
                "produces": [
                    "application/octet-stream",
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享代码",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件下载或文本内容"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "需要认证",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "分享代码不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "410": {
                        "description": "分享已过期",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/chunk/upload/init/": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "分片上传"
                ],
                "summary": "初始化分片上传",
                "description": "初始化文件分片上传，返回上传ID和分片信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "上传初始化参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InitUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "初始化成功",
                        "schema": {
                            "$ref": "#/definitions/models.InitUploadResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "413": {
                        "description": "文件过大",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/chunk/upload/chunk/{upload_id}/{chunk_index}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "分片上传"
                ],
                "summary": "上传文件分片",
                "description": "上传指定索引的文件分片",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "上传ID",
                        "name": "upload_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分片索引",
                        "name": "chunk_index",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "分片文件",
                        "name": "chunk",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功",
                        "schema": {
                            "$ref": "#/definitions/models.UploadChunkResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "上传ID不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/chunk/upload/complete/{upload_id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "分片上传"
                ],
                "summary": "完成分片上传",
                "description": "完成所有分片上传，合并文件并生成分享代码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "上传ID",
                        "name": "upload_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "完成上传参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CompleteUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传完成",
                        "schema": {
                            "$ref": "#/definitions/models.ShareResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "上传ID不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/chunk/upload/status/{upload_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "分片上传"
                ],
                "summary": "获取上传状态",
                "description": "获取分片上传的进度和状态",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "上传ID",
                        "name": "upload_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传状态",
                        "schema": {
                            "$ref": "#/definitions/models.ChunkStatusResponse"
                        }
                    },
                    "404": {
                        "description": "上传ID不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/chunk/upload/cancel/{upload_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "分片上传"
                ],
                "summary": "取消分片上传",
                "description": "取消分片上传并清理相关文件",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "上传ID",
                        "name": "upload_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取消成功",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "404": {
                        "description": "上传ID不存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "用户注册",
                "description": "注册新用户账号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/models.UserResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "409": {
                        "description": "用户已存在",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "用户登录",
                "description": "用户登录认证",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/admin/stats": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "管理员"
                ],
                "summary": "获取系统统计",
                "description": "获取系统统计信息",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "统计信息",
                        "schema": {
                            "$ref": "#/definitions/models.AdminStatsResponse"
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2025-09-11T10:00:00Z"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                },
                "uptime": {
                    "type": "string",
                    "example": "2h30m15s"
                }
            }
        },
        "models.SystemConfig": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "站点名称"
                },
                "description": {
                    "type": "string",
                    "description": "站点描述"
                },
                "uploadSize": {
                    "type": "integer",
                    "description": "最大上传大小(MB)"
                },
                "enableChunk": {
                    "type": "integer",
                    "description": "是否启用分片上传"
                },
                "openUpload": {
                    "type": "boolean",
                    "description": "是否开放上传"
                },
                "expireStyle": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "过期时间选项"
                }
            }
        },
        "models.ShareResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "description": "分享代码"
                },
                "download_url": {
                    "type": "string",
                    "description": "下载URL"
                },
                "share_url": {
                    "type": "string",
                    "description": "分享URL"
                },
                "expired_at": {
                    "type": "string",
                    "format": "date-time",
                    "description": "过期时间"
                }
            }
        },
        "models.ShareInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "description": "分享代码"
                },
                "type": {
                    "type": "string",
                    "enum": ["text", "file"],
                    "description": "分享类型"
                },
                "filename": {
                    "type": "string",
                    "description": "文件名（文件类型时）"
                },
                "size": {
                    "type": "integer",
                    "description": "文件大小（文件类型时）"
                },
                "text": {
                    "type": "string",
                    "description": "文本内容（文本类型时）"
                },
                "expired_at": {
                    "type": "string",
                    "format": "date-time",
                    "description": "过期时间"
                },
                "used_count": {
                    "type": "integer",
                    "description": "已使用次数"
                },
                "expired_count": {
                    "type": "integer",
                    "description": "最大使用次数"
                },
                "require_auth": {
                    "type": "boolean",
                    "description": "是否需要认证"
                }
            }
        },
        "models.FileCode": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "expire_count": {
                    "type": "integer"
                },
                "expire_style": {
                    "type": "string"
                },
                "expire_value": {
                    "type": "integer"
                },
                "expired_at": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "owner_ip": {
                    "type": "string"
                },
                "owner_token": {
                    "type": "string"
                },
                "prefix": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "used_count": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.InitUploadRequest": {
            "type": "object",
            "required": [
                "filename",
                "filesize",
                "chunk_size"
            ],
            "properties": {
                "filename": {
                    "type": "string",
                    "description": "文件名"
                },
                "filesize": {
                    "type": "integer",
                    "description": "文件总大小"
                },
                "chunk_size": {
                    "type": "integer",
                    "description": "分片大小"
                },
                "file_hash": {
                    "type": "string",
                    "description": "文件哈希（可选，用于秒传）"
                },
                "expire_value": {
                    "type": "integer",
                    "default": 1,
                    "description": "过期值"
                },
                "expire_style": {
                    "type": "string",
                    "enum": ["minute", "hour", "day", "week", "month", "year", "forever"],
                    "default": "day",
                    "description": "过期样式"
                },
                "require_auth": {
                    "type": "boolean",
                    "default": false,
                    "description": "是否需要认证"
                }
            }
        },
        "models.InitUploadResponse": {
            "type": "object",
            "properties": {
                "upload_id": {
                    "type": "string",
                    "description": "上传ID"
                },
                "total_chunks": {
                    "type": "integer",
                    "description": "总分片数"
                },
                "chunk_size": {
                    "type": "integer",
                    "description": "分片大小"
                },
                "uploaded_chunks": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "description": "已上传的分片索引"
                },
                "existing_file": {
                    "type": "boolean",
                    "description": "文件是否已存在（秒传）"
                }
            }
        },
        "models.CompleteUploadRequest": {
            "type": "object",
            "required": [
                "filename"
            ],
            "properties": {
                "filename": {
                    "type": "string",
                    "description": "最终文件名"
                },
                "expire_style": {
                    "type": "string",
                    "enum": ["minute", "hour", "day", "week", "month", "year", "forever"],
                    "default": "day",
                    "description": "过期样式"
                },
                "expire_value": {
                    "type": "integer",
                    "default": 1,
                    "description": "过期值"
                },
                "require_auth": {
                    "type": "boolean",
                    "default": false,
                    "description": "是否需要认证"
                }
            }
        },
        "models.UploadChunkResponse": {
            "type": "object",
            "properties": {
                "chunk_index": {
                    "type": "integer",
                    "description": "分片索引"
                },
                "chunk_hash": {
                    "type": "string",
                    "description": "分片哈希"
                },
                "progress": {
                    "type": "number",
                    "description": "上传进度(0-100)"
                }
            }
        },
        "models.ChunkStatusResponse": {
            "type": "object",
            "properties": {
                "upload_id": {
                    "type": "string",
                    "description": "上传ID"
                },
                "progress": {
                    "type": "number",
                    "description": "上传进度(0-100)"
                },
                "total_chunks": {
                    "type": "integer",
                    "description": "总分片数"
                },
                "uploaded_chunks": {
                    "type": "integer",
                    "description": "已上传分片数"
                },
                "status": {
                    "type": "string",
                    "enum": ["pending", "uploading", "completed", "failed"],
                    "description": "上传状态"
                }
            }
        },
        "models.RegisterRequest": {
            "type": "object",
            "required": [
                "username",
                "email", 
                "password"
            ],
            "properties": {
                "username": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 50,
                    "description": "用户名"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "description": "邮箱地址"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "description": "密码"
                },
                "nickname": {
                    "type": "string",
                    "maxLength": 50,
                    "description": "昵称"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "username",
                "password"
            ],
            "properties": {
                "username": {
                    "type": "string",
                    "description": "用户名或邮箱"
                },
                "password": {
                    "type": "string",
                    "description": "密码"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "description": "认证令牌"
                },
                "user": {
                    "$ref": "#/definitions/models.User",
                    "description": "用户信息"
                }
            }
        },
        "models.UserResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "data": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "description": "用户ID"
                },
                "username": {
                    "type": "string",
                    "description": "用户名"
                },
                "email": {
                    "type": "string",
                    "description": "邮箱地址"
                },
                "nickname": {
                    "type": "string",
                    "description": "昵称"
                },
                "avatar": {
                    "type": "string",
                    "description": "头像URL"
                },
                "role": {
                    "type": "string",
                    "enum": ["admin", "user"],
                    "description": "用户角色"
                },
                "status": {
                    "type": "string",
                    "enum": ["active", "inactive", "banned"],
                    "description": "用户状态"
                },
                "total_uploads": {
                    "type": "integer",
                    "description": "总上传次数"
                },
                "total_downloads": {
                    "type": "integer",
                    "description": "总下载次数"
                },
                "total_storage": {
                    "type": "integer",
                    "description": "总存储大小"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time",
                    "description": "创建时间"
                }
            }
        },
        "models.AdminStatsResponse": {
            "type": "object",
            "properties": {
                "total_files": {
                    "type": "integer",
                    "description": "总文件数"
                },
                "total_users": {
                    "type": "integer",
                    "description": "总用户数"
                },
                "total_storage": {
                    "type": "integer",
                    "description": "总存储大小"
                },
                "total_downloads": {
                    "type": "integer",
                    "description": "总下载次数"
                },
                "active_shares": {
                    "type": "integer",
                    "description": "活跃分享数"
                },
                "expired_shares": {
                    "type": "integer",
                    "description": "过期分享数"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:12345",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "FileCodeBox API",
	Description:      "FileCodeBox 是一个用于文件分享和代码片段管理的 Web 应用程序，提供完整的 RESTful API 支持文件上传、分享、分片上传、用户管理等功能",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
