// Code generated by hertz generator.

package setup

import (
	"context"
	"errors"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	setupmodel "github.com/zy84338719/fileCodeBox/biz/model/setup"
	setupservice "github.com/zy84338719/fileCodeBox/internal/app/setup"
)

var setupService = setupservice.NewService()

// CheckInitialization .
// @router /setup/check [GET]
func CheckInitialization(ctx context.Context, c *app.RequestContext) {
	initialized, err := setupService.IsSystemInitialized(ctx)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "检查系统初始化状态失败: " + err.Error(),
		})
		return
	}

	resp := &setupmodel.CheckInitializationResp{
		Initialized: initialized,
		Message:     getMessage(initialized),
	}

	c.JSON(consts.StatusOK, resp)
}

// Initialize .
// @router /setup [POST]
func Initialize(ctx context.Context, c *app.RequestContext) {
	var err error
	var req setupmodel.InitializeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": "请求参数错误: " + err.Error(),
		})
		return
	}

	// 验证必填字段
	if err := validateInitializeRequest(&req); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]interface{}{
			"code":    400,
			"message": err.Error(),
		})
		return
	}

	// 检查系统是否已初始化
	initialized, err := setupService.IsSystemInitialized(ctx)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "检查系统初始化状态失败: " + err.Error(),
		})
		return
	}
	if initialized {
		c.JSON(consts.StatusForbidden, map[string]interface{}{
			"code":    403,
			"message": "系统已初始化，禁止重复初始化",
		})
		return
	}

	// 调用 service 初始化系统
	err = setupService.InitializeSystem(ctx, &setupservice.InitializeSystemReq{
		AdminUsername: req.AdminUsername,
		AdminPassword: req.AdminPassword,
		AdminEmail:    req.AdminEmail,
	})
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"code":    500,
			"message": "系统初始化失败: " + err.Error(),
		})
		return
	}

	resp := &setupmodel.InitializeResp{
		Message:  "系统初始化成功",
		Username: req.AdminUsername,
	}

	c.JSON(consts.StatusOK, resp)
}

// validateInitializeRequest 验证初始化请求
func validateInitializeRequest(req *setupmodel.InitializeReq) error {
	if len(req.AdminUsername) < 3 {
		return errors.New("用户名长度至少3个字符")
	}
	if len(req.AdminPassword) < 6 {
		return errors.New("密码长度至少6个字符")
	}
	if req.AdminEmail == "" || len(req.AdminEmail) < 5 {
		return errors.New("邮箱格式无效")
	}
	// 简单邮箱验证
	if !strings.Contains(req.AdminEmail, "@") {
		return errors.New("邮箱格式无效")
	}
	return nil
}

// getMessage 获取状态消息
func getMessage(initialized bool) string {
	if initialized {
		return "系统已初始化"
	}
	return "系统未初始化"
}
