// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: http/setup.proto

package setup

import (
	_ "github.com/zy84338719/fileCodeBox/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckInitializationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInitializationReq) Reset() {
	*x = CheckInitializationReq{}
	mi := &file_http_setup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInitializationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInitializationReq) ProtoMessage() {}

func (x *CheckInitializationReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_setup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInitializationReq.ProtoReflect.Descriptor instead.
func (*CheckInitializationReq) Descriptor() ([]byte, []int) {
	return file_http_setup_proto_rawDescGZIP(), []int{0}
}

type CheckInitializationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Initialized   bool                   `protobuf:"varint,1,opt,name=initialized,proto3" json:"initialized,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInitializationResp) Reset() {
	*x = CheckInitializationResp{}
	mi := &file_http_setup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInitializationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInitializationResp) ProtoMessage() {}

func (x *CheckInitializationResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_setup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInitializationResp.ProtoReflect.Descriptor instead.
func (*CheckInitializationResp) Descriptor() ([]byte, []int) {
	return file_http_setup_proto_rawDescGZIP(), []int{1}
}

func (x *CheckInitializationResp) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

func (x *CheckInitializationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InitializeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUsername string                 `protobuf:"bytes,1,opt,name=admin_username,json=adminUsername,proto3" json:"admin_username,omitempty"`
	AdminPassword string                 `protobuf:"bytes,2,opt,name=admin_password,json=adminPassword,proto3" json:"admin_password,omitempty"`
	AdminEmail    string                 `protobuf:"bytes,3,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"`
	BaseConfig    *BaseConfig            `protobuf:"bytes,4,opt,name=base_config,json=baseConfig,proto3" json:"base_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeReq) Reset() {
	*x = InitializeReq{}
	mi := &file_http_setup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeReq) ProtoMessage() {}

func (x *InitializeReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_setup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeReq.ProtoReflect.Descriptor instead.
func (*InitializeReq) Descriptor() ([]byte, []int) {
	return file_http_setup_proto_rawDescGZIP(), []int{2}
}

func (x *InitializeReq) GetAdminUsername() string {
	if x != nil {
		return x.AdminUsername
	}
	return ""
}

func (x *InitializeReq) GetAdminPassword() string {
	if x != nil {
		return x.AdminPassword
	}
	return ""
}

func (x *InitializeReq) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

func (x *InitializeReq) GetBaseConfig() *BaseConfig {
	if x != nil {
		return x.BaseConfig
	}
	return nil
}

type BaseConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseConfig) Reset() {
	*x = BaseConfig{}
	mi := &file_http_setup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseConfig) ProtoMessage() {}

func (x *BaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_http_setup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseConfig.ProtoReflect.Descriptor instead.
func (*BaseConfig) Descriptor() ([]byte, []int) {
	return file_http_setup_proto_rawDescGZIP(), []int{3}
}

func (x *BaseConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BaseConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *BaseConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type InitializeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResp) Reset() {
	*x = InitializeResp{}
	mi := &file_http_setup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResp) ProtoMessage() {}

func (x *InitializeResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_setup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResp.ProtoReflect.Descriptor instead.
func (*InitializeResp) Descriptor() ([]byte, []int) {
	return file_http_setup_proto_rawDescGZIP(), []int{4}
}

func (x *InitializeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitializeResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_http_setup_proto protoreflect.FileDescriptor

const file_http_setup_proto_rawDesc = "" +
	"\n" +
	"\x10http/setup.proto\x12\n" +
	"http.setup\x1a\rapi/api.proto\"\x18\n" +
	"\x16CheckInitializationReq\"s\n" +
	"\x17CheckInitializationResp\x121\n" +
	"\vinitialized\x18\x01 \x01(\bB\x0fʻ\x18\vinitializedR\vinitialized\x12%\n" +
	"\amessage\x18\x02 \x01(\tB\vʻ\x18\amessageR\amessage\"\x81\x02\n" +
	"\rInitializeReq\x129\n" +
	"\x0eadmin_username\x18\x01 \x01(\tB\x12ʻ\x18\x0eadmin_usernameR\radminUsername\x129\n" +
	"\x0eadmin_password\x18\x02 \x01(\tB\x12ʻ\x18\x0eadmin_passwordR\radminPassword\x120\n" +
	"\vadmin_email\x18\x03 \x01(\tB\x0fʻ\x18\vadmin_emailR\n" +
	"adminEmail\x12H\n" +
	"\vbase_config\x18\x04 \x01(\v2\x16.http.setup.BaseConfigB\x0fʻ\x18\vbase_configR\n" +
	"baseConfig\"\x99\x01\n" +
	"\n" +
	"BaseConfig\x12\x1c\n" +
	"\x04name\x18\x01 \x01(\tB\bʻ\x18\x04nameR\x04name\x121\n" +
	"\vdescription\x18\x02 \x01(\tB\x0fʻ\x18\vdescriptionR\vdescription\x12\x1c\n" +
	"\x04port\x18\x03 \x01(\x05B\bʻ\x18\x04portR\x04port\x12\x1c\n" +
	"\x04host\x18\x04 \x01(\tB\bʻ\x18\x04hostR\x04host\"a\n" +
	"\x0eInitializeResp\x12%\n" +
	"\amessage\x18\x01 \x01(\tB\vʻ\x18\amessageR\amessage\x12(\n" +
	"\busername\x18\x02 \x01(\tB\fʻ\x18\busernameR\busername2\xd1\x01\n" +
	"\fSetupService\x12p\n" +
	"\x13CheckInitialization\x12\".http.setup.CheckInitializationReq\x1a#.http.setup.CheckInitializationResp\"\x10\xca\xc1\x18\f/setup/check\x12O\n" +
	"\n" +
	"Initialize\x12\x19.http.setup.InitializeReq\x1a\x1a.http.setup.InitializeResp\"\n" +
	"\xd2\xc1\x18\x06/setupB3Z1github.com/zy84338719/fileCodeBox/biz/model/setupb\x06proto3"

var (
	file_http_setup_proto_rawDescOnce sync.Once
	file_http_setup_proto_rawDescData []byte
)

func file_http_setup_proto_rawDescGZIP() []byte {
	file_http_setup_proto_rawDescOnce.Do(func() {
		file_http_setup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_http_setup_proto_rawDesc), len(file_http_setup_proto_rawDesc)))
	})
	return file_http_setup_proto_rawDescData
}

var file_http_setup_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_http_setup_proto_goTypes = []any{
	(*CheckInitializationReq)(nil),  // 0: http.setup.CheckInitializationReq
	(*CheckInitializationResp)(nil), // 1: http.setup.CheckInitializationResp
	(*InitializeReq)(nil),           // 2: http.setup.InitializeReq
	(*BaseConfig)(nil),              // 3: http.setup.BaseConfig
	(*InitializeResp)(nil),          // 4: http.setup.InitializeResp
}
var file_http_setup_proto_depIdxs = []int32{
	3, // 0: http.setup.InitializeReq.base_config:type_name -> http.setup.BaseConfig
	0, // 1: http.setup.SetupService.CheckInitialization:input_type -> http.setup.CheckInitializationReq
	2, // 2: http.setup.SetupService.Initialize:input_type -> http.setup.InitializeReq
	1, // 3: http.setup.SetupService.CheckInitialization:output_type -> http.setup.CheckInitializationResp
	4, // 4: http.setup.SetupService.Initialize:output_type -> http.setup.InitializeResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_http_setup_proto_init() }
func file_http_setup_proto_init() {
	if File_http_setup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_setup_proto_rawDesc), len(file_http_setup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_http_setup_proto_goTypes,
		DependencyIndexes: file_http_setup_proto_depIdxs,
		MessageInfos:      file_http_setup_proto_msgTypes,
	}.Build()
	File_http_setup_proto = out.File
	file_http_setup_proto_goTypes = nil
	file_http_setup_proto_depIdxs = nil
}
