// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: http/health.proto

package health

import (
	_ "github.com/zy84338719/fileCodeBox/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckReq) Reset() {
	*x = HealthCheckReq{}
	mi := &file_http_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckReq) ProtoMessage() {}

func (x *HealthCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckReq.ProtoReflect.Descriptor instead.
func (*HealthCheckReq) Descriptor() ([]byte, []int) {
	return file_http_health_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResp) Reset() {
	*x = HealthCheckResp{}
	mi := &file_http_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResp) ProtoMessage() {}

func (x *HealthCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResp.ProtoReflect.Descriptor instead.
func (*HealthCheckResp) Descriptor() ([]byte, []int) {
	return file_http_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResp) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ReadinessReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessReq) Reset() {
	*x = ReadinessReq{}
	mi := &file_http_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessReq) ProtoMessage() {}

func (x *ReadinessReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessReq.ProtoReflect.Descriptor instead.
func (*ReadinessReq) Descriptor() ([]byte, []int) {
	return file_http_health_proto_rawDescGZIP(), []int{2}
}

type ReadinessResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Database      bool                   `protobuf:"varint,2,opt,name=database,proto3" json:"database,omitempty"`
	Redis         bool                   `protobuf:"varint,3,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessResp) Reset() {
	*x = ReadinessResp{}
	mi := &file_http_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessResp) ProtoMessage() {}

func (x *ReadinessResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessResp.ProtoReflect.Descriptor instead.
func (*ReadinessResp) Descriptor() ([]byte, []int) {
	return file_http_health_proto_rawDescGZIP(), []int{3}
}

func (x *ReadinessResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReadinessResp) GetDatabase() bool {
	if x != nil {
		return x.Database
	}
	return false
}

func (x *ReadinessResp) GetRedis() bool {
	if x != nil {
		return x.Redis
	}
	return false
}

type LivenessReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessReq) Reset() {
	*x = LivenessReq{}
	mi := &file_http_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessReq) ProtoMessage() {}

func (x *LivenessReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessReq.ProtoReflect.Descriptor instead.
func (*LivenessReq) Descriptor() ([]byte, []int) {
	return file_http_health_proto_rawDescGZIP(), []int{4}
}

type LivenessResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessResp) Reset() {
	*x = LivenessResp{}
	mi := &file_http_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessResp) ProtoMessage() {}

func (x *LivenessResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessResp.ProtoReflect.Descriptor instead.
func (*LivenessResp) Descriptor() ([]byte, []int) {
	return file_http_health_proto_rawDescGZIP(), []int{5}
}

func (x *LivenessResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type VersionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionReq) Reset() {
	*x = VersionReq{}
	mi := &file_http_health_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionReq) ProtoMessage() {}

func (x *VersionReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_health_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionReq.ProtoReflect.Descriptor instead.
func (*VersionReq) Descriptor() ([]byte, []int) {
	return file_http_health_proto_rawDescGZIP(), []int{6}
}

type VersionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	BuildTime     string                 `protobuf:"bytes,3,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	GitCommit     string                 `protobuf:"bytes,4,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	GoVersion     string                 `protobuf:"bytes,5,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResp) Reset() {
	*x = VersionResp{}
	mi := &file_http_health_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResp) ProtoMessage() {}

func (x *VersionResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_health_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResp.ProtoReflect.Descriptor instead.
func (*VersionResp) Descriptor() ([]byte, []int) {
	return file_http_health_proto_rawDescGZIP(), []int{7}
}

func (x *VersionResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VersionResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionResp) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *VersionResp) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *VersionResp) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_http_health_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_http_health_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_http_health_proto_rawDescGZIP(), []int{8}
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_http_health_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_http_health_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_http_health_proto_rawDescGZIP(), []int{9}
}

func (x *PingResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_http_health_proto protoreflect.FileDescriptor

const file_http_health_proto_rawDesc = "" +
	"\n" +
	"\x11http/health.proto\x12\vhttp.health\x1a\rapi/api.proto\"\x10\n" +
	"\x0eHealthCheckReq\"b\n" +
	"\x0fHealthCheckResp\x12\"\n" +
	"\x06status\x18\x01 \x01(\tB\n" +
	"ʻ\x18\x06statusR\x06status\x12+\n" +
	"\ttimestamp\x18\x02 \x01(\tB\rʻ\x18\ttimestampR\ttimestamp\"\x0e\n" +
	"\fReadinessReq\"~\n" +
	"\rReadinessResp\x12\"\n" +
	"\x06status\x18\x01 \x01(\tB\n" +
	"ʻ\x18\x06statusR\x06status\x12(\n" +
	"\bdatabase\x18\x02 \x01(\bB\fʻ\x18\bdatabaseR\bdatabase\x12\x1f\n" +
	"\x05redis\x18\x03 \x01(\bB\tʻ\x18\x05redisR\x05redis\"\r\n" +
	"\vLivenessReq\"2\n" +
	"\fLivenessResp\x12\"\n" +
	"\x06status\x18\x01 \x01(\tB\n" +
	"ʻ\x18\x06statusR\x06status\"\f\n" +
	"\n" +
	"VersionReq\"\xdf\x01\n" +
	"\vVersionResp\x12\x1c\n" +
	"\x04name\x18\x01 \x01(\tB\bʻ\x18\x04nameR\x04name\x12%\n" +
	"\aversion\x18\x02 \x01(\tB\vʻ\x18\aversionR\aversion\x12-\n" +
	"\n" +
	"build_time\x18\x03 \x01(\tB\x0eʻ\x18\n" +
	"build_timeR\tbuildTime\x12-\n" +
	"\n" +
	"git_commit\x18\x04 \x01(\tB\x0eʻ\x18\n" +
	"git_commitR\tgitCommit\x12-\n" +
	"\n" +
	"go_version\x18\x05 \x01(\tB\x0eʻ\x18\n" +
	"go_versionR\tgoVersion\"\t\n" +
	"\aPingReq\"1\n" +
	"\bPingResp\x12%\n" +
	"\amessage\x18\x01 \x01(\tB\vʻ\x18\amessageR\amessage2\x89\x03\n" +
	"\rHealthService\x12P\n" +
	"\x06Health\x12\x1b.http.health.HealthCheckReq\x1a\x1c.http.health.HealthCheckResp\"\v\xca\xc1\x18\a/health\x12N\n" +
	"\tReadiness\x12\x19.http.health.ReadinessReq\x1a\x1a.http.health.ReadinessResp\"\n" +
	"\xca\xc1\x18\x06/ready\x12J\n" +
	"\bLiveness\x12\x18.http.health.LivenessReq\x1a\x19.http.health.LivenessResp\"\t\xca\xc1\x18\x05/live\x12J\n" +
	"\aVersion\x12\x17.http.health.VersionReq\x1a\x18.http.health.VersionResp\"\f\xca\xc1\x18\b/version\x12>\n" +
	"\x04Ping\x12\x14.http.health.PingReq\x1a\x15.http.health.PingResp\"\t\xca\xc1\x18\x05/pingB4Z2github.com/zy84338719/fileCodeBox/biz/model/healthb\x06proto3"

var (
	file_http_health_proto_rawDescOnce sync.Once
	file_http_health_proto_rawDescData []byte
)

func file_http_health_proto_rawDescGZIP() []byte {
	file_http_health_proto_rawDescOnce.Do(func() {
		file_http_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_http_health_proto_rawDesc), len(file_http_health_proto_rawDesc)))
	})
	return file_http_health_proto_rawDescData
}

var file_http_health_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_http_health_proto_goTypes = []any{
	(*HealthCheckReq)(nil),  // 0: http.health.HealthCheckReq
	(*HealthCheckResp)(nil), // 1: http.health.HealthCheckResp
	(*ReadinessReq)(nil),    // 2: http.health.ReadinessReq
	(*ReadinessResp)(nil),   // 3: http.health.ReadinessResp
	(*LivenessReq)(nil),     // 4: http.health.LivenessReq
	(*LivenessResp)(nil),    // 5: http.health.LivenessResp
	(*VersionReq)(nil),      // 6: http.health.VersionReq
	(*VersionResp)(nil),     // 7: http.health.VersionResp
	(*PingReq)(nil),         // 8: http.health.PingReq
	(*PingResp)(nil),        // 9: http.health.PingResp
}
var file_http_health_proto_depIdxs = []int32{
	0, // 0: http.health.HealthService.Health:input_type -> http.health.HealthCheckReq
	2, // 1: http.health.HealthService.Readiness:input_type -> http.health.ReadinessReq
	4, // 2: http.health.HealthService.Liveness:input_type -> http.health.LivenessReq
	6, // 3: http.health.HealthService.Version:input_type -> http.health.VersionReq
	8, // 4: http.health.HealthService.Ping:input_type -> http.health.PingReq
	1, // 5: http.health.HealthService.Health:output_type -> http.health.HealthCheckResp
	3, // 6: http.health.HealthService.Readiness:output_type -> http.health.ReadinessResp
	5, // 7: http.health.HealthService.Liveness:output_type -> http.health.LivenessResp
	7, // 8: http.health.HealthService.Version:output_type -> http.health.VersionResp
	9, // 9: http.health.HealthService.Ping:output_type -> http.health.PingResp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_http_health_proto_init() }
func file_http_health_proto_init() {
	if File_http_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_health_proto_rawDesc), len(file_http_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_http_health_proto_goTypes,
		DependencyIndexes: file_http_health_proto_depIdxs,
		MessageInfos:      file_http_health_proto_msgTypes,
	}.Build()
	File_http_health_proto = out.File
	file_http_health_proto_goTypes = nil
	file_http_health_proto_depIdxs = nil
}
