// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_api_api_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50101,
		Name:          "api.raw_body",
		Tag:           "bytes,50101,opt,name=raw_body",
		Filename:      "api/api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50102,
		Name:          "api.query",
		Tag:           "bytes,50102,opt,name=query",
		Filename:      "api/api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50103,
		Name:          "api.header",
		Tag:           "bytes,50103,opt,name=header",
		Filename:      "api/api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50104,
		Name:          "api.cookie",
		Tag:           "bytes,50104,opt,name=cookie",
		Filename:      "api/api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50105,
		Name:          "api.body",
		Tag:           "bytes,50105,opt,name=body",
		Filename:      "api/api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50106,
		Name:          "api.path",
		Tag:           "bytes,50106,opt,name=path",
		Filename:      "api/api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50107,
		Name:          "api.vd",
		Tag:           "bytes,50107,opt,name=vd",
		Filename:      "api/api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50108,
		Name:          "api.form",
		Tag:           "bytes,50108,opt,name=form",
		Filename:      "api/api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51001,
		Name:          "api.go_tag",
		Tag:           "bytes,51001,opt,name=go_tag",
		Filename:      "api/api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50201,
		Name:          "api.get",
		Tag:           "bytes,50201,opt,name=get",
		Filename:      "api/api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50202,
		Name:          "api.post",
		Tag:           "bytes,50202,opt,name=post",
		Filename:      "api/api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50203,
		Name:          "api.put",
		Tag:           "bytes,50203,opt,name=put",
		Filename:      "api/api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50204,
		Name:          "api.delete",
		Tag:           "bytes,50204,opt,name=delete",
		Filename:      "api/api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50205,
		Name:          "api.patch",
		Tag:           "bytes,50205,opt,name=patch",
		Filename:      "api/api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50402,
		Name:          "api.base_domain",
		Tag:           "bytes,50402,opt,name=base_domain",
		Filename:      "api/api.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string raw_body = 50101;
	E_RawBody = &file_api_api_proto_extTypes[0]
	// optional string query = 50102;
	E_Query = &file_api_api_proto_extTypes[1]
	// optional string header = 50103;
	E_Header = &file_api_api_proto_extTypes[2]
	// optional string cookie = 50104;
	E_Cookie = &file_api_api_proto_extTypes[3]
	// optional string body = 50105;
	E_Body = &file_api_api_proto_extTypes[4]
	// optional string path = 50106;
	E_Path = &file_api_api_proto_extTypes[5]
	// optional string vd = 50107;
	E_Vd = &file_api_api_proto_extTypes[6]
	// optional string form = 50108;
	E_Form = &file_api_api_proto_extTypes[7]
	// optional string go_tag = 51001;
	E_GoTag = &file_api_api_proto_extTypes[8]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string get = 50201;
	E_Get = &file_api_api_proto_extTypes[9]
	// optional string post = 50202;
	E_Post = &file_api_api_proto_extTypes[10]
	// optional string put = 50203;
	E_Put = &file_api_api_proto_extTypes[11]
	// optional string delete = 50204;
	E_Delete = &file_api_api_proto_extTypes[12]
	// optional string patch = 50205;
	E_Patch = &file_api_api_proto_extTypes[13]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional string base_domain = 50402;
	E_BaseDomain = &file_api_api_proto_extTypes[14]
)

var File_api_api_proto protoreflect.FileDescriptor

const file_api_api_proto_rawDesc = "" +
	"\n" +
	"\rapi/api.proto\x12\x03api\x1a google/protobuf/descriptor.proto::\n" +
	"\braw_body\x12\x1d.google.protobuf.FieldOptions\x18\xb5\x87\x03 \x01(\tR\arawBody:5\n" +
	"\x05query\x12\x1d.google.protobuf.FieldOptions\x18\xb6\x87\x03 \x01(\tR\x05query:7\n" +
	"\x06header\x12\x1d.google.protobuf.FieldOptions\x18\xb7\x87\x03 \x01(\tR\x06header:7\n" +
	"\x06cookie\x12\x1d.google.protobuf.FieldOptions\x18\xb8\x87\x03 \x01(\tR\x06cookie:3\n" +
	"\x04body\x12\x1d.google.protobuf.FieldOptions\x18\xb9\x87\x03 \x01(\tR\x04body:3\n" +
	"\x04path\x12\x1d.google.protobuf.FieldOptions\x18\xba\x87\x03 \x01(\tR\x04path:/\n" +
	"\x02vd\x12\x1d.google.protobuf.FieldOptions\x18\xbb\x87\x03 \x01(\tR\x02vd:3\n" +
	"\x04form\x12\x1d.google.protobuf.FieldOptions\x18\xbc\x87\x03 \x01(\tR\x04form:6\n" +
	"\x06go_tag\x12\x1d.google.protobuf.FieldOptions\x18\xb9\x8e\x03 \x01(\tR\x05goTag:2\n" +
	"\x03get\x12\x1e.google.protobuf.MethodOptions\x18\x99\x88\x03 \x01(\tR\x03get:4\n" +
	"\x04post\x12\x1e.google.protobuf.MethodOptions\x18\x9a\x88\x03 \x01(\tR\x04post:2\n" +
	"\x03put\x12\x1e.google.protobuf.MethodOptions\x18\x9b\x88\x03 \x01(\tR\x03put:8\n" +
	"\x06delete\x12\x1e.google.protobuf.MethodOptions\x18\x9c\x88\x03 \x01(\tR\x06delete:6\n" +
	"\x05patch\x12\x1e.google.protobuf.MethodOptions\x18\x9d\x88\x03 \x01(\tR\x05patch:B\n" +
	"\vbase_domain\x12\x1f.google.protobuf.ServiceOptions\x18\xe2\x89\x03 \x01(\tR\n" +
	"baseDomainB1Z/github.com/zy84338719/fileCodeBox/biz/model/api"

var file_api_api_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil),   // 0: google.protobuf.FieldOptions
	(*descriptorpb.MethodOptions)(nil),  // 1: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 2: google.protobuf.ServiceOptions
}
var file_api_api_proto_depIdxs = []int32{
	0,  // 0: api.raw_body:extendee -> google.protobuf.FieldOptions
	0,  // 1: api.query:extendee -> google.protobuf.FieldOptions
	0,  // 2: api.header:extendee -> google.protobuf.FieldOptions
	0,  // 3: api.cookie:extendee -> google.protobuf.FieldOptions
	0,  // 4: api.body:extendee -> google.protobuf.FieldOptions
	0,  // 5: api.path:extendee -> google.protobuf.FieldOptions
	0,  // 6: api.vd:extendee -> google.protobuf.FieldOptions
	0,  // 7: api.form:extendee -> google.protobuf.FieldOptions
	0,  // 8: api.go_tag:extendee -> google.protobuf.FieldOptions
	1,  // 9: api.get:extendee -> google.protobuf.MethodOptions
	1,  // 10: api.post:extendee -> google.protobuf.MethodOptions
	1,  // 11: api.put:extendee -> google.protobuf.MethodOptions
	1,  // 12: api.delete:extendee -> google.protobuf.MethodOptions
	1,  // 13: api.patch:extendee -> google.protobuf.MethodOptions
	2,  // 14: api.base_domain:extendee -> google.protobuf.ServiceOptions
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	0,  // [0:15] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 15,
			NumServices:   0,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		ExtensionInfos:    file_api_api_proto_extTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}
