// Code generated by hertz generator.

package setup

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	setup "github.com/zy84338719/fileCodeBox/biz/model/setup"
)

// CheckInitialization .
// @router /setup/check [GET]
func CheckInitialization(ctx context.Context, c *app.RequestContext) {
	var err error
	var req setup.CheckInitializationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(setup.CheckInitializationResp)

	c.JSON(consts.StatusOK, resp)
}

// Initialize .
// @router /setup [POST]
func Initialize(ctx context.Context, c *app.RequestContext) {
	var err error
	var req setup.InitializeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(setup.InitializeResp)

	c.JSON(consts.StatusOK, resp)
}
